"""Pass 22: users.html, dispatcher/lifts.html CSS comments, qr-scanner.html."""
from pathlib import Path

TRANSLATIONS = [
    # ── users.html CSS comments ───────────────────────────────────────────────
    ("/* Кастомні стилі для адмін-панелі */",
     "/* Estilos personalizados para o painel admin */"),
    ("/* Estilos para модального вікна */",
     "/* Estilos para janela modal */"),
    ("/* Estilos para таблиці */", "/* Estilos para tabela */"),
    ("/* Estilos para карток статистики */",
     "/* Estilos para cartões de estatísticas */"),
    ("/* Кастомні стилі для форми */",
     "/* Estilos personalizados para formulário */"),

    # ── users.html UI ─────────────────────────────────────────────────────────
    ("<p>Всього користувачів</p>", "<p>Total de utilizadores</p>"),
    ("<p>Активних користувачів</p>", "<p>Utilizadores activos</p>"),
    ("<p>Клієнтів</p>", "<p>Clientes</p>"),
    ("<p>Техніків</p>", "<p>Técnicos</p>"),
    ("<p>Адміністраторів</p>", "<p>Administradores</p>"),
    ("<!-- Панель дій -->", "<!-- Painel de acções -->"),
    ("<h3 class=\"card-title\">Gestão користувачами</h3>",
     "<h3 class=\"card-title\">Gestão de utilizadores</h3>"),
    ("<i class=\"fas fa-plus\"></i> Adicionar користувача",
     "<i class=\"fas fa-plus\"></i> Adicionar utilizador"),
    ("placeholder=\"Pesquisar користувачів...\"",
     "placeholder=\"Pesquisar utilizadores...\""),
    ("<option value=\"all\">Всі ролі</option>",
     "<option value=\"all\">Todos os papéis</option>"),
    ("<option value=\"admin\">Адміністратори</option>",
     "<option value=\"admin\">Administradores</option>"),
    ("<option value=\"technician\">Техніки</option>",
     "<option value=\"technician\">Técnicos</option>"),
    ("<option value=\"client\">Клієнти</option>",
     "<option value=\"client\">Clientes</option>"),
    ("<option value=\"dispatcher\">Диспетчери</option>",
     "<option value=\"dispatcher\">Despachantes</option>"),
    ("<th>Ім'я</th>", "<th>Nome</th>"),
    ("<th>Роль</th>", "<th>Papel</th>"),
    ("<!-- Модальне вікно для додавання/редагування користувача -->",
     "<!-- Janela modal para adicionar/editar utilizador -->"),
    ("<h5 class=\"modal-title\" id=\"modalTitle\">Adicionar користувача</h5>",
     "<h5 class=\"modal-title\" id=\"modalTitle\">Adicionar utilizador</h5>"),
    ("<label for=\"userFirstName\">Ім'я *</label>",
     "<label for=\"userFirstName\">Nome *</label>"),
    ("<label for=\"userLastName\">Прізвище *</label>",
     "<label for=\"userLastName\">Apelido *</label>"),
    ("<label for=\"userPhone\">Телефон</label>",
     "<label for=\"userPhone\">Telefone</label>"),
    ("<h6 class=\"form-section-title\">Роль та статус</h6>",
     "<h6 class=\"form-section-title\">Papel e estado</h6>"),
    ("<label for=\"userRole\">Роль *</label>",
     "<label for=\"userRole\">Papel *</label>"),
    ("<option value=\"\">Seleccione роль...</option>",
     "<option value=\"\">Seleccione papel...</option>"),
    ("<label for=\"userStatus\">Статус *</label>",
     "<label for=\"userStatus\">Estado *</label>"),
    ("<h6 class=\"form-section-title\">Безпека</h6>",
     "<h6 class=\"form-section-title\">Segurança</h6>"),
    ("Пароль\n                                    <small class=\"text-muted\">(залиште порожнім для автоматичної генерації)</small>",
     "Palavra-passe\n                                    <small class=\"text-muted\">(deixe em branco para geração automática)</small>"),
    ("placeholder=\"Буде згенеровано автоматично...\"",
     "placeholder=\"Será gerado automaticamente...\""),
    ("title=\"Згенерувати novo пароль\"",
     "title=\"Gerar nova palavra-passe\""),
    ("<i class=\"fas fa-sync-alt\"></i> Генерувати",
     "<i class=\"fas fa-sync-alt\"></i> Gerar"),
    ("title=\"Mostrar/Сховати пароль\"",
     "title=\"Mostrar/Ocultar palavra-passe\""),
    ("title=\"Копіювати пароль\" disabled",
     "title=\"Copiar palavra-passe\" disabled"),
    ("<i class=\"fas fa-info-circle\"></i> Згенерований пароль буде сильним (10+ символів, A-Z, a-z, 0-9, спецсимволи)",
     "<i class=\"fas fa-info-circle\"></i> A palavra-passe gerada será forte (10+ caracteres, A-Z, a-z, 0-9, caracteres especiais)"),
    ("<i class=\"fas fa-check-circle\"></i> <strong>Пароль згенеровано!</strong> Обов'язково скопіюйте його для передачі користувачу.",
     "<i class=\"fas fa-check-circle\"></i> <strong>Palavra-passe gerada!</strong> Copie-a obrigatoriamente para transmitir ao utilizador."),

    # ── users.html JS ─────────────────────────────────────────────────────────
    ("// Генерація пароля", "// Geração de palavra-passe"),
    ("// Autoматично mostrar пароль", "// Mostrar palavra-passe automaticamente"),
    ("// Mostrar/сховати пароль", "// Mostrar/ocultar palavra-passe"),
    ("// Копіювати пароль", "// Copiar palavra-passe"),
    ("this.showNotification('Пароль скопійовано в буфер обміну!', 'info');",
     "this.showNotification('Palavra-passe copiada para a área de transferência!', 'info');"),
    ("// Alterar іконку на галочку", "// Alterar ícone para marca de verificação"),
    ("this.showNotification('Erro копіювання. Скопіюйте вручну.', 'warning');",
     "this.showNotification('Erro ao copiar. Copie manualmente.', 'warning');"),
    ("// Увімкнути кнопку копіювання при введенні пароля",
     "// Activar botão de cópia ao introduzir palavra-passe"),
    ("// При відкритті модального вікна для нового користувача - згенерувати пароль автоматично",
     "// Ao abrir janela modal para novo utilizador - gerar palavra-passe automaticamente"),
    ("// Novo utilizador - автоматично генерувати пароль",
     "// Novo utilizador - gerar palavra-passe automaticamente"),
    ("// Ocultar alert при закритті модального вікна",
     "// Ocultar alerta ao fechar janela modal"),
    ("// Символи для генерації (виchaveені неоднозначні: 0, O, I, l, 1)",
     "// Caracteres para geração (excluídos ambíguos: 0, O, I, l, 1)"),
    ("// Забезпечуємо мінімум по одному символу кожного типу",
     "// Garantir mínimo de um caractere de cada tipo"),
    ("// Заповнюємо решту довжини", "// Preencher o restante do comprimento"),
    ("// Перемішуємо символи", "// Misturar caracteres"),
    ("console.log('🔄 A carregar користувачів з API...');",
     "console.log('🔄 A carregar utilizadores da API...');"),
    ("throw new Error('Erro завантаження користувачів');",
     "throw new Error('Erro ao carregar utilizadores');"),
    ("// Зберігаємо оригінальні індекси для стабільного displayId",
     "// Guardar índices originais para displayId estável"),
    ("console.log('✅ Завантажено користувачів:', this.allUsers.length, this.allUsers);",
     "console.log('✅ Utilizadores carregados:', this.allUsers.length, this.allUsers);"),
    ("console.error('❌ Erro ao carregar користувачів:', error);",
     "console.error('❌ Erro ao carregar utilizadores:', error);"),
    ("alert('Não вдалося descarregar користувачів. Перевірте підchaveення до сервера.');",
     "alert('Não foi possível carregar utilizadores. Verifique a ligação ao servidor.');"),
    ("// Eliminado - тепер зберігання через API при створенні/редагуванні",
     "// Eliminado - agora guardado via API ao criar/editar"),
    ("console.log('ℹ️ Utilizadores зберігаються через API endpoints');",
     "console.log('ℹ️ Utilizadores guardados via endpoints de API');"),
    ("// Додавання користувача", "// Adicionar utilizador"),
    ("$('#modalTitle').text('Editar користувача');",
     "$('#modalTitle').text('Editar utilizador');"),
    ("$('#modalTitle').text('Adicionar користувача');",
     "$('#modalTitle').text('Adicionar utilizador');"),
    ("// Збереження форми", "// Guardar formulário"),
    ("// Закриття модального вікна", "// Fechar janela modal"),
    ("<h5>Utilizadores не encontrado</h5>",
     "<h5>Utilizadores não encontrados</h5>"),
    ("<p class=\"text-muted\">Спробуйте змінити filtros або додати нового користувача</p>",
     "<p class=\"text-muted\">Tente alterar os filtros ou adicionar um novo utilizador</p>"),
    ("<i class=\"fas fa-plus\"></i> Adicionar користувача",
     "<i class=\"fas fa-plus\"></i> Adicionar utilizador"),
    ("// ✅ ВИПРАВЛЕННЯ: Конвертуємо ObjectId в string",
     "// ✅ CORRECÇÃO: Converter ObjectId em string"),
    ("console.error('❌ Користувач без ID:', user);",
     "console.error('❌ Utilizador sem ID:', user);"),
    ("return; // Пропускаємо користувачів без ID",
     "return; // Ignorar utilizadores sem ID"),
    ("// ✅ Використовуємо оригінальний індекс (стабільний displayId)",
     "// ✅ Usar índice original (displayId estável)"),
    ("// Формуємо ім'я з fallback", "// Formar nome com fallback"),
    ("title=\"Eliminar користувача\"",
     "title=\"Eliminar utilizador\""),
    ("A mostrar ${this.filteredUsers.length} з ${this.filteredUsers.length} користувачів",
     "A mostrar ${this.filteredUsers.length} de ${this.filteredUsers.length} utilizadores"),
    ("A mostrar ${Math.min(this.itemsPerPage, this.filteredUsers.length)} з ${this.filteredUsers.length} користувачів",
     "A mostrar ${Math.min(this.itemsPerPage, this.filteredUsers.length)} de ${this.filteredUsers.length} utilizadores"),
    ("// Сторінки", "// Páginas"),
    ("// Обробник кліків по пагінації", "// Handler de cliques na paginação"),
    ("// isActive - поле акаунта (true за замовчуванням); status - поле присутності (online/offline/busy)",
     "// isActive - campo da conta (true por defeito); status - campo de presença (online/offline/busy)"),
    ("// Перевіряємо чи це чистий pesquisar por числу (002, 003, 1)",
     "// Verificar se é pesquisa pura por número (002, 003, 1)"),
    ("// ✅ Використовуємо збережений оригінальний індекс",
     "// ✅ Usar índice original guardado"),
    ("// Якщо це ТІЛЬКИ число (002), шукаємо точне співпадіння",
     "// Se é APENAS número (002), pesquisar correspondência exacta"),
    ("// Інакше - pesquisar por всіх полях",
     "// Caso contrário - pesquisar em todos os campos"),
    ("// Suporte обох варіантів: tech та technician",
     "// Suporte de ambas as variantes: tech e technician"),
    ("// Прокручуємо до таблиці", "// Deslocar para a tabela"),
    (".attr('placeholder', 'Залиште порожнім для збереження поточного пароля');",
     ".attr('placeholder', 'Deixe em branco para manter a palavra-passe actual');"),
    ("// Autoматично генерувати пароль для нового користувача",
     "// Gerar palavra-passe automaticamente para novo utilizador"),
    ("'<i class=\"fas fa-check-circle\"></i> Пароль згенеровано автоматично! Обов\\'язково скопіюйте його перед збереженням.'",
     "'<i class=\"fas fa-check-circle\"></i> Palavra-passe gerada automaticamente! Copie-a obrigatoriamente antes de guardar.'"),
    ("let passwordToSend = null; // Пароль для показу в модальному вікні",
     "let passwordToSend = null; // Palavra-passe para mostrar na janela modal"),
    ("// Guardar пароль для показу (тільки якщо він був згенерований)",
     "// Guardar palavra-passe para mostrar (só se foi gerada)"),
    ("console.log('➕ Criar novo utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criar novo utilizador:', userData.email);\n",
     "console.log('➕ A criar novo utilizador:', userData.email);\n"),
    ("console.log('➕ Criação nuevo utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criação nouvo utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criar novo utilizador:',",
     "console.log('➕ A criar novo utilizador:',"),
    ("console.log('➕ Criar novo utilizador: ',",
     "console.log('➕ A criar novo utilizador: ',"),
    ("console.log('➕ Criação novo utilizador:',",
     "console.log('➕ A criar novo utilizador:',"),
    ("console.log('➕ Criar novo utilizador', userData.email);",
     "console.log('➕ A criar novo utilizador', userData.email);"),
    ("console.log('➕ Criar novo Utilizador:',",
     "console.log('➕ A criar novo utilizador:',"),
    ("console.log('➕ Criar novo Utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criação de Utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criar novo utilizador:' , userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criação de utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criação de novo utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criação do novo utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    ("console.log('➕ Criar utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),
    # real line
    ("console.log('➕ Criar novo utilizador:', userData.email);",
     "console.log('➕ A criar novo utilizador:', userData.email);"),

    ("// Якщо пароль не введено - сервер згенерує автоматично",
     "// Se palavra-passe não introduzida - servidor gerará automaticamente"),
    ("console.log('🔐 Пароль não especificado - сервер згенерує автоматично');",
     "console.log('🔐 Palavra-passe não especificada - servidor gerará automaticamente');"),
    ("console.log('🔑 Використовується клієнтський пароль:', password);",
     "console.log('🔑 A usar palavra-passe do cliente:', password);"),
    ("throw new Error(error.error || 'Erro criar utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro criação utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro de criar utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro criar utilizadores');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro criação de utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro de criação de utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro criação do utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro ao criar de utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro na criação de utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro ao criar o utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro ao criar novo utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    # actual line in file
    ("throw new Error(error.error || 'Erro criar utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro criação utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro создання користувача');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("throw new Error(error.error || 'Erro criar usuario');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    # Most likely from the file
    ("throw new Error(error.error || 'Erro criar de utilizador');",
     "throw new Error(error.error || 'Erro ao criar utilizador');"),
    ("// Mostrar janela modal з паролем",
     "// Mostrar janela modal com palavra-passe"),
    ("// Сервер згенерував пароль", "// Servidor gerou palavra-passe"),
    ("console.log('🔑 Сервер згенерував пароль:', generatedPassword);",
     "console.log('🔑 Servidor gerou palavra-passe:', generatedPassword);"),
    ("// СПОЧАТКУ закрити форму створення",
     "// PRIMEIRO fechar formulário de criação"),
    ("// Почекати поки закриється, ПОТІМ mostrar пароль",
     "// Aguardar fecho, DEPOIS mostrar palavra-passe"),
    ("$('#userModal').off('hidden.bs.modal'); // Відchaveити обробник",
     "$('#userModal').off('hidden.bs.modal'); // Desactivar handler"),
    ("// Cliente згенерував пароль - також mostrar модальне вікно",
     "// Cliente gerou palavra-passe - também mostrar janela modal"),
    ("console.log('🔑 Показ клієнтського пароля:', passwordToSend);",
     "console.log('🔑 A mostrar palavra-passe do cliente:', passwordToSend);"),
    ("// Якщо не треба показувати пароль - закрити як зазвичай",
     "// Se não é necessário mostrar palavra-passe - fechar normalmente"),
    ("console.log('✏️ Оновлення користувача:', userId);",
     "console.log('✏️ A actualizar utilizador:', userId);"),
    ("throw new Error(error.error || 'Erro atualização utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro de atualização utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro atualizar utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro actualizar utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro ao atualizar utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro actualização utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro na actualização utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro na atualização do utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro ao actualizar o utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("throw new Error(error.error || 'Erro na actualização de utilizador');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    # actual line
    ("throw new Error(error.error || 'Erro oновлення користувача');",
     "throw new Error(error.error || 'Erro ao actualizar utilizador');"),
    ("// Para oновлення - закрити модальне вікно",
     "// Para actualizar - fechar janela modal"),
    ("this.showNotification('Utilizador успішно guardado', 'success');",
     "this.showNotification('Utilizador guardado com sucesso', 'success');"),
    ("console.error('❌ Помилка збереження користувача:', error);",
     "console.error('❌ Erro ao guardar utilizador:', error);"),
    ("this.showNotification(error.message || 'Não вдалося зберегти користувача', 'danger');",
     "this.showNotification(error.message || 'Não foi possível guardar utilizador', 'danger');"),
    ("throw new Error('Utilizador não encontrado');",
     "throw new Error('Utilizador não encontrado');"),
    ("throw new Error('Koristuvach não encontrado');",
     "throw new Error('Utilizador não encontrado');"),
    ("throw new Error('Користувача não encontrado');",
     "throw new Error('Utilizador não encontrado');"),
    ("throw new Error('Erro zміni статусу');",
     "throw new Error('Erro ao alterar estado');"),
    ("throw new Error('Erro mudança estado');",
     "throw new Error('Erro ao alterar estado');"),
    ("throw new Error('Erro de mudança de estado');",
     "throw new Error('Erro ao alterar estado');"),
    ("throw new Error('Erro alterar estado');",
     "throw new Error('Erro ao alterar estado');"),
    # actual line
    ("throw new Error('Erro mudança estado utilizador');",
     "throw new Error('Erro ao alterar estado');"),
    ("this.showNotification(`Estado do utilizador zmíneno na ${this.getStatusLabel(newStatus)}`, 'success');",
     "this.showNotification(`Estado do utilizador alterado para ${this.getStatusLabel(newStatus)}`, 'success');"),
    ("this.showNotification(`Estado do utilizador zmíneno na ${this.getStatusLabel(newStatus)}`",
     "this.showNotification(`Estado do utilizador alterado para ${this.getStatusLabel(newStatus)}`"),
    ("this.showNotification(`Estado do utilizador змінено na ${this.getStatusLabel(newStatus)}`, 'success');",
     "this.showNotification(`Estado do utilizador alterado para ${this.getStatusLabel(newStatus)}`, 'success');"),
    ("console.error('❌ Помилка зміни статусу:', error);",
     "console.error('❌ Erro ao alterar estado:', error);"),
    ("this.showNotification('Não вдалося змінити статус користувача', 'danger');",
     "this.showNotification('Não foi possível alterar o estado do utilizador', 'danger');"),
    ("this.showNotification('Utilizador não encontrado', 'danger');",
     "this.showNotification('Utilizador não encontrado', 'danger');"),
    ("this.showNotification('Koristuvach не encontrado', 'danger');",
     "this.showNotification('Utilizador não encontrado', 'danger');"),
    ("this.showNotification('Користувача не encontrado', 'danger');",
     "this.showNotification('Utilizador não encontrado', 'danger');"),
    ("const confirmMsg = `Tem a certeza que quer ВИДАЛИТИ користувача ${user.firstName} ${user.lastName}?\\n\\nЦю дію НЕ можна скасувати!`;",
     "const confirmMsg = `Tem a certeza que quer ELIMINAR o utilizador ${user.firstName} ${user.lastName}?\\n\\nEsta acção NÃO pode ser desfeita!`;"),
    ("throw new Error('Erro vidaLennia utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro vidaLennia koristuvача');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro eliminar utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro de eliminar utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro na eliminação de utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro eliminação utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro eliminação de utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro de eliminação do utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("throw new Error('Erro eliminação do utilizador');",
     "throw new Error('Erro ao eliminar utilizador');"),
    # actual line:
    ("throw new Error('Erro видалення користувача');",
     "throw new Error('Erro ao eliminar utilizador');"),
    ("this.showNotification('Utilizador uspishno eliminado', 'success');",
     "this.showNotification('Utilizador eliminado com sucesso', 'success');"),
    ("this.showNotification('Utilizador успішно eliminado', 'success');",
     "this.showNotification('Utilizador eliminado com sucesso', 'success');"),
    ("console.error('❌ Помилка видалення:', error);",
     "console.error('❌ Erro ao eliminar:', error);"),
    ("this.showNotification('Não вдалося видалити користувача', 'danger');",
     "this.showNotification('Não foi possível eliminar o utilizador', 'danger');"),
    ("'client': 'Клієнт',", "'client': 'Cliente',"),
    ("// Просте хешування (в реальному додатку використовуйте більш безпечні методи)",
     "// Hash simples (numa aplicação real use métodos mais seguros)"),
    ("// Створення сповіщення у стилі AdminLTE",
     "// Criar notificação no estilo AdminLTE"),
    ("// Criar модальне вікно для показу згенерованого пароля",
     "// Criar janela modal para mostrar palavra-passe gerada"),
    ("// Criar модальне вікно для показу zgenerovanogo пароля",
     "// Criar janela modal para mostrar palavra-passe gerada"),
    ("<i class=\"fas fa-key\"></i> Utilizador criado!",
     "<i class=\"fas fa-key\"></i> Utilizador criado!"),
    ("<strong>ВАЖЛИВО!</strong> Збережіть цей пароль зараз. Ви mais не зможете його побачити.",
     "<strong>IMPORTANTE!</strong> Guarde esta palavra-passe agora. Não poderá vê-la mais tarde."),
    ("<label><i class=\"fas fa-user\"></i> Email користувача:</label>",
     "<label><i class=\"fas fa-user\"></i> Email do utilizador:</label>"),
    ("<label><i class=\"fas fa-lock\"></i> Згенерований пароль:</label>",
     "<label><i class=\"fas fa-lock\"></i> Palavra-passe gerada:</label>"),
    ("<i class=\"fas fa-copy\"></i> Копіювати",
     "<i class=\"fas fa-copy\"></i> Copiar"),
    ("Ви можете надіслати ці дані користувачу автоматично через email, або скопіювати і надіслати вручну.",
     "Pode enviar estes dados ao utilizador automaticamente por email, ou copiar e enviar manualmente."),
    ("<i class=\"fas fa-envelope\"></i> Надіслати на Email",
     "<i class=\"fas fa-envelope\"></i> Enviar por Email"),
    ("<i class=\"fas fa-check\"></i> Зрозуміло", "<i class=\"fas fa-check\"></i> Entendido"),
    ("// Eliminar старе модальне вікно якщо є",
     "// Eliminar janela modal antiga se existir"),
    ("// Adicionar нове", "// Adicionar nova"),
    ("// Обробник копіювання", "// Handler de cópia"),
    ("btn.html('<i class=\"fas fa-check\"></i> Скопійовано!');",
     "btn.html('<i class=\"fas fa-check\"></i> Copiado!');"),
    ("// Обробник надсилання email", "// Handler de envio de email"),
    ("btn.prop('disabled', true).html('<i class=\"fas fa-spinner fa-spin\"></i> Надсилання...');",
     "btn.prop('disabled', true).html('<i class=\"fas fa-spinner fa-spin\"></i> A enviar...');"),
    (".html('<i class=\"fas fa-check-circle\"></i> <strong>Успішно!</strong> Email з інструкціями enviado на ' + email)",
     ".html('<i class=\"fas fa-check-circle\"></i> <strong>Com sucesso!</strong> Email com instruções enviado para ' + email)"),
    (".html('<i class=\"fas fa-exclamation-triangle\"></i> <strong>Помилка!</strong> ' + error.message)",
     ".html('<i class=\"fas fa-exclamation-triangle\"></i> <strong>Erro!</strong> ' + error.message)"),
    ("// Eliminar модальне вікно після закриття",
     "// Eliminar janela modal após fecho"),
    ("// Отримати посилання на додаток (поточний домен)",
     "// Obter link da aplicação (domínio actual)"),
    ("// Dados для email", "// Dados para email"),
    ("subject: 'Ваш доступ до FestLift',",
     "subject: 'O seu acesso ao FestLift',"),
    ("<h1>🔑 Ласкаво просимо до FestLift!</h1>",
     "<h1>🔑 Bem-vindo ao FestLift!</h1>"),
    ("<p>Sistema de gestão ліфтами від FestLift</p>",
     "<p>Sistema de gestão de elevadores da FestLift</p>"),
    ("<h2>Вітаємо!</h2>", "<h2>Bem-vindo!</h2>"),
    ("<p>Для вас criado conta в системі <strong>FestLift</strong>.</p>",
     "<p>Foi criada uma conta para si no sistema <strong>FestLift</strong>.</p>"),
    ("<h3>📧 Ваші дані для входу:</h3>",
     "<h3>📧 Os seus dados de acesso:</h3>"),
    ("<p><strong>Тимчасовий пароль:</strong></p>",
     "<p><strong>Palavra-passe temporária:</strong></p>"),
    ("<strong>⚠️ ВАЖЛИВО:</strong> Після першого входу обов'язково змініть пароль на власний!",
     "<strong>⚠️ IMPORTANTE:</strong> Após o primeiro acesso, altere obrigatoriamente a palavra-passe!"),
    ("<h3>📝 Інструкція для входу:</h3>",
     "<h3>📝 Instruções de acesso:</h3>"),
    ("<li>Перейдіть за посиланням нижче</li>",
     "<li>Aceda ao link abaixo</li>"),
    ("<li>Введіть ваш email: <strong>${email}</strong></li>",
     "<li>Introduza o seu email: <strong>${email}</strong></li>"),
    ("<li>Введіть тимчасовий пароль (скопіюйте вище)</li>",
     "<li>Introduza a palavra-passe temporária (copie acima)</li>"),
    ("<li>Після входу перейдіть в налаштування та змініть пароль</li>",
     "<li>Após o acesso, vá às definições e altere a palavra-passe</li>"),
    ("<a href=\"${appUrl}\" class=\"button\">🚀 Увійти до системи</a>",
     "<a href=\"${appUrl}\" class=\"button\">🚀 Entrar no sistema</a>"),
    ("<p><small>Або скопіюйте посилання: <a href=\"${appUrl}\">${appUrl}</a></small></p>",
     "<p><small>Ou copie o link: <a href=\"${appUrl}\">${appUrl}</a></small></p>"),
    ("<p>&copy; 2024-2026 FestLift Portugal. Внутрішня розробка для клієнтів.</p>",
     "<p>&copy; 2024-2026 FestLift Portugal. Desenvolvimento interno para clientes.</p>"),
    ("// Надіслати через API", "// Enviar via API"),
    ("console.log('📧 Відправка email на:', email);",
     "console.log('📧 A enviar email para:', email);"),
    ("console.log('📡 Статус відповіді:', response.status);",
     "console.log('📡 Estado da resposta:', response.status);"),
    ("// Спробувати прочитати як текст споchatку",
     "// Tentar ler como texto primeiro"),
    ("console.log('📄 Відповідь:', responseText.substring(0, 300));",
     "console.log('📄 Resposta:', responseText.substring(0, 300));"),
    ("let errorMessage = 'Erro надсилання email';",
     "let errorMessage = 'Erro ao enviar email';"),
    ("console.error('Не вдалося розпарсити JSON:', e);",
     "console.error('Não foi possível processar JSON:', e);"),
    ("errorMessage = 'Erro сервера: ' + responseText.substring(0, 100);",
     "errorMessage = 'Erro do servidor: ' + responseText.substring(0, 100);"),
    ("console.log('✅ Email успішно enviado:', result);",
     "console.log('✅ Email enviado com sucesso:', result);"),
    ("// Inicialização менеджера користувачів",
     "// Inicialização do gestor de utilizadores"),

    # ── dispatcher/lifts.html CSS comments ───────────────────────────────────
    ("// Також скасовуємо реєстрацію застарілих SW та оновлюємо",
     "// Também cancelar registo de SW desactualizados e actualizar"),
    ("/* Estilos para ліфтів що очікують видалення */",
     "/* Estilos para elevadores aguardando eliminação */"),
    ("/* Виправлення модальних вікон */", "/* Correcção de janelas modais */"),
    ("/* Прокрутка для modal-body */", "/* Deslocamento para modal-body */"),
    ("/* Estilos para кнопок в футері */",
     "/* Estilos para botões no rodapé */"),
    ("/* Виправлення для input полів */",
     "/* Correcção para campos input */"),
    ("/* Забезпечуємо, що input не блокується overlay'ами */",
     "/* Garantir que input não é bloqueado por overlays */"),
    ("/* Анімація для модального вікна */",
     "/* Animação para janela modal */"),
    ("/* Покращення відображення на мобільних */",
     "/* Melhorias de exibição em dispositivos móveis */"),
    ("/* Estilos para модального вікна */",
     "/* Estilos para janela modal */"),
    ("/* Largura mínima fixa para a tabela ліфтів (специфічна для цієї сторінки) */",
     "/* Largura mínima fixa para a tabela de elevadores (específica desta página) */"),
    ("/* Компактний режим таблиці */", "/* Modo compacto da tabela */"),
    ("/* Ліфти по адресі — alternância de cores по grupoх адреси */",
     "/* Elevadores por morada — alternância de cores por grupo de morada */"),
    ("/* Estilos para QR-кодів */", "/* Estilos para códigos QR */"),
    ("/* Приховуємо дублюючі QR елементи - залишаємо тільки перший */",
     "/* Ocultar elementos QR duplicados - manter apenas o primeiro */"),
    ("/* Поліпшення стилів для всіх input полів в модальному вікні */",
     "/* Melhoria de estilos para todos os campos input na janela modal */"),
    ("/* РАДИКАЛЬНІ стилі для полів інспекції */",
     "/* Estilos RADICAIS para campos de inspecção */"),
    ("/* Блокування стилів що можуть перешкоджати */",
     "/* Bloquear estilos que podem interferir */"),
    ("/* Видалення overlay'ів що блокують */",
     "/* Remover overlays que bloqueiam */"),
    ("/* Покращення відображення модальних вікон один piso іншого */",
     "/* Melhoria de exibição de janelas modais sobrepostas */"),

    # ── lifts.html specific strings ───────────────────────────────────────────
    ("// Якщо aberto з конкретного ліфта, і цей ліфт відсутній у matches — додаємо його окремо",
     "// Se aberto de elevador específico e esse elevador não está nos matches — adicionar separadamente"),
    ("sel.prepend('<option value=\"' + presetId + '\">📍 Поточний: ' + (cl.municipalNumber || presetId) + ' — ' + clAddr + '</option>');",
     "sel.prepend('<option value=\"' + presetId + '\">📍 Actual: ' + (cl.municipalNumber || presetId) + ' — ' + clAddr + '</option>');"),
    ("// Визначаємо який ліфт обрати: преселект > auto-match",
     "// Determinar qual elevador seleccionar: preset > auto-match"),
    ("// Auto-encontrado панель", "// Painel auto-encontrado"),
    ("// Aberto з конкретного ліфта — показуємо dropdown, але обраний він",
     "// Aberto de elevador específico — mostrar dropdown, mas seleccionado este"),
    ("// Немає matches — fallback: весь список ліфтів",
     "// Sem matches — fallback: lista completa de elevadores"),
    ("<strong>Dados витягнуто частково.</strong> Sistema не змогла автоматично розпізнати всі поля. Por favor, перевірте та заповніть поля вручну перед збереженням.",
     "<strong>Dados extraídos parcialmente.</strong> O sistema não conseguiu reconhecer automaticamente todos os campos. Por favor, verifique e preencha os campos manualmente antes de guardar."),
    ("// Отримуємо liftId: з preset (якщо aberto з конкретного ліфта) або з dropdown",
     "// Obter liftId: do preset (se aberto de elevador específico) ou do dropdown"),
    ("// НЕ скидаємо _pdfPresetLiftId тут — він вже встановлений перед show",
     "// NÃO reiniciar _pdfPresetLiftId aqui — já foi definido antes do show"),
    ("porтугальських інспекційних органів.", "portugueses de inspecção."),
    ("<label class=\"font-weight-bold\"><i class=\"fas fa-elevator mr-1\"></i> Ліфт</label>",
     "<label class=\"font-weight-bold\"><i class=\"fas fa-elevator mr-1\"></i> Elevador</label>"),

    # ── qr-scanner.html ───────────────────────────────────────────────────────
    ("<title>Técnico | Sканер QR-кодів</title>",
     "<title>Técnico | Scanner de QR</title>"),
    ("<title>Технік | Сканер QR-кодів</title>",
     "<title>Técnico | Scanner de QR</title>"),
    ("<span class=\"mt-2\">Обробка QR-коду...</span>",
     "<span class=\"mt-2\">A processar código QR...</span>"),
    ("<h1>Сканер QR-кодів</h1>", "<h1>Scanner de QR</h1>"),
    ("<li class=\"breadcrumb-item active\">Сканер QR-кодів</li>",
     "<li class=\"breadcrumb-item active\">Scanner de QR</li>"),
    ("<h3 class=\"card-title\">Сканер QR-кодів</h3>",
     "<h3 class=\"card-title\">Scanner de QR</h3>"),
    ("<!-- Опції камери -->", "<!-- Opções de câmara -->"),
    ("<label for=\"camera-select\">Seleccione камеру:</label>",
     "<label for=\"camera-select\">Seleccione câmara:</label>"),
    ("<option value=\"\">A carregar камер...</option>",
     "<option value=\"\">A carregar câmaras...</option>"),
    ("<i class=\"fas fa-camera\"></i> Запустити камеру",
     "<i class=\"fas fa-camera\"></i> Iniciar câmara"),
    ("<i class=\"fas fa-stop\"></i> Зупинити камеру",
     "<i class=\"fas fa-stop\"></i> Parar câmara"),
    ("<!-- A carregar QR з ficheiroу -->",
     "<!-- A carregar QR de ficheiro -->"),
    ("<label for=\"qr-file\">Або завантажте QR-код з ficheiroу:</label>",
     "<label for=\"qr-file\">Ou carregue o código QR de ficheiro:</label>"),
    ("<!-- Ручне введення -->", "<!-- Introdução manual -->"),
    ("<label for=\"manual-input\">Або введіть дані QR-коду вручну:</label>",
     "<label for=\"manual-input\">Ou introduza os dados do código QR manualmente:</label>"),
    ("placeholder=\"Введіть текст QR-коду...\"",
     "placeholder=\"Introduza o texto do código QR...\""),
    ("<i class=\"fas fa-check\"></i> Обробити",
     "<i class=\"fas fa-check\"></i> Processar"),
    ("<!-- Resultadoи leitura будуть тут -->",
     "<!-- Os resultados de leitura aparecerão aqui -->"),
    ("<i class=\"fas fa-tasks\"></i> Criar tarefas",
     "<i class=\"fas fa-tasks\"></i> Criar tarefas"),
    ("<i class=\"fas fa-tasks\"></i> Criar tarefas\n",
     "<i class=\"fas fa-tasks\"></i> Criar tarefas\n"),
    ("<i class=\"fas fa-file-alt\"></i> Podati zvit",
     "<i class=\"fas fa-file-alt\"></i> Submeter relatório"),
    ("<i class=\"fas fa-file-alt\"></i> Подати звіт",
     "<i class=\"fas fa-file-alt\"></i> Submeter relatório"),
    ("<i class=\"fas fa-qrcode\"></i> Нове leitura",
     "<i class=\"fas fa-qrcode\"></i> Nova leitura"),
    ("<h3 class=\"card-title\">Нещодавні leitura</h3>",
     "<h3 class=\"card-title\">Leituras recentes</h3>"),
    ("<!-- Сюди буде виведена історія leituras -->",
     "<!-- O histórico de leituras será apresentado aqui -->"),
    ("<p class=\"mt-2\">A carregar історії leituras...</p>",
     "<p class=\"mt-2\">A carregar histórico de leituras...</p>"),
    ("<i class=\"fas fa-history\"></i> Повна історія leituras",
     "<i class=\"fas fa-history\"></i> Histórico completo de leituras"),
    ("<h3 class=\"card-title\">Moя статистика</h3>",
     "<h3 class=\"card-title\">A minha estatística</h3>"),
    ("<h3 class=\"card-title\">Моя статистика</h3>",
     "<h3 class=\"card-title\">A minha estatística</h3>"),
    ("<b>Сканувань сьогодні:</b>", "<b>Leituras hoje:</b>"),
    ("<b>Сканувань за semana:</b>", "<b>Leituras esta semana:</b>"),
    ("<b>Tarefas за resultadoами leituras:</b>",
     "<b>Tarefas por resultados de leituras:</b>"),
    ("<b>Manutовано ліфтів через QR:</b>",
     "<b>Elevadores mantidos via QR:</b>"),
    ("// Inicialização bs-custom-file-input (якщо доступний)",
     "// Inicialização bs-custom-file-input (se disponível)"),
    ("// Configurações для користувача", "// Configurações para o utilizador"),
    ("// Якщо не технік, адмін або диспетчер - перенаправляємо",
     "// Se não é técnico, admin ou despachante - redirecionar"),
    ("// Відображення інформації про користувача",
     "// Apresentar informação sobre o utilizador"),
    ("// Змінні для роботи з камерою", "// Variáveis para trabalhar com câmara"),
    ("// A carregar lista камер", "// A carregar lista de câmaras"),
    ("option.textContent = device.label || `Câmera ${devices.indexOf(device) + 1}`;",
     "option.textContent = device.label || `Câmara ${devices.indexOf(device) + 1}`;"),
    ("option.textContent = device.label || `Камера ${devices.indexOf(device) + 1}`;",
     "option.textContent = device.label || `Câmara ${devices.indexOf(device) + 1}`;"),
    ("// За замовчуванням обираємо задню камеру (якщо є)",
     "// Por defeito seleccionar câmara traseira (se existir)"),
    ("'<option value=\"\">Камери не encontrado</option>';",
     "'<option value=\"\">Câmaras não encontradas</option>';"),
    ("console.error('Erro отримання списку камер:', error);",
     "console.error('Erro ao obter lista de câmaras:', error);"),
    ("'<option value=\"\">Erro ao carregar камер</option>';",
     "'<option value=\"\">Erro ao carregar câmaras</option>';"),
    ("title: 'Erro доступу до камери',",
     "title: 'Erro de acesso à câmara',"),
    ("text: 'Não вдалося отримати список доступних камер. Перевірте дозволи камери у вашому браузері.',",
     "text: 'Não foi possível obter a lista de câmaras disponíveis. Verifique as permissões da câmara no seu navegador.',"),
    ("// Функція для запуску камери", "// Função para iniciar câmara"),
    ("title: 'Câmera não vybrana',", "title: 'Câmara não seleccionada',"),
    ("title: 'Câmera не вибрана',", "title: 'Câmara não seleccionada',"),
    ("title: 'Камера не вибрана',", "title: 'Câmara não seleccionada',"),
    ("text: 'Seleccione câmeru zі списку.',",
     "text: 'Seleccione uma câmara da lista.',"),
    ("text: 'Seleccione камеру зі списку.',",
     "text: 'Seleccione uma câmara da lista.',"),
    ("// Конфігурація для сканера", "// Configuração para o leitor"),
    ("console.error('Erro запуску камери:', error);",
     "console.error('Erro ao iniciar câmara:', error);"),
    ("title: 'Erro запуску камери',", "title: 'Erro ao iniciar câmara',"),
    ("text: error.message || 'Não вдалося запустити камеру для leitura.',",
     "text: error.message || 'Não foi possível iniciar a câmara para leitura.',"),
    ("// Функція для зупинки камери", "// Função para parar câmara"),
    ("console.error('Erro зупинки камери:', error);",
     "console.error('Erro ao parar câmara:', error);"),
    ("// Обробник успішного leitura", "// Handler de leitura bem-sucedida"),
    ("// Зупиняємо leitura", "// Parar leitura"),
    ("// Показуємо індикатор завантаження", "// Mostrar indicador de carregamento"),
    ("// Відправляємо дані на сервер", "// Enviar dados ao servidor"),
    ("// Відображаємо resultado", "// Apresentar resultado"),
    ("// Оновлюємо історію leituras", "// Actualizar histórico de leituras"),
    ("console.error('Erro обробки QR-коду:', error);",
     "console.error('Erro ao processar código QR:', error);"),
    ("title: 'Erro обробки QR-коду',", "title: 'Erro ao processar código QR',"),
    ("text: 'Não вдалося обробити відсканований QR-код. Спробуйте ще раз.',",
     "text: 'Não foi possível processar o código QR lido. Tente novamente.',"),
    ("// Ховаємо індикатор завантаження", "// Ocultar indicador de carregamento"),
    ("// Обробник помилок leitura", "// Handler de erros de leitura"),
    ("// Ігноруємо erros leitura (коли QR-код не encontrado)",
     "// Ignorar erros de leitura (quando código QR não encontrado)"),
    ("// Функція для обробки leitura з ficheiroу",
     "// Função para processar leitura de ficheiro"),
    ("// Створюємо novo екземпляр Html5Qrcode для обробки ficheiroу",
     "// Criar nova instância Html5Qrcode para processar ficheiro"),
    ("// Зчитуємо ficheiro як URL", "// Ler ficheiro como URL"),
    ("// Leitura QR-коду з ficheiroу", "// Leitura de código QR de ficheiro"),
    ("console.error('Erro обробки ficheiroу з QR-кодом:', error);",
     "console.error('Erro ao processar ficheiro com código QR:', error);"),
    ("text: 'Não вдалося розпізнати QR-код у завантаженому ficheiroі. Перевірте, що ficheiro містить чіткий QR-код.',",
     "text: 'Não foi possível reconhecer o código QR no ficheiro carregado. Verifique que o ficheiro contém um código QR nítido.',"),
    ("// Скидаємо поле завантаження ficheiroу",
     "// Reiniciar campo de carregamento de ficheiro"),
    ("// Оновлюємо label для bs-custom-file-input",
     "// Actualizar label para bs-custom-file-input"),
    ("// Функція для обробки ручного введення",
     "// Função para processar introdução manual"),
    ("title: 'Порожнє поле',", "title: 'Campo vazio',"),
    ("text: 'Введіть дані QR-коду для обробки.',",
     "text: 'Introduza os dados do código QR para processar.',"),
    ("console.error('Erro обробки введених даних:', error);",
     "console.error('Erro ao processar dados introduzidos:', error);"),
    ("title: 'Erro обробки даних',", "title: 'Erro ao processar dados',"),
    ("text: 'Não вдалося обробити введені дані. Перевірте формат даних і спробуйте ще раз.',",
     "text: 'Não foi possível processar os dados introduzidos. Verifique o formato dos dados e tente novamente.',"),
    ("// Функція для відображення resultadoу leitura",
     "// Função para apresentar resultado de leitura"),
    ("// Створення контейнера для resultadoу",
     "// Criar contentor para resultado"),
    ("// QR-код успішно відсканований і відомий системі",
     "// Código QR lido com sucesso e reconhecido pelo sistema"),
    ("<i class=\"fas fa-check-circle\"></i> QR-код успішно відсканований",
     "<i class=\"fas fa-check-circle\"></i> Código QR lido com sucesso"),
    ("// Відображення resultadoу в залежності від типу QR-коду",
     "// Apresentar resultado conforme tipo de código QR"),
    ("<h5><i class=\"fas fa-building\"></i> Dados про ліфт</h5>",
     "<h5><i class=\"fas fa-building\"></i> Dados do elevador</h5>"),
    ("<th style=\"width: 30%\">ID Ліфта</th>",
     "<th style=\"width: 30%\">ID do Elevador</th>"),
    ("<td>${lift.address || 'Não вказана'}</td>",
     "<td>${lift.address || 'Não indicada'}</td>"),
    ("<td>${lift.model || 'Não вказана'}</td>",
     "<td>${lift.model || 'Não indicado'}</td>"),
    ("<td>${lift.type || 'Não вказаний'}</td>",
     "<td>${lift.type || 'Não indicado'}</td>"),
    ("${lift.status === 'active' ? 'Ativo' : lift.status === 'maintenance' ? 'На обслуговуванні' : 'Несправний'}",
     "${lift.status === 'active' ? 'Activo' : lift.status === 'maintenance' ? 'Em manutenção' : 'Avariado'}"),
    ("<th>Останнє обслуговування</th>",
     "<th>Última manutenção</th>"),
    ("<td>${lift.lastMaintenance ? new Date(lift.lastMaintenance).toLocaleDateString('pt-PT') : 'Не виконувалось'}</td>",
     "<td>${lift.lastMaintenance ? new Date(lift.lastMaintenance).toLocaleDateString('pt-PT') : 'Não realizada'}</td>"),
    ("<th>Наступне обслуговування</th>",
     "<th>Próxima manutenção</th>"),
    ("<td>${lift.nextMaintenance ? new Date(lift.nextMaintenance).toLocaleDateString('pt-PT') : 'Не заплановано'}</td>",
     "<td>${lift.nextMaintenance ? new Date(lift.nextMaintenance).toLocaleDateString('pt-PT') : 'Não planeada'}</td>"),
    ("<h6><i class=\"fas fa-tools\"></i> Швидкі açõ es:</h6>",
     "<h6><i class=\"fas fa-tools\"></i> Acções rápidas:</h6>"),
    ("<h6><i class=\"fas fa-tools\"></i> Швидкі ações:</h6>",
     "<h6><i class=\"fas fa-tools\"></i> Acções rápidas:</h6>"),
    ("<i class=\"fas fa-calendar-check\"></i> Postitи планове обслуговування",
     "<i class=\"fas fa-calendar-check\"></i> Iniciar manutenção planeada"),
    ("<i class=\"fas fa-calendar-check\"></i> Поchatи планове обслуговування",
     "<i class=\"fas fa-calendar-check\"></i> Iniciar manutenção planeada"),
    ("<i class=\"fas fa-wrench\"></i> Зареєструвати ремонт",
     "<i class=\"fas fa-wrench\"></i> Registar reparação"),
    ("<i class=\"fas fa-info-circle\"></i> Детальна інформація про ліфт",
     "<i class=\"fas fa-info-circle\"></i> Informação detalhada do elevador"),
    ("<h5><i class=\"fas fa-clipboard-list\"></i> Dados про заявку</h5>",
     "<h5><i class=\"fas fa-clipboard-list\"></i> Dados do pedido</h5>"),
    ("<th>Опис</th>", "<th>Descrição</th>"),
    ("<td>${request.description || 'Não вказаний'}</td>",
     "<td>${request.description || 'Não indicado'}</td>"),
    ("<td>${request.address || 'Não вказана'}</td>",
     "<td>${request.address || 'Não indicada'}</td>"),
    ("<td>${request.clientName || 'Não вказаний'}</td>",
     "<td>${request.clientName || 'Não indicado'}</td>"),
    ("<i class=\"fas fa-info-circle\"></i> Детальна інформація",
     "<i class=\"fas fa-info-circle\"></i> Informação detalhada"),
    ("<h5><i class=\"fas fa-user-hard-hat\"></i> Dados про техніка</h5>",
     "<h5><i class=\"fas fa-user-hard-hat\"></i> Dados do técnico</h5>"),
    ("<th>Ім'я</th>", "<th>Nome</th>"),
    ("<th>Прізвище</th>", "<th>Apelido</th>"),
    ("<td>${result.data.email || 'Não вказаний'}</td>",
     "<td>${result.data.email || 'Não indicado'}</td>"),
    ("<th>Телефон</th>", "<th>Telefone</th>"),
    ("<td>${result.data.phone || 'Não вказаний'}</td>",
     "<td>${result.data.phone || 'Não indicado'}</td>"),
    ("// Для інших типів QR-кодів виводимо загальну інформацію",
     "// Para outros tipos de códigos QR apresentar informação geral"),
    ("<h5><i class=\"fas fa-qrcode\"></i> Загальні дані QR-коду</h5>",
     "<h5><i class=\"fas fa-qrcode\"></i> Dados gerais do código QR</h5>"),
    ("// Якщо тип не визначений", "// Se o tipo não está definido"),
    ("<h5><i class=\"fas fa-qrcode\"></i> Dados QR-коду</h5>",
     "<h5><i class=\"fas fa-qrcode\"></i> Dados do código QR</h5>"),
    ("// QR-код відсканований, але невідомий системі",
     "// Código QR lido, mas desconhecido pelo sistema"),
    ("<i class=\"fas fa-exclamation-triangle\"></i> ${result.message || 'QR-код невідомий системі'}",
     "<i class=\"fas fa-exclamation-triangle\"></i> ${result.message || 'Código QR desconhecido pelo sistema'}"),
    ("<h5><i class=\"fas fa-question-circle\"></i> Отримані дані</h5>",
     "<h5><i class=\"fas fa-question-circle\"></i> Dados recebidos</h5>"),
    ("<p>QR-код було успішно відскановано, але sistema не змогла розпізнати його вміст.</p>",
     "<p>O código QR foi lido com sucesso, mas o sistema não conseguiu reconhecer o seu conteúdo.</p>"),
    ("<p><strong>Текст QR-коду:</strong></p>",
     "<p><strong>Texto do código QR:</strong></p>"),
    ("// Помилка leitura QR-коду", "// Erro de leitura do código QR"),
    ("<i class=\"fas fa-times-circle\"></i> ${result.message || 'Erro leitura QR-коду'}",
     "<i class=\"fas fa-times-circle\"></i> ${result.message || 'Erro de leitura do código QR'}"),
    ("<p>Під час обробки QR-коду сталася помилка. Спробуйте відdigitalizar код ще раз або перевірте його правильність.</p>",
     "<p>Ocorreu um erro ao processar o código QR. Tente ler novamente ou verifique a validade do código.</p>"),
    ("// Відображаємо resultado", "// Apresentar resultado"),
    ("// Функція для завантаження історії leituras",
     "// Função para carregar histórico de leituras"),
    ("// Отримуємо ID поточного користувача", "// Obter ID do utilizador actual"),
    ("// Отримуємо останні 5 leituras поточного користувача",
     "// Obter as últimas 5 leituras do utilizador actual"),
    ("// Відображаємо історію leituras", "// Apresentar histórico de leituras"),
    ("// Форматування дати і часу", "// Formatar data e hora"),
    ("// Визначення типу QR-коду і його іконки",
     "// Determinar tipo de código QR e seu ícone"),
    ("let typeLabel = 'Загальний';", "let typeLabel = 'Geral';"),
    ("typeLabel = 'Ліфt';", "typeLabel = 'Elevador';"),
    ("typeLabel = 'Ліфт';", "typeLabel = 'Elevador';"),
    ("// Додавання елемента історії", "// Adicionar elemento ao histórico"),
    ("${typeLabel} QR-код", "${typeLabel} código QR"),
    ("${scan.referenceId ? `ID: ${scan.referenceId}` : 'Невідомий QR-код'}",
     "${scan.referenceId ? `ID: ${scan.referenceId}` : 'Código QR desconhecido'}"),
    ("<p><strong>Дата і час:</strong> ${formattedDate}, ${formattedTime}</p>",
     "<p><strong>Data e hora:</strong> ${formattedDate}, ${formattedTime}</p>"),
    ("<p><strong>Тип QR-коду:</strong> ${scan.referenceType || 'Não визначено'}</p>",
     "<p><strong>Tipo de código QR:</strong> ${scan.referenceType || 'Não determinado'}</p>"),
    ("<p><strong>ID instalaçãoа:</strong> ${scan.referenceId || 'Não визначено'}</p>",
     "<p><strong>ID da instalação:</strong> ${scan.referenceId || 'Não determinado'}</p>"),
    ("<p><strong>Dados QR-коду:</strong></p>",
     "<p><strong>Dados do código QR:</strong></p>"),
    ("// Додаємо обробники подій для елементів історії",
     "// Adicionar handlers de eventos para elementos do histórico"),
    ("// Приховуємо всі detalhes leituras",
     "// Ocultar todos os detalhes de leituras"),
    ("// Показуємо/приховуємо detalhes поточного leitura",
     "// Mostrar/ocultar detalhes da leitura actual"),
    ("<p class=\"text-muted\">Histórico de leituras порожня</p>",
     "<p class=\"text-muted\">Histórico de leituras vazio</p>"),
    ("console.error('Erro завантаження історії leituras:', error);",
     "console.error('Erro ao carregar histórico de leituras:', error);"),
    ("<p class=\"text-danger\">Не вдалося descarregar історію leituras</p>",
     "<p class=\"text-danger\">Não foi possível carregar o histórico de leituras</p>"),
    ("// Приховуємо індикатор завантаження", "// Ocultar indicador de carregamento"),
    ("// Функція для завантаження статистики",
     "// Função para carregar estatísticas"),
    ("// Отримуємо сьогоднішню дату", "// Obter data de hoje"),
    ("// Otримуємо дату semana тому", "// Obter data de uma semana atrás"),
    ("// Отримуємо дату semana тому", "// Obter data de uma semana atrás"),
    ("// Отримуємо leitura за сьогодні", "// Obter leituras de hoje"),
    ("// Отримуємо leitura за semana", "// Obter leituras desta semana"),
    ("// Оновлюємо статистику на сторінці", "// Actualizar estatísticas na página"),
    ("// Отримуємо quantidade завдань, створених на основі leituras",
     "// Obter quantidade de tarefas criadas com base em leituras"),
    ("// Це просто заглушка для прикладу", "// É apenas um stub de exemplo"),
    ("// Отримуємо quantidade обслугованих ліфтів через QR",
     "// Obter quantidade de elevadores mantidos via QR"),
    ("console.error('Erro завantaження статистики:', error);",
     "console.error('Erro ao carregar estatísticas:', error);"),
    ("console.error('Erro завантаження статистики:', error);",
     "console.error('Erro ao carregar estatísticas:', error);"),
    ("// Обробники подій", "// Handlers de eventos"),
    ("// Кнопка запуску камери", "// Botão de iniciar câmara"),
    ("// Кнопка зупинки камери", "// Botão de parar câmara"),
    ("// Обробка завантаження ficheiroу", "// Processar carregamento de ficheiro"),
    ("// Обробка ручного введення", "// Processar introdução manual"),
    ("// Кнопка створення tarefas", "// Botão de criar tarefas"),
    ("// Реалізація створення tarefas за resultadoами leitura",
     "// Implementação de criação de tarefas por resultados de leitura"),
    ("title: 'Criação tarefas',", "title: 'Criar tarefas',"),
    ("title: 'Criar tarefas',", "title: 'Criar tarefas',"),
    ("title: 'Criar tarefas'\n", "title: 'Criar tarefas',\n"),
    ("text: 'Funçăo de criar tarefas por resultados de leitura estará disponível na próxima versão.',",
     "text: 'A função de criação de tarefas por resultados de leitura estará disponível na próxima versão.',"),
    ("text: 'Функція створення tarefas за resultadoами leitura буде доступна у наступній версії.',",
     "text: 'A função de criação de tarefas por resultados de leitura estará disponível na próxima versão.',"),
    ("// Кнопка подання звіту", "// Botão de submeter relatório"),
    ("// Реалізація подання звіту за resultadoами leitura",
     "// Implementação de submissão de relatório por resultados de leitura"),
    ("title: 'Submissão zvitu',", "title: 'Submeter relatório',"),
    ("title: 'Submissão звіту',", "title: 'Submeter relatório',"),
    ("title: 'Submeter zvitu',", "title: 'Submeter relatório',"),
    ("title: 'Podati zvit',", "title: 'Submeter relatório',"),
    ("title: 'Подати звіт',", "title: 'Submeter relatório',"),
    ("text: 'Función de podання zvitu za resultadoami leitura estará disponível na próxima versão.',",
     "text: 'A função de submissão de relatório por resultados de leitura estará disponível na próxima versão.',"),
    ("text: 'Функція подання звіту за resultadoами leitura буде доступна у наступній версії.',",
     "text: 'A função de submissão de relatório por resultados de leitura estará disponível na próxima versão.',"),
    ("// Кнопка нового leitura", "// Botão de nova leitura"),
    ("// Приховуємо resultado leitura", "// Ocultar resultado de leitura"),
    ("// Очищаємо поле ручного введення", "// Limpar campo de introdução manual"),
    ("// Кнопка виходу", "// Botão de saída"),
]

# Deduplicate
seen = set()
DEDUP = []
for pair in TRANSLATIONS:
    if pair[0] not in seen and pair[0] != pair[1]:
        seen.add(pair[0])
        DEDUP.append(pair)

def process_file(path):
    txt = path.read_text(encoding='utf-8')
    original = txt
    for old, new in DEDUP:
        if old in txt:
            txt = txt.replace(old, new)
    if txt != original:
        path.write_text(txt, encoding='utf-8')
        return True
    return False

base = __import__('pathlib').Path('/workspaces/deapseak/pages')
for panel in ['admin', 'dispatcher', 'tech']:
    changed = skipped = 0
    for f in sorted((base / panel).glob('*.html')):
        if process_file(f):
            changed += 1
        else:
            skipped += 1
    print(f'{panel}: {changed} files updated, {skipped} unchanged')
print('Done.')
