"""Pass 29: pages/ai-assistant/ai-assistant.html - translate all Ukrainian."""
from pathlib import Path

TRANSLATIONS = [
    ('<html lang="uk">', '<html lang="pt">'),
    ('<title>AI Асистент | LiftMaster Pro</title>',
     '<title>AI Assistente | FestLift</title>'),
    # navbar
    ('<a href="/pages/admin/admin-dashboard.html" class="nav-link">Головна</a>',
     '<a href="/pages/admin/admin-dashboard.html" class="nav-link">Início</a>'),
    ('<a href="/pages/ai-assistant/ai-assistant.html" class="nav-link">AI Асистент</a>',
     '<a href="/pages/ai-assistant/ai-assistant.html" class="nav-link">AI Assistente</a>'),
    ('<i class="fas fa-sign-out-alt"></i> Вихід',
     '<i class="fas fa-sign-out-alt"></i> Sair'),
    # sidebar comments
    ('МІНІМАЛЬНИЙ SIDEBAR ДЛЯ AI АСИСТЕНТА', 'SIDEBAR MÍNIMO PARA O AI ASSISTENTE'),
    ('AI асистент - спільна зона для всіх ролей',
     'AI Assistente - zona comum para todos os papéis'),
    ('Тільки кнопка "Назад" без посилань на панелі',
     'Apenas botão "Voltar" sem ligações ao painel'),
    ('<span class="brand-text font-weight-light">← Назад</span>',
     '<span class="brand-text font-weight-light">← Voltar</span>'),
    ('<span class="d-block text-white">AI Асистент</span>',
     '<span class="d-block text-white">AI Assistente</span>'),
    ('<small class="text-muted">Спільна зона</small>',
     '<small class="text-muted">Zona comum</small>'),
    ('<!-- Назад до панелі -->', '<!-- Voltar ao painel -->'),
    ('<p>Повернутись назад</p>', '<p>Voltar</p>'),
    ('<!-- Поточна сторінка -->', '<!-- Página actual -->'),
    ('<p>AI Асистент</p>', '<p>AI Assistente</p>'),
    ('<li class="nav-header">ФУНКЦІЇ</li>', '<li class="nav-header">FUNÇÕES</li>'),
    ('<!-- Функції AI -->', '<!-- Funções AI -->'),
    ('<p>Чат з AI</p>', '<p>Chat com AI</p>'),
    ('<p>Юридичні питання</p>', '<p>Questões jurídicas</p>'),
    ('<p>Норми PT</p>', '<p>Normas PT</p>'),
    ('<p>Аналіз звіту</p>', '<p>Análise de relatório</p>'),
    ('<li class="nav-header">СИСТЕМА</li>', '<li class="nav-header">SISTEMA</li>'),
    ('<!-- Вийти -->', '<!-- Sair -->'),
    ('<p>Вийти</p>', '<p>Sair</p>'),
    # content header
    ('AI Асистент FestLift', 'AI Assistente FestLift'),
    ('<li class="breadcrumb-item"><a href="javascript:history.back()">Назад</a></li>',
     '<li class="breadcrumb-item"><a href="javascript:history.back()">Voltar</a></li>'),
    ('<li class="breadcrumb-item active">AI Асистент</li>',
     '<li class="breadcrumb-item active">AI Assistente</li>'),
    # tabs
    ('<i class="fas fa-comments"></i> Чат з AI',
     '<i class="fas fa-comments"></i> Chat com AI'),
    ('<i class="fas fa-balance-scale"></i> Юридична консультація',
     '<i class="fas fa-balance-scale"></i> Consulta jurídica'),
    ('<i class="fas fa-book"></i> Норми PT',
     '<i class="fas fa-book"></i> Normas PT'),
    ('<i class="fas fa-clipboard-check"></i> Аналіз звіту',
     '<i class="fas fa-clipboard-check"></i> Análise de relatório'),
    # chat area
    ('<i class="fas fa-magic"></i> Розмова з AI',
     '<i class="fas fa-magic"></i> Conversa com AI'),
    ('<span class="direct-chat-name float-left">AI Асистент</span>',
     '<span class="direct-chat-name float-left">AI Assistente</span>'),
    ('<span class="direct-chat-timestamp float-right">Зараз</span>',
     '<span class="direct-chat-timestamp float-right">Agora</span>'),
    ('<strong>Вітаю! Я AI Асистент FestLift</strong>',
     '<strong>Olá! Sou o AI Assistente FestLift</strong>'),
    ('<p>Можу допомогти з:</p>', '<p>Posso ajudar com:</p>'),
    ('<li>📄 Аналізом звітів інспекції (PDF)</li>',
     '<li>📄 Análise de relatórios de inspecção (PDF)</li>'),
    ('<li>⚖️ Юридичними питаннями</li>',
     '<li>⚖️ Questões jurídicas</li>'),
    ('<li>📋 Нормами та регламентами PT</li>',
     '<li>📋 Normas e regulamentos PT</li>'),
    ('<li>🔧 Técнічними рекомендаціями</li>',
     '<li>🔧 Recomendações técnicas</li>'),
    ('<li>🔧 Технічними рекомендаціями</li>',
     '<li>🔧 Recomendações técnicas</li>'),
    ('<p>Оберіть потрібну функцію в табах вгорі або задайте питання!</p>',
     '<p>Seleccione a função necessária nos separadores acima ou faça uma pergunta!</p>'),
    ('placeholder="Напишіть повідомлення..."',
     'placeholder="Escreva uma mensagem..."'),
    # quick actions
    ('<i class="fas fa-bolt text-warning"></i> Швидкі дії',
     '<i class="fas fa-bolt text-warning"></i> Acções rápidas'),
    ("onclick=\"askQuestion('Які основні вимоги до технічного обслуговування ліфтів?'); return false;\"",
     "onclick=\"askQuestion('Quais são os principais requisitos de manutenção técnica de elevadores?'); return false;\""),
    ('<i class="fas fa-wrench text-info"></i> Вимоги до ТО',
     '<i class="fas fa-wrench text-info"></i> Requisitos de manutenção'),
    ("onclick=\"askQuestion('Які терміни усунення порушень C1, C2, C3?'); return false;\"",
     "onclick=\"askQuestion('Quais são os prazos para corrigir violações C1, C2, C3?'); return false;\""),
    ('<i class="fas fa-clock text-warning"></i> Терміни усунення',
     '<i class="fas fa-clock text-warning"></i> Prazos de correcção'),
    ("onclick=\"askQuestion('Що робити якщо ліфт зупинився між поверхами?'); return false;\"",
     "onclick=\"askQuestion('O que fazer se o elevador parou entre andares?'); return false;\""),
    ('<i class="fas fa-exclamation-triangle text-danger"></i> Аварійна ситуація',
     '<i class="fas fa-exclamation-triangle text-danger"></i> Situação de emergência'),
    ("onclick=\"askQuestion('Які документи потрібні для інспекції ліфта?'); return false;\"",
     "onclick=\"askQuestion('Quais documentos são necessários para a inspecção do elevador?'); return false;\""),
    ('<i class="fas fa-file-alt text-primary"></i> Документи для інспекції',
     '<i class="fas fa-file-alt text-primary"></i> Documentos para inspecção'),
    # legal tab
    ('<h5><i class="icon fas fa-info-circle"></i> Юридична консультація</h5>',
     '<h5><i class="icon fas fa-info-circle"></i> Consulta jurídica</h5>'),
    ('Отримайте професійну юридичну консультацію щодо експлуатації та обслуговування ліфтів в Португалії',
     'Obtenha aconselhamento jurídico profissional sobre a exploração e manutenção de elevadores em Portugal'),
    ('<h3 class="widget-user-username">Відповідальність власника</h3>',
     '<h3 class="widget-user-username">Responsabilidade do proprietário</h3>'),
    ('<h5 class="widget-user-desc">Права та обов\'язки</h5>',
     '<h5 class="widget-user-desc">Direitos e obrigações</h5>'),
    ('<p>Дізнайтесь про юридичну відповідальність власника ліфта, обов\'язкове обслуговування та наслідки порушень</p>',
     '<p>Saiba mais sobre a responsabilidade jurídica do proprietário do elevador, manutenção obrigatória e consequências das infracções</p>'),
    ("onclick=\"askLegal('Яка юридична відповідальність власника ліфта?')\"",
     "onclick=\"askLegal('Qual é a responsabilidade jurídica do proprietário do elevador?')\""),
    ('<i class="fas fa-question-circle"></i> Детальніше',
     '<i class="fas fa-question-circle"></i> Mais detalhes'),
    ('<h3 class="widget-user-username">Санкції та штрафи</h3>',
     '<h3 class="widget-user-username">Sanções e multas</h3>'),
    ('<h5 class="widget-user-desc">Порушення норм безпеки</h5>',
     '<h5 class="widget-user-desc">Violações das normas de segurança</h5>'),
    ('<p>Інформація про штрафи, адміністративні та кримінальні покарання за порушення вимог безпеки</p>',
     '<p>Informação sobre multas, sanções administrativas e penais por violação dos requisitos de segurança</p>'),
    ("onclick=\"askLegal('Які штрафи за порушення норм безпеки ліфтів?')\"",
     "onclick=\"askLegal('Quais são as multas por violação das normas de segurança dos elevadores?')\""),
    ('<i class="fas fa-gavel"></i> Детальніше',
     '<i class="fas fa-gavel"></i> Mais detalhes'),
    ('<i class="fas fa-question"></i> Задати юридичне питання',
     '<i class="fas fa-question"></i> Fazer pergunta jurídica'),
    ('placeholder="Опишіть вашу ситуацію..."',
     'placeholder="Descreva a sua situação..."'),
    ('<i class="fas fa-paper-plane"></i> Отримати консультацію',
     '<i class="fas fa-paper-plane"></i> Obter aconselhamento'),
    ('<!-- Відповідь -->', '<!-- Resposta -->'),
    # regulations tab
    ('<h5><i class="icon fas fa-book"></i> Норми та Регламенти Португалії</h5>',
     '<h5><i class="icon fas fa-book"></i> Normas e Regulamentos de Portugal</h5>'),
    ('База знань португальських норм безпеки для ліфтів',
     'Base de conhecimento das normas de segurança portuguesas para elevadores'),
    ('<i class="fas fa-sync"></i> Перевірити оновлення',
     '<i class="fas fa-sync"></i> Verificar actualizações'),
    ('<!-- Інформація про останню перевірку -->', '<!-- Informação sobre última verificação -->'),
    ('<i class="fas fa-search"></i> Пошук по регламентам',
     '<i class="fas fa-search"></i> Pesquisar regulamentos'),
    ('placeholder="Пошук за ключовими словами (напр. \'ventilação\', \'portas\', \'iluminação\')..."',
     'placeholder="Pesquisar por palavras-chave (ex. \'ventilação\', \'portas\', \'iluminação\')..."'),
    ('<i class="fas fa-search"></i> Шукати',
     '<i class="fas fa-search"></i> Pesquisar'),
    ('<p class="mt-2">Завантаження законів...</p>',
     '<p class="mt-2">A carregar leis...</p>'),
    # analysis tab
    ('<h5><i class="fas fa-clipboard-check"></i> Аналіз звіту інспекції</h5>',
     '<h5><i class="fas fa-clipboard-check"></i> Análise do relatório de inspecção</h5>'),
    ('<p>Завантажте PDF звіт інспекції і отримайте детальний аналіз кожного порушення з поясненнями, законодавчими посиланнями та рекомендаціями щодо усунення</p>',
     '<p>Carregue o relatório PDF de inspecção e obtenha uma análise detalhada de cada violação com explicações, referências legais e recomendações de correcção</p>'),
    ('<i class="fas fa-file-upload"></i> Завантаження звіту',
     '<i class="fas fa-file-upload"></i> Carregar relatório'),
    ('<h5>Перетягніть PDF звіт або клікніть для вибору</h5>',
     '<h5>Arraste o relatório PDF ou clique para seleccionar</h5>'),
    # JS strings
    ("` від ${reg.date}`", "` de ${reg.date}`"),
    ('<h6 class="text-primary"><i class="fas fa-list-ul"></i> Основні пункти:</h6>',
     '<h6 class="text-primary"><i class="fas fa-list-ul"></i> Pontos principais:</h6>'),
    ('`... та ще ${reg.scope.length - 3} пунктів`',
     '`... e mais ${reg.scope.length - 3} pontos`'),
    ('<i class="fas fa-info-circle"></i> Детальніше',
     '<i class="fas fa-info-circle"></i> Mais detalhes'),
    ('<i class="fas fa-scroll"></i> Офіційний текст',
     '<i class="fas fa-scroll"></i> Texto oficial'),
    ("'vigente': { color: 'success', text: 'Діючий' },",
     "'vigente': { color: 'success', text: 'Vigente' },"),
    ("'vigente_obrigatoria': { color: 'danger', text: \"Обов'язковий\" },",
     "'vigente_obrigatoria': { color: 'danger', text: 'Obrigatório' },"),
    ("'vigente_obrigatória': { color: 'danger', text: \"Обов'язковий\" },",
     "'vigente_obrigatória': { color: 'danger', text: 'Obrigatório' },"),
    ("'vigente_obrigatória_condicional': { color: 'warning', text: \"Обов'язковий (умовно)\" },",
     "'vigente_obrigatória_condicional': { color: 'warning', text: 'Obrigatório (condicional)' },"),
    ("'vigente_obrigatória_modernização': { color: 'info', text: 'Модернізація (обов.)' },",
     "'vigente_obrigatória_modernização': { color: 'info', text: 'Modernização (obrig.)' },"),
    ("'vigente_parcial': { color: 'warning', text: 'Частково діючий' },",
     "'vigente_parcial': { color: 'warning', text: 'Parcialmente vigente' },"),
    ("'vigente_opcional': { color: 'secondary', text: 'Необов\\'язковий' },",
     "'vigente_opcional': { color: 'secondary', text: 'Opcional' },"),
    ("'revogado': { color: 'dark', text: 'Скасований' },",
     "'revogado': { color: 'dark', text: 'Revogado' },"),
    ("regulation.status || 'Невідомий'", "regulation.status || 'Desconhecido'"),
    ('<i class="fas fa-arrow-left"></i> Повернутись до списку',
     '<i class="fas fa-arrow-left"></i> Voltar à lista'),
    ('<p><strong>Тип документу:</strong> ${regulation.type.toUpperCase()}</p>',
     '<p><strong>Tipo de documento:</strong> ${regulation.type.toUpperCase()}</p>'),
    ('<p><strong>Статус:</strong>',
     '<p><strong>Estado:</strong>'),
    ('<h6><i class="fas fa-info-circle"></i> Опис</h6>',
     '<h6><i class="fas fa-info-circle"></i> Descrição</h6>'),
    ('<h5 class="text-primary"><i class="fas fa-list"></i> Сфера застосування</h5>',
     '<h5 class="text-primary"><i class="fas fa-list"></i> Âmbito de aplicação</h5>'),
    ('<h5 class="text-primary"><i class="fas fa-clipboard-check"></i> Пункти інспекції (${regulation.inspection_points.length})</h5>',
     '<h5 class="text-primary"><i class="fas fa-clipboard-check"></i> Pontos de inspecção (${regulation.inspection_points.length})</h5>'),
    ('`<strong>Пункт ${idx + 1}</strong>`',
     '`<strong>Ponto ${idx + 1}</strong>`'),
    ('<p><strong>Пояснення для клієнта:</strong><br>',
     '<p><strong>Explicação para o cliente:</strong><br>'),
    ('<p><strong>Опис:</strong><br>',
     '<p><strong>Descrição:</strong><br>'),
    ('<p><strong>Типові порушення:</strong></p>',
     '<p><strong>Violações típicas:</strong></p>'),
    ('<h6><i class="fas fa-exclamation-triangle"></i> Санкції</h6>',
     '<h6><i class="fas fa-exclamation-triangle"></i> Sanções</h6>'),
    ('<h6><i class="fas fa-sticky-note"></i> Примітки</h6>',
     '<h6><i class="fas fa-sticky-note"></i> Notas</h6>'),
    ('<i class="fas fa-external-link-alt"></i> Переглянути офіційний текст',
     '<i class="fas fa-external-link-alt"></i> Ver texto oficial'),
    ("alert('Введіть ключове слово для пошуку');",
     "alert('Introduza uma palavra-chave para pesquisar');"),
    ('<p class="mt-2">Шукаю...</p>',
     '<p class="mt-2">A pesquisar...</p>'),
    ('<i class="fas fa-info-circle"></i> Не знайдено результатів для "${query}"',
     '<i class="fas fa-info-circle"></i> Nenhum resultado encontrado para "${query}"'),
    ('Показати всі закони', 'Mostrar todas as leis'),
    ('<strong>Знайдено: ${data.total}</strong> результатів для "${query}"',
     '<strong>Encontrado: ${data.total}</strong> resultados para "${query}"'),
    ('<i class="fas fa-list"></i> Показати всі',
     '<i class="fas fa-list"></i> Mostrar todos'),
    ("alert('Будь ласка, завантажте PDF файл');",
     "alert('Por favor, carregue um ficheiro PDF');"),
    ("alert('Файл занадто великий! Максимум 10 MB');",
     "alert('Ficheiro demasiado grande! Máximo 10 MB');"),
    ("alert('Завантажте PDF файл або введіть текст звіту');",
     "alert('Carregue um ficheiro PDF ou introduza o texto do relatório');"),
    ('<p class="mt-2">Аналізую звіт...</p>',
     '<p class="mt-2">A analisar relatório...</p>'),
    ("// ✨ Зберігаємо витягнутий текст з PDF", "// ✨ Save extracted PDF text"),
    ("'Не вдалося проаналізувати звіт'", "'Não foi possível analisar o relatório'"),
    ("// Попередження для сканованих документів (OCR)", "// Warning for scanned documents (OCR)"),
    ('<span class="info-box-text">C1 - Критичні</span>',
     '<span class="info-box-text">C1 - Críticas</span>'),
    ('<span class="info-box-text">C2 - Середні</span>',
     '<span class="info-box-text">C2 - Médias</span>'),
    ('<span class="info-box-text">C3 - Легкі</span>',
     '<span class="info-box-text">C3 - Ligeiras</span>'),
    ('<h3 class="card-title"><i class="fas fa-info-circle"></i> Інформація про звіт</h3>',
     '<h3 class="card-title"><i class="fas fa-info-circle"></i> Informação sobre o relatório</h3>'),
    ('`<p><strong>Номер звіту:</strong> ${metadata.reportNumber}</p>`',
     '`<p><strong>Número do relatório:</strong> ${metadata.reportNumber}</p>`'),
    ('`<p><strong>Дата інспекції:</strong> ${metadata.date}</p>`',
     '`<p><strong>Data da inspecção:</strong> ${metadata.date}</p>`'),
    ('`<p><strong>Ліфт №:</strong> ${metadata.liftId}</p>`',
     '`<p><strong>Elevador n.º:</strong> ${metadata.liftId}</p>`'),
    ('`<p><strong>Локація:</strong> ${metadata.location}</p>`',
     '`<p><strong>Localização:</strong> ${metadata.location}</p>`'),
    ('`<p><strong>Інспектор:</strong> ${metadata.inspector}</p>`',
     '`<p><strong>Inspector:</strong> ${metadata.inspector}</p>`'),
    ('<h5><i class="fas fa-list"></i> Виявлені порушення (${result.violations.length})</h5>',
     '<h5><i class="fas fa-list"></i> Violações detectadas (${result.violations.length})</h5>'),
    ('<i class="fas fa-expand"></i> Показати всі деталі',
     '<i class="fas fa-expand"></i> Mostrar todos os detalhes'),
    ('// Форматування відображення артикулу', '// Format article display'),
    ('<strong><i class="fas fa-book"></i> Текст клаузи:</strong>',
     '<strong><i class="fas fa-book"></i> Texto da cláusula:</strong>'),
    ('<p class="mb-2"><strong>Порушення:</strong> ${v.description}</p>',
     '<p class="mb-2"><strong>Violação:</strong> ${v.description}</p>'),
    ('<i class="fas fa-chevron-down"></i> Детальна інформація',
     '<i class="fas fa-chevron-down"></i> Informação detalhada'),
    ('<h6><i class="fas fa-exclamation-triangle"></i> Чому це небезпечно?</h6>',
     '<h6><i class="fas fa-exclamation-triangle"></i> Por que é perigoso?</h6>'),
    ('<i class="fas fa-clock"></i> <strong>Термін усунення:</strong>',
     '<i class="fas fa-clock"></i> <strong>Prazo de correcção:</strong>'),
    ("'Не вказано'", "'Não especificado'"),
    ('<i class="fas fa-balance-scale"></i> <strong>Правові наслідки:</strong>',
     '<i class="fas fa-balance-scale"></i> <strong>Consequências legais:</strong>'),
    ("'Див. законодавство'", "'Ver legislação'"),
    ('<h5><i class="fas fa-check-circle"></i> Вітаємо!</h5>',
     '<h5><i class="fas fa-check-circle"></i> Parabéns!</h5>'),
    ('<p>Порушень не виявлено. Ліфт відповідає всім вимогам безпеки.</p>',
     '<p>Nenhuma violação detectada. O elevador cumpre todos os requisitos de segurança.</p>'),
    ("// ✨ Додаємо секцію з витягнутим текстом PDF", "// ✨ Add section with extracted PDF text"),
    ("'<i class=\"fas fa-compress\"></i> Приховати всі деталі'",
     "'<i class=\"fas fa-compress\"></i> Ocultar todos os detalhes'"),
    ("'<i class=\"fas fa-expand\"></i> Показати всі деталі'",
     "'<i class=\"fas fa-expand\"></i> Mostrar todos os detalhes'"),
    ("// Переконуємося, що auth доступний", "// Ensure auth is available"),
    ("// Додаємо запис в історію браузера для правильної роботи кнопки \"Назад\"",
     "// Add browser history entry for correct Back button behaviour"),
    ("// Це гарантує, що при натисканні \"Назад\" користувач повертається на dashboard",
     "// Ensures that pressing Back returns user to dashboard"),
    ("// Визначаємо dashboard відповідно до ролі користувача",
     "// Determine dashboard based on user role"),
    ("let dashboardUrl = '/pages/admin/admin-dashboard.html'; // За замовчуванням",
     "let dashboardUrl = '/pages/admin/admin-dashboard.html'; // Default"),
    ("// Якщо в історії немає попередньої сторінки, або це була сторінка логіну",
     "// If history has no previous page or it was the login page"),
    ("// додаємо запис про dashboard в історію",
     "// add dashboard entry to history"),
    ("console.log('📌 Dashboard URL для повернення:', dashboardUrl);",
     "console.log('📌 Dashboard URL for return:', dashboardUrl);"),
    ("// Обробник для кнопки \"Назад\"", "// Handler for Back button"),
    ("// Якщо користувач натискає \"Назад\", перенаправляємо на dashboard",
     "// If user presses Back, redirect to dashboard"),
    ("// Перевірка JWT токена при завантаженні", "// JWT token check on load"),
    ("console.warn('⚠️ JWT токен не знайдено');",
     "console.warn('⚠️ JWT token not found');"),
    ("// Не блокуємо сторінку, але попереджаємо", "// Don't block page, but warn"),
    ('<strong>⚠️ Увага!</strong> Ви не авторизовані.',
     '<strong>⚠️ Atenção!</strong> Não está autenticado.'),
    ('<a href="/pages/auth/login.html" class="alert-link">Увійдіть в систему</a>',
     '<a href="/pages/auth/login.html" class="alert-link">Inicie sessão</a>'),
    ('для повного функціоналу.', 'para acesso completo.'),
    ("console.log('✅ JWT токен знайдено');",
     "console.log('✅ JWT token found');"),
    ("// Завантажити інформацію про останню перевірку",
     "// Load last check information"),
    ("// Завантаження голосів для TTS (європейська португальська)",
     "// Load voices for TTS (European Portuguese)"),
    ("// Chrome потребує час для завантаження голосів",
     "// Chrome needs time to load voices"),
    ("// Знайти португальські голоси", "// Find Portuguese voices"),
    ("console.log('🔊 Доступні португальські голоси:', ptVoices.map(v => `${v.name} (${v.lang})`))",
     "console.log('🔊 Available Portuguese voices:', ptVoices.map(v => `${v.name} (${v.lang})`))",),
    ("// Пріоритет: Joana Neural → будь-який pt-PT", "// Priority: Joana Neural → any pt-PT"),
    ("console.log('✅ Знайдено голос pt-PT:', ptPT.name);",
     "console.log('✅ Found pt-PT voice:', ptPT.name);"),
    ("console.warn('⚠️ pt-PT голос не знайдено. Доступні:', ptVoices.map(v => v.lang).join(', '));",
     "console.warn('⚠️ pt-PT voice not found. Available:', ptVoices.map(v => v.lang).join(', '));"),
    ("// Спроба завантажити голоси", "// Try to load voices"),
    ("// Event listener для Chrome", "// Event listener for Chrome"),
    ("// 🔄 ПЕРЕВІРКА ОНОВЛЕНЬ РЕГЛАМЕНТІВ", "// 🔄 REGULATION UPDATE CHECK"),
    ("btn.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i> Перевірка...';",
     "btn.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i> A verificar...';"),
    ("// Показати результати", "// Show results"),
    ('<h5><i class="fas fa-check-circle"></i> Перевірка завершена!</h5>',
     '<h5><i class="fas fa-check-circle"></i> Verificação concluída!</h5>'),
    ('<strong>Перевірено:</strong> ${report.total_checked} регламентів<br>',
     '<strong>Verificados:</strong> ${report.total_checked} regulamentos<br>'),
    ('<strong>Нових знайдено:</strong> ${report.new_regulations}<br>',
     '<strong>Novos encontrados:</strong> ${report.new_regulations}<br>'),
    ('<strong>Оновлено:</strong> ${report.updated_regulations}',
     '<strong>Actualizados:</strong> ${report.updated_regulations}'),
    ("'<p class=\"text-danger\"><strong>⚠️ Знайдено нові регламенти! Перезавантажте сторінку.</strong></p>'",
     "'<p class=\"text-danger\"><strong>⚠️ Novos regulamentos encontrados! Recarregue a página.</strong></p>'"),
    ("// Вставити повідомлення перед результатами", "// Insert message before results"),
    ("// Оновити інформацію про останню перевірку", "// Update last check info"),
    ("// Якщо є нові регламенти - перезавантажити список", "// If new regulations - reload list"),
    ("throw new Error(data.message || 'Помилка перевірки');",
     "throw new Error(data.message || 'Erro de verificação');"),
    ("alert('Помилка при перевірці оновлень: ' + error.message);",
     "alert('Erro ao verificar actualizações: ' + error.message);"),
    ("// Завантажити інформацію про останню перевірку при завантаженні",
     "// Load last check info on page load"),
    ("// ✨ Функції для роботи з витягнутим текстом PDF",
     "// ✨ Functions for working with extracted PDF text"),
    ("alert('Немає тексту для копіювання');",
     "alert('Não há texto para copiar');"),
    ("alert('Не вдалося скопіювати текст автоматично. Виділіть текст у блоці та скопіюйте Ctrl/Cmd+C.');",
     "alert('Não foi possível copiar o texto automaticamente. Seleccione o texto no bloco e copie Ctrl/Cmd+C.');"),
    ("console.error('Помилка копіювання через Clipboard API:', err);",
     "console.error('Copy error via Clipboard API:', err);"),
    ("//  AI ASSISTANT - МІНІМАЛЬНИЙ SIDEBAR (Спільна зона для всіх ролей)",
     "//  AI ASSISTANT - MINIMAL SIDEBAR (Common zone for all roles)"),
    ("// Мінімальний sidebar вже в HTML (рядки 265-352)", "// Minimal sidebar already in HTML (lines 265-352)"),
    ("// Не потрібно динамічно завантажувати - це спільна зона!", "// No need to load dynamically - this is a common zone!"),
    ("console.log('✅ AI Assistant - мінімальний sidebar готовий (спільна зона)');",
     "console.log('✅ AI Assistant - minimal sidebar ready (common zone)');"),
]

TARGET = Path("pages/ai-assistant/ai-assistant.html")

def main():
    if not TARGET.exists():
        print(f"❌ File not found: {TARGET}"); return
    content = TARGET.read_text(encoding="utf-8")
    orig = content; n = 0
    for old, new in TRANSLATIONS:
        if old in content:
            content = content.replace(old, new, 1); n += 1
            print(f"✅ {old[:70]}")
    if content != orig:
        TARGET.write_text(content, encoding="utf-8")
        print(f"\n🎉 Pass 29: {n}/{len(TRANSLATIONS)} replacements in {TARGET}")
    else:
        print(f"⚠️ No changes in {TARGET}")

if __name__ == "__main__":
    main()
