"""Pass 21: unified-analytics.html, users.html, and shared patterns."""
from pathlib import Path

TRANSLATIONS = [
    # ── unified-analytics.html ────────────────────────────────────────────────
    ("<title>Єдина sistema аналітики - FestLift</title>",
     "<title>Sistema unificado de análise - FestLift</title>"),
    ("/* Estilos para звітів */", "/* Estilos para relatórios */"),
    ("/* Timeline стилі */", "/* Estilos da cronologia */"),
    ("<i class=\"fas fa-home\"></i> Головна",
     "<i class=\"fas fa-home\"></i> Início"),
    ("Онлайн аналітика", "Análise em tempo real"),
    ("<h1 class=\"m-0\">📊 Єдина sistema аналітики</h1>",
     "<h1 class=\"m-0\">📊 Sistema unificado de análise</h1>"),
    ("<div class=\"metric-label\">Всього ліфтів</div>",
     "<div class=\"metric-label\">Total de elevadores</div>"),
    ("<div class=\"metric-label\">Потребують ТО</div>",
     "<div class=\"metric-label\">Precisam de manutenção</div>"),
    ("<h6><i class=\"fas fa-exclamation-triangle\"></i> Системні сповіщення</h6>",
     "<h6><i class=\"fas fa-exclamation-triangle\"></i> Alertas do sistema</h6>"),
    ("<!-- Динамічні алерти -->", "<!-- Alertas dinâmicos -->"),
    ("<i class=\"fas fa-tools\"></i> ТО",
     "<i class=\"fas fa-tools\"></i> Manutenção"),
    ("<i class=\"fas fa-money-bill-wave\"></i> Фінанси",
     "<i class=\"fas fa-money-bill-wave\"></i> Finanças"),
    ("<i class=\"fas fa-clipboard-check\"></i> Inspecçõeсції",
     "<i class=\"fas fa-clipboard-check\"></i> Inspecções"),
    ("<i class=\"fas fa-clipboard-check\"></i> Інспекції",
     "<i class=\"fas fa-clipboard-check\"></i> Inspecções"),
    ("<i class=\"fas fa-file-alt\"></i> Звіти",
     "<i class=\"fas fa-file-alt\"></i> Relatórios"),
    ("<i class=\"fas fa-landmark\"></i> Municípioи",
     "<i class=\"fas fa-landmark\"></i> Municípios"),
    ("<h3 class=\"card-title\">📈 Загальна активність системи</h3>",
     "<h3 class=\"card-title\">📈 Actividade geral do sistema</h3>"),
    ("<h3 class=\"card-title\">🏥 Estado системи</h3>",
     "<h3 class=\"card-title\">🏥 Estado do sistema</h3>"),
    ("<strong>Сервер</strong><br>", "<strong>Servidor</strong><br>"),
    ("<small>Онлайн • 99.9% uptime</small>",
     "<small>Online • 99.9% uptime</small>"),
    ("<strong>База даних</strong><br>", "<strong>Base de dados</strong><br>"),
    ("<small>Стабільно • 2ms відповідь</small>",
     "<small>Estável • 2ms de resposta</small>"),
    ("<strong>IoT з'єднання</strong><br>", "<strong>Ligação IoT</strong><br>"),
    ("<small>Стабільно • 95% ліфтів онлайн</small>",
     "<small>Estável • 95% dos elevadores online</small>"),
    ("<h3 class=\"card-title\">🏢 Розподіл ліфтів по статусу</h3>",
     "<h3 class=\"card-title\">🏢 Distribuição de elevadores por estado</h3>"),
    ("<h3 class=\"card-title\">📍 Географічний розподіл</h3>",
     "<h3 class=\"card-title\">📍 Distribuição geográfica</h3>"),
    ("<h3 class=\"card-title\">🔧 Історія технічного обслуговування</h3>",
     "<h3 class=\"card-title\">🔧 Histórico de manutenção</h3>"),
    ("<h3 class=\"card-title\">⏰ Próximos ТО</h3>",
     "<h3 class=\"card-title\">⏰ Próximas manutenções</h3>"),
    ("<!-- Динамічний контент -->", "<!-- Conteúdo dinâmico -->"),
    ("<h3 class=\"card-title\">📱 QR leitura по часу</h3>",
     "<h3 class=\"card-title\">📱 Leituras QR por hora</h3>"),
    ("<h3 class=\"card-title\">👥 Top користувачів QR</h3>",
     "<h3 class=\"card-title\">👥 Top utilizadores QR</h3>"),
    ("<h4><i class=\"fas fa-brain\"></i> AI Previsão та recomendações</h4>",
     "<h4><i class=\"fas fa-brain\"></i> AI Previsão e recomendações</h4>"),
    ("<p>Розумна sistema аналізу даних та машинного навчання</p>",
     "<p>Sistema inteligente de análise de dados e aprendizagem automática</p>"),
    ("<h3 class=\"card-title\">🔮 Прогноз поломок</h3>",
     "<h3 class=\"card-title\">🔮 Previsão de avarias</h3>"),
    ("<!-- Динамічні AI recomendações -->",
     "<!-- Recomendações dinâmicas de AI -->"),
    ("<h3 class=\"card-title\">🔍 Статистика інспекцій</h3>",
     "<h3 class=\"card-title\">🔍 Estatísticas de inspecções</h3>"),
    ("<h3 class=\"card-title\">📋 Resultadoи інспекцій</h3>",
     "<h3 class=\"card-title\">📋 Resultados de inspecções</h3>"),
    ("<h3 class=\"card-title\">👥 Активність користувачів</h3>",
     "<h3 class=\"card-title\">👥 Actividade de utilizadores</h3>"),
    ("<h3 class=\"card-title\">📊 Статистика користувачів</h3>",
     "<h3 class=\"card-title\">📊 Estatísticas de utilizadores</h3>"),
    ("<div class=\"metric-label\">Активні користувачі</div>",
     "<div class=\"metric-label\">Utilizadores activos</div>"),
    ("<div class=\"metric-label\">Техніки</div>",
     "<div class=\"metric-label\">Técnicos</div>"),
    ("<div class=\"metric-label\">Адміністратори</div>",
     "<div class=\"metric-label\">Administradores</div>"),
    ("<h3 class=\"card-title\">📄 Типи звітів</h3>",
     "<h3 class=\"card-title\">📄 Tipos de relatórios</h3>"),
    ("<!-- Календарний період -->", "<!-- Período de calendário -->"),
    ("<h3 class=\"card-title\">📅 Período звіту</h3>",
     "<h3 class=\"card-title\">📅 Período do relatório</h3>"),
    ("<label for=\"startDate\">З дати</label>",
     "<label for=\"startDate\">De data</label>"),
    ("<label for=\"endDate\">До дати</label>",
     "<label for=\"endDate\">Até data</label>"),
    ("<h6>Швидкі періоди:</h6>", "<h6>Períodos rápidos:</h6>"),
    ("<i class=\"fas fa-calendar-day\"></i> Сьогодні",
     "<i class=\"fas fa-calendar-day\"></i> Hoje"),
    ("<i class=\"fas fa-calendar-week\"></i> Цей semana",
     "<i class=\"fas fa-calendar-week\"></i> Esta semana"),
    ("<i class=\"fas fa-calendar-alt\"></i> Цей місяць",
     "<i class=\"fas fa-calendar-alt\"></i> Este mês"),
    ("<i class=\"fas fa-calendar\"></i> Цей квартал",
     "<i class=\"fas fa-calendar\"></i> Este trimestre"),
    ("<i class=\"fas fa-calendar-check\"></i> Цей рік",
     "<i class=\"fas fa-calendar-check\"></i> Este ano"),
    ("<!-- Ações та готові звіти -->", "<!-- Acções e relatórios prontos -->"),
    ("<h3 class=\"card-title\">📊 Готові звіти</h3>",
     "<h3 class=\"card-title\">📊 Relatórios prontos</h3>"),
    ("<th>Nome звіту</th>", "<th>Nome do relatório</th>"),
    ("<th>Período</th>", "<th>Período</th>"),
    ("<h3 class=\"card-title\">🚀 Створити звіт</h3>",
     "<h3 class=\"card-title\">🚀 Criar relatório</h3>"),
    ("<i class=\"fas fa-file-export\"></i> Criar звіт",
     "<i class=\"fas fa-file-export\"></i> Criar relatório"),
    ("<i class=\"fas fa-file-export\"></i> Criar звіт",
     "<i class=\"fas fa-file-export\"></i> Criar relatório"),
    ("<i class=\"fas fa-file-export\"></i> Criar звіт\n",
     "<i class=\"fas fa-file-export\"></i> Criar relatório\n"),
    ("<i class=\"fas fa-calendar-plus\"></i> Запланувати звіт",
     "<i class=\"fas fa-calendar-plus\"></i> Agendar relatório"),
    ("<h6>📈 Статистика звітів:</h6>",
     "<h6>📈 Estatísticas de relatórios:</h6>"),
    ("<span>Згенеровано сьогодні:</span>", "<span>Gerados hoje:</span>"),
    ("<span>Erros генерації:</span>", "<span>Erros de geração:</span>"),
    ("<!-- Estatísticas gerais комунікацій -->",
     "<!-- Estatísticas gerais de comunicações -->"),
    ("<div class=\"metric-label\">Всього municípioів</div>",
     "<div class=\"metric-label\">Total de municípios</div>"),
    ("<div class=\"metric-label\">Очікують mensagem</div>",
     "<div class=\"metric-label\">Aguardam mensagem</div>"),
    ("<div class=\"metric-label\">Ліфтів з Municipality</div>",
     "<div class=\"metric-label\">Elevadores com município</div>"),
    ("<!-- Історія комунікацій -->", "<!-- Histórico de comunicações -->"),
    ("<h3 class=\"card-title\">📧 Історія комунікацій з municípioами</h3>",
     "<h3 class=\"card-title\">📧 Histórico de comunicações com municípios</h3>"),
    ("<th>Тип mensagem</th>", "<th>Tipo de mensagem</th>"),
    ("<th>Дата відправки</th>", "<th>Data de envio</th>"),
    ("<!-- Municípioи за округами -->", "<!-- Municípios por distrito -->"),
    ("<h3 class=\"card-title\">🗺️ Розподіл по районах</h3>",
     "<h3 class=\"card-title\">🗺️ Distribuição por distrito</h3>"),
    ("<h3 class=\"card-title\">📊 Типи повідомлень</h3>",
     "<h3 class=\"card-title\">📊 Tipos de mensagens</h3>"),
    ("<!-- Top municípioів -->", "<!-- Top municípios -->"),
    ("<h3 class=\"card-title\">🏆 Top-10 municípioів за кількістю ліфтів</h3>",
     "<h3 class=\"card-title\">🏆 Top-10 municípios por número de elevadores</h3>"),
    ("<th>Quantidade ліфтів</th>", "<th>Quantidade de elevadores</th>"),
    ("<th>Відстань від центру</th>", "<th>Distância do centro</th>"),
    ("<th>Контакт</th>", "<th>Contacto</th>"),
    ("<!-- Chart.js ЛОКАЛЬНИЙ - не залежить від CDN -->",
     "<!-- Chart.js LOCAL - não depende de CDN -->"),
    ("<!-- Додатковий скрипт для гарантованої активації AI прогнозування -->",
     "<!-- Script adicional para activação garantida de previsão AI -->"),
    ("// Функція для активації AI прогнозування",
     "// Função para activar previsão AI"),
    ("console.log('🤖 Активація AI прогнозування...');",
     "console.log('🤖 A activar previsão AI...');"),
    ("// Деактивуємо всі таби", "// Desactivar todos os separadores"),
    ("// Знаходимо і активуємо AI таб",
     "// Encontrar e activar separador AI"),
    ("console.log('🔍 AI елементи:', { tabButton, tabPane });",
     "console.log('🔍 Elementos AI:', { tabButton, tabPane });"),
    ("// Активуємо кнопку табу", "// Activar botão do separador"),
    ("// Активуємо панель табу", "// Activar painel do separador"),
    ("console.log('✅ AI таб activado');",
     "console.log('✅ Separador AI activado');"),
    ("// Ініціалізуємо AI компоненти", "// Inicializar componentes AI"),
    ("console.log('🚀 Запуск ініціалізації AI компонентів...');",
     "console.log('🚀 A inicializar componentes AI...');"),
    ("console.warn('⚠️ initPredictiveAnalytics не encontrado');",
     "console.warn('⚠️ initPredictiveAnalytics não encontrado');"),
    ("console.error('❌ AI таб елементи не encontrado');",
     "console.error('❌ Elementos do separador AI não encontrados');"),
    ("console.error('❌ Помилка активації AI прогнозування:', error);",
     "console.error('❌ Erro ao activar previsão AI:', error);"),
    ("console.log('🔍 Перевіряємо хеш при завантаженні сторінки...');",
     "console.log('🔍 A verificar hash ao carregar página...');"),
    ("// Функція для mensagem батьківської сторінки про активний пункт меню",
     "// Função para notificar página pai sobre item de menu activo"),
    ("// Зберігаємо стан меню", "// Guardar estado do menu"),
    ("// Якщо це не iframe, можемо безпосередньо оновити меню на цій сторінці",
     "// Se não é iframe, podemos actualizar directamente o menu nesta página"),
    ("console.log(`📋 Atualizado активний пункт меню: ${menuItem}`);",
     "console.log(`📋 Item de menu activo actualizado: ${menuItem}`);"),
    ("console.warn('⚠️ Не вдалося оновити стан меню:', error);",
     "console.warn('⚠️ Não foi possível actualizar estado do menu:', error);"),
    ("// Якщо в URL є хеш predictive-analytics, форсуємо активацію",
     "// Se URL tem hash predictive-analytics, forçar activação"),
    ("console.log('🎯 Encontrado хеш AI прогнозування, форсуємо активацію...');",
     "console.log('🎯 Hash de previsão AI encontrado, a forçar activação...');"),
    ("// Повідомляємо що активний AI прогнозування пункт меню",
     "// Notificar que item de menu AI previsão está activo"),
    ("// Чекаємо поки все завантажиться і активуємо таб",
     "// Aguardar carregamento completo e activar separador"),
    ("console.log('🔍 Перевіряємо наявність функції activateAIPredictive...');",
     "console.log('🔍 A verificar disponibilidade da função activateAIPredictive...');"),
    ("console.log('✅ Функція activateAIPredictive знайдена, викликаємо...');",
     "console.log('✅ Função activateAIPredictive encontrada, a invocar...');"),
    ("console.log(success ? '✅ AI таб activado успішно' : '❌ Не вдалося активувати AI таб');",
     "console.log(success ? '✅ Separador AI activado com sucesso' : '❌ Não foi possível activar separador AI');"),
    ("// Додатково ініціалізуємо AI компоненти",
     "// Inicializar adicionalmente componentes AI"),
    ("console.log('🤖 Ініціалізуємо AI компоненти...');",
     "console.log('🤖 A inicializar componentes AI...');"),
    ("console.warn('⚠️ Функція activateAIPredictive не знайдена, використовуємо fallback...');",
     "console.warn('⚠️ Função activateAIPredictive não encontrada, a usar fallback...');"),
    ("// Fallback - пряма активація", "// Fallback - activação directa"),
    ("console.log('🔄 Використовуємо fallback активацію...');",
     "console.log('🔄 A usar activação fallback...');"),
    ("console.log('Знайдені елементи:', { tabButton, tabPane });",
     "console.log('Elementos encontrados:', { tabButton, tabPane });"),
    ("// Деактивуємо всі таби", "// Desactivar todos os separadores"),
    ("// Активуємо AI таб", "// Activar separador AI"),
    ("console.log('✅ Fallback активація AI таба com sucesso');",
     "console.log('✅ Activação fallback do separador AI com sucesso');"),
    ("console.error('❌ Не вдалося знайти елементи AI таба');",
     "console.error('❌ Não foi possível encontrar elementos do separador AI');"),
    ("}, 2000); // Zmaiorна затримка для надійності",
     "}, 2000); // Atraso maior para fiabilidade"),
    ("}, 2000); // Змaisна затримка для надійності",
     "}, 2000); // Atraso maior para fiabilidade"),
    ("// Якщо немає хешу, то це звичайна аналітика",
     "// Se não há hash, é análise normal"),
    ("// Додаємо обробник для всіх посилань на AI прогнозування",
     "// Adicionar handler para todos os links de previsão AI"),
    ("console.log('🔗 Перехоплено клік по посиланню AI прогнозування');",
     "console.log('🔗 Clique em link de previsão AI interceptado');"),
    ("// Оновлюємо URL", "// Actualizar URL"),
    ("// Повідомляємо про зміну активного пункту меню",
     "// Notificar sobre mudança do item de menu activo"),
    ("// Активуємо таб", "// Activar separador"),
    ("// Слухаємо зміни в хеші для оновлення меню",
     "// Escutar mudanças no hash para actualizar menu"),
    ("// Ініціалізуємо AI систему при завантаженні",
     "// Inicializar sistema AI ao carregar"),
    ("console.log('🤖 Ініціалізуємо Predictive Maintenance System...');",
     "console.log('🤖 A inicializar Predictive Maintenance System...');"),
    ("// Створюємо екземпляр системи прогнозування якщо його немає",
     "// Criar instância do sistema de previsão se não existir"),
    ("// Ініціалізуємо unified analytics engine",
     "// Inicializar motor de análise unificada"),
    ("console.log('✅ Predictive Analytics ініціалізовано');",
     "console.log('✅ Predictive Analytics inicializado');"),
    ("console.warn('⚠️ initPredictiveAnalytics функція не знайдена');",
     "console.warn('⚠️ Função initPredictiveAnalytics não encontrada');"),
    ("// Якщо це AI прогнозування таб - активуємо його",
     "// Se é separador AI previsão - activar"),
    ("console.log('✅ AI прогнозування таб activado');",
     "console.log('✅ Separador AI previsão activado');"),
    ("console.error('❌ Помилка ініціалізації AI системи:', error);",
     "console.error('❌ Erro ao inicializar sistema AI:', error);"),
    ("// A carregar dados при переchaveенні на таб",
     "// Carregar dados ao mudar de separador"),
    ("// A carregar загальної статистики", "// Carregar estatísticas gerais"),
    ("// Отримати всі ліфти", "// Obter todos os elevadores"),
    ("// Отримати всі municípioи", "// Obter todos os municípios"),
    ("// Підрахунок статистики", "// Calcular estatísticas"),
    ("// Оновлення метрик", "// Actualizar métricas"),
    ("document.getElementById('emails-change').textContent = `+${Math.floor(totalEmails * 0.15)} цього місяця`;",
     "document.getElementById('emails-change').textContent = `+${Math.floor(totalEmails * 0.15)} este mês`;"),
    ("document.getElementById('pending-info').textContent = pendingNotifications > 0 ? 'Потребують уваги' : 'Все enviado';",
     "document.getElementById('pending-info').textContent = pendingNotifications > 0 ? 'Necessitam atenção' : 'Tudo enviado';"),
    ("document.getElementById('municipality-coverage').textContent = `${coverage}% покриття`;",
     "document.getElementById('municipality-coverage').textContent = `${coverage}% cobertura`;"),
    ("console.error('❌ Erro ao carregar статистики:', error);",
     "console.error('❌ Erro ao carregar estatísticas:', error);"),
    ("// A carregar історії комунікацій", "// Carregar histórico de comunicações"),
    ("// Filtroуємо ліфти з історією комунікацій",
     "// Filtrar elevadores com histórico de comunicações"),
    ("// Сортуємо по даті (найновіші першими)",
     "// Ordenar por data (mais recentes primeiro)"),
    ("// Відображення таблиці", "// Apresentar tabela"),
    ("<i class=\"fas fa-inbox\"></i> Історія комунікацій порожня",
     "<i class=\"fas fa-inbox\"></i> Histórico de comunicações vazio"),
    ("title=\"Переглянути detalhes\">",
     "title=\"Ver detalhes\">"),
    ("console.error('❌ Erro ao carregar історії:', error);",
     "console.error('❌ Erro ao carregar histórico:', error);"),
    ("<i class=\"fas fa-exclamation-triangle\"></i> Erro ao carregar даних",
     "<i class=\"fas fa-exclamation-triangle\"></i> Erro ao carregar dados"),
    ("// A carregar топ municípioів", "// Carregar top municípios"),
    ("// Otримати всі ліфти та municípioи",
     "// Obter todos os elevadores e municípios"),
    ("// Otримати всі ліфти та municípioи\n",
     "// Obter todos os elevadores e municípios\n"),
    ("// Карта municípioів (актуальні дані з JSON)",
     "// Mapa de municípios (dados actuais do JSON)"),
    ("// Підрахунок ліфтів по municípioам",
     "// Calcular elevadores por município"),
    ("// Сортуємо по кількості ліфтів",
     "// Ordenar por quantidade de elevadores"),
    ("// Відображення таблиці", "// Apresentar tabela"),
    ("console.error('❌ Erro ao carregar топ municípioів:', error);",
     "console.error('❌ Erro ao carregar top municípios:', error);"),
    ("// Створення gráficoів", "// Criar gráficos"),
    ("// Gráfico розподілу по районах", "// Gráfico de distribuição por distrito"),
    ("labels: ['Lisboa', 'Setúbal', 'Santarém', 'Leiria', 'Інші'],",
     "labels: ['Lisboa', 'Setúbal', 'Santarém', 'Leiria', 'Outros'],"),
    ("// Gráfico типів повідомлень", "// Gráfico de tipos de mensagens"),
    ("label: 'Quantidade повідомлень',",
     "label: 'Quantidade de mensagens',"),
    ("alert(`Email Details:\\nMessage ID: ${messageId}\\n\\nФункція в розробці...`);",
     "alert(`Detalhes do email:\\nMessage ID: ${messageId}\\n\\nFunção em desenvolvimento...`);"),
    ("tbody.innerHTML = '<tr><td colspan=\"6\" class=\"text-center text-muted\">Звітів ще немає. Створіть перший звіт.</td></tr>';",
     "tbody.innerHTML = '<tr><td colspan=\"6\" class=\"text-center text-muted\">Ainda sem relatórios. Crie o primeiro relatório.</td></tr>';"),
    ("const typeLabels = { maintenance: 'ТО', financial: 'Фінанси', performance: 'Desempenho', inventory: 'Інвентар' };",
     "const typeLabels = { maintenance: 'Manutenção', financial: 'Finanças', performance: 'Desempenho', inventory: 'Inventário' };"),
    ("<span class=\"badge badge-success\">Готовий</span>' :",
     "<span class=\"badge badge-success\">Pronto</span>' :"),
    ("<span class=\"badge badge-warning\"><i class=\"fas fa-spinner fa-spin\"></i> Генерується</span>' :",
     "<span class=\"badge badge-warning\"><i class=\"fas fa-spinner fa-spin\"></i> A gerar</span>' :"),
    ("<td>${r.title || r.name || 'Звіт'}</td>",
     "<td>${r.title || r.name || 'Relatório'}</td>"),
    ("'<tr><td colspan=\"6\" class=\"text-center text-muted\">Звітів поки немає. Натисніть \"Criar звіт\".</td></tr>';",
     "'<tr><td colspan=\"6\" class=\"text-center text-muted\">Ainda sem relatórios. Clique em \"Criar relatório\".</td></tr>';"),
    ("'<tr><td colspan=\"6\" class=\"text-center text-muted\">Не вдалося descarregar звіти.</td></tr>';",
     "'<tr><td colspan=\"6\" class=\"text-center text-muted\">Não foi possível carregar relatórios.</td></tr>';"),
    ("toastr.warning('Seleccione período звіту');",
     "toastr.warning('Seleccione o período do relatório');"),
    ("genBtn.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i> Генерується...';",
     "genBtn.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i> A gerar...';"),
    ("toastr.success('Звіт успішно criado!');",
     "toastr.success('Relatório criado com sucesso!');"),
    ("toastr.error('Erro: ' + (err.message || 'Не вдалося створити звіт'));",
     "toastr.error('Erro: ' + (err.message || 'Não foi possível criar relatório'));"),
    ("genBtn.innerHTML = '<i class=\"fas fa-file-export\"></i> Criar звіт';",
     "genBtn.innerHTML = '<i class=\"fas fa-file-export\"></i> Criar relatório';"),

    # ── Criar звіт button text (inside anchor) ────────────────────────────────
    (">Criar звіт<", ">Criar relatório<"),

    # ── Outros padrões gerais ─────────────────────────────────────────────────
    ("Створити звіт", "Criar relatório"),
    ("Запланувати звіт", "Agendar relatório"),

    # ── users.html common patterns ────────────────────────────────────────────
    # (will be gathered in later pass)
]

# Deduplicate
seen = set()
DEDUP = []
for pair in TRANSLATIONS:
    if pair[0] not in seen and pair[0] != pair[1]:
        seen.add(pair[0])
        DEDUP.append(pair)

def process_file(path):
    txt = path.read_text(encoding='utf-8')
    original = txt
    for old, new in DEDUP:
        if old in txt:
            txt = txt.replace(old, new)
    if txt != original:
        path.write_text(txt, encoding='utf-8')
        return True
    return False

base = __import__('pathlib').Path('/workspaces/deapseak/pages')
for panel in ['admin', 'dispatcher', 'tech']:
    changed = skipped = 0
    for f in sorted((base / panel).glob('*.html')):
        if process_file(f):
            changed += 1
        else:
            skipped += 1
    print(f'{panel}: {changed} files updated, {skipped} unchanged')
print('Done.')
