"""Fix corrupted plurals and apply remaining translations to all panel files."""
import re
from pathlib import Path

# Fix corrupted strings from broken plural replacements
CORRUPTIONS = [
    # Pattern: Portuguese word + Ukrainian plural suffix
    (re.compile(r'Elevador([іи]в|ів)'), 'Elevadores'),
    (re.compile(r'elevador([іи]в|ів)'), 'elevadores'),
    (re.compile(r'Utilizadores([иів]+)'), 'Utilizadores'),
    (re.compile(r'utilizador([иів]+)'), 'utilizadores'),
    (re.compile(r'Pedido([иів]+)'), 'Pedidos'),
    (re.compile(r'pedido([иів]+)'), 'pedidos'),
    (re.compile(r'relatório([иів]+)'), 'relatórios'),
    (re.compile(r'Relatório([иів]+)'), 'Relatórios'),
    (re.compile(r'registo([иів]+)'), 'registos'),
    (re.compile(r'Registo([иів]+)'), 'Registos'),
    (re.compile(r'Техніко([иів]+)'), 'Técnicos'),
    (re.compile(r'Técnico([иів]+)'), 'Técnicos'),
    (re.compile(r'Assistente IA([аи]+)'), 'Assistente IA'),
    (re.compile(r'Análise([аи]+)'), 'Análise'),
]

# Remaining translations not yet applied
REMAINING = [
    # Corrupted/hybrid phrases
    ('Новий utilizador зареєстрований', 'Novo utilizador registado'),
    ('Pedido на ТО завершена', 'Pedido de manutenção concluído'),
    ('Elevador додано до системи', 'Elevador adicionado ao sistema'),
    ('Додати або редагувати elevadores', 'Adicionar ou editar elevadores'),
    ('Єдина система аналітики та relatórioів', 'Sistema integrado de análise e relatórios'),
    ('Єдина система аналітики та relatórios', 'Sistema integrado de análise e relatórios'),
    ('Створити новий обліковий registo', 'Criar nova conta'),
    ('Tem a certeza, що хочете sair?', 'Tem a certeza que quer sair?'),
    ('Перенаправлення на нову сторінку Assistente IAа', 'A redirecionar para o Assistente IA'),
    # Ukrainian still untranslated in JS/UI
    ('Система', 'Sistema'),
    ('система', 'sistema'),
    ('Підключено', 'Ligado'),
    ('підключено', 'ligado'),
    ('Останнє оновлення', 'Última atualização'),
    ('Зараз', 'Agora'),
    ('Перевірити', 'Verificar'),
    ('перевірити', 'verificar'),
    ('Знайдено', 'Encontrado'),
    ('знайдено', 'encontrado'),
    ('Тиждень', 'Semana'),
    ('тиждень', 'semana'),
    ('Ймовірність поломки', 'Probabilidade de avaria'),
    ('Критичне', 'Crítico'),
    ('критичне', 'crítico'),
    ('потребує негайного огляду', 'requer inspecção imediata'),
    ('Планове ТО', 'Manutenção planeada'),
    ('Підказка', 'Sugestão'),
    ('підказка', 'sugestão'),
    ('Виявлено можливість оптимізації енергоспоживання', 'Identificada oportunidade de otimização energética'),
    ('Перевірка всіх компонентів системи AI прогнозування', 'Verificação de todos os componentes do sistema de IA'),
    ('Тестові дії', 'Ações de teste'),
    ('Тест ініціалізації', 'Teste de inicialização'),
    ('Тест графіка', 'Teste de gráfico'),
    ('Симулювати оригінал', 'Simular original'),
    ('Очистити консоль', 'Limpar consola'),
    ('Тестовий графік', 'Gráfico de teste'),
    ('Консоль виводу', 'Saída da consola'),
    ('Тестові AI рекомендації', 'Recomendações de IA de teste'),
    ('Діагностика AI прогнозування', 'Diagnóstico de previsão IA'),
    ('Повна діагностика AI прогнозування', 'Diagnóstico completo de previsão IA'),
    ('Тестовий прогноз ТО', 'Previsão de manutenção de teste'),
    # More common patterns
    ('Показати', 'Mostrar'),
    ('показати', 'mostrar'),
    ('Приховати', 'Ocultar'),
    ('приховати', 'ocultar'),
    ('через 7 днів', 'em 7 dias'),
    ('Кількість', 'Quantidade'),
    ('кількість', 'quantidade'),
    ('Відмова', 'Falha'),
    ('відмова', 'falha'),
    ('Несправність', 'Avaria'),
    ('несправність', 'avaria'),
    ('Обліковий запис', 'Conta'),
    ('обліковий запис', 'conta'),
    ('Логін та пароль', 'Login e palavra-passe'),
    ('Підтримуються', 'Suportados'),
    ('Тип заявки', 'Tipo de pedido'),
    ('Нова заявка', 'Novo pedido'),
    ('Опис заявки', 'Descrição do pedido'),
    ('Теги', 'Etiquetas'),
    ('теги', 'etiquetas'),
    ('Зображення', 'Imagem'),
    ('зображення', 'imagem'),
    ('Файли', 'Ficheiros'),
    ('файли', 'ficheiros'),
    ('Файл', 'Ficheiro'),
    ('файл', 'ficheiro'),
    ('Рядок', 'Linha'),
    ('рядок', 'linha'),
    ('Колонка', 'Coluna'),
    ('колонка', 'coluna'),
    ('Фільтри', 'Filtros'),
    ('фільтри', 'filtros'),
    ('Група', 'Grupo'),
    ('група', 'grupo'),
    ('Категорія', 'Categoria'),
    ('категорія', 'categoria'),
    ('Підкатегорія', 'Subcategoria'),
    ('Регіон', 'Região'),
    ('регіон', 'região'),
    ('Країна', 'País'),
    ('країна', 'país'),
    ('Мережа', 'Rede'),
    ('мережа', 'rede'),
    ('Версія', 'Versão'),
    ('Платформа', 'Plataforma'),
    ('Відсоток', 'Percentagem'),
    ('відсоток', 'percentagem'),
    ('Швидкість', 'Velocidade'),
    ('швидкість', 'velocidade'),
    ('Власник', 'Proprietário'),
    ('власник', 'proprietário'),
    ('Обслуг', 'Manut'),  # prefix fix for partial words
    ('Поштовий індекс', 'Código postal'),
    ('поштовий індекс', 'código postal'),
    ('Кімната', 'Divisão'),
    ('Під\'їзд', 'Entrada'),
    ('під\'їзд', 'entrada'),
    ('Інсталяція', 'Instalação'),
    ('Сертифікат', 'Certificado'),
    ('Термін дії', 'Validade'),
    ('термін дії', 'validade'),
    ('Інтеграція', 'Integração'),
    ('інтеграція', 'integração'),
    ('Ввімкнено', 'Activado'),
    ('Вимкнено', 'Desactivado'),
    ('Активовано', 'Activado'),
    ('активовано', 'activado'),
    ('Деактивовано', 'Desactivado'),
    ('деактивовано', 'desactivado'),
    ('Дозволено', 'Permitido'),
    ('дозволено', 'permitido'),
    ('Заблоковано', 'Bloqueado'),
    ('заблоковано', 'bloqueado'),
    ('Підтверджено', 'Confirmado'),
    ('підтверджено', 'confirmado'),
    ('Надіслано', 'Enviado'),
    ('надіслано', 'enviado'),
    ('Отримано', 'Recebido'),
    ('отримано', 'recebido'),
    ('Збережено', 'Guardado'),
    ('збережено', 'guardado'),
    ('Видалено', 'Eliminado'),
    ('видалено', 'eliminado'),
    ('Оновлено', 'Atualizado'),
    ('оновлено', 'atualizado'),
    ('Створено', 'Criado'),
    ('створено', 'criado'),
    ('Завершено', 'Concluído'),
    ('завершено', 'concluído'),
    ('Відмінено', 'Cancelado'),
    ('відмінено', 'cancelado'),
    ('Не активний', 'Inactivo'),
    ('Не активна', 'Inactiva'),
    ('Немає підключення', 'Sem ligação'),
    ('немає підключення', 'sem ligação'),
    ('немає даних', 'sem dados'),
    ('Без змін', 'Sem alterações'),
    ('Перевірка', 'Verificação'),
    ('перевірка', 'verificação'),
    # Dispatcher-specific
    ('Карта маршруту', 'Mapa do percurso'),
    ('Детальна карта', 'Mapa detalhado'),
    ('Огляд', 'Revisão'),
    ('Чат', 'Chat'),
    ('чат', 'chat'),
    ('Повідомлення', 'Mensagem'),
    ('повідомлення', 'mensagem'),
    ('Вхідні', 'Entrada'),
    ('Вихідні', 'Enviadas'),
    ('Непрочитані', 'Não lidas'),
    ('Відправник', 'Remetente'),
    ('Отримувач', 'Destinatário'),
    ('Тема', 'Assunto'),
    # Tech panel specific
    ('Мої завдання', 'As minhas tarefas'),
    ('Моя карта', 'O meu mapa'),
    ('Мій маршрут', 'O meu percurso'),
    ('Нові завдання', 'Novas tarefas'),
    ('Завершені завдання', 'Tarefas concluídas'),
    ('Завдання', 'Tarefas'),
    ('завдання', 'tarefas'),
    ('Завдання виконано', 'Tarefa concluída'),
    ('Прийняти завдання', 'Aceitar tarefa'),
    ('Відмовитись від завдання', 'Recusar tarefa'),
    ('Мій профіль', 'O meu perfil'),
    ('Робочий час', 'Horário de trabalho'),
    ('Планування', 'Planeamento'),
    ('Деталі роботи', 'Detalhes do trabalho'),
    ('Матеріали', 'Materiais'),
    ('Запчастини', 'Peças sobresselentes'),
    ('Знаряддя', 'Ferramentas'),
    ('Обладнання', 'Equipamento'),
    ('Результат', 'Resultado'),
    ('результат', 'resultado'),
    ('Рекомендація', 'Recomendação'),
    ('рекомендація', 'recomendação'),
    ('Рекомендації', 'Recomendações'),
    ('рекомендації', 'recomendações'),
    ('Нова рекомендація', 'Nova recomendação'),
    ('Перевірено', 'Verificado'),
    ('перевірено', 'verificado'),
    ('Виявлено', 'Detectado'),
    ('виявлено', 'detectado'),
    ('Замінено', 'Substituído'),
    ('замінено', 'substituído'),
    ('Відремонтовано', 'Reparado'),
    ('відремонтовано', 'reparado'),
    ('Налагоджено', 'Configurado'),
    ('налагоджено', 'configurado'),
    # Admin specific
    ('Карта ліфтів', 'Mapa de elevadores'),
    ('Карта об\'єктів', 'Mapa de instalações'),
    ('Аудит журнал', 'Registo de auditoria'),
    ('Журнал подій', 'Registo de eventos'),
    ('Журнал дій', 'Registo de ações'),
    ('Аудит', 'Auditoria'),
    ('Авторизація', 'Autorização'),
    ('авторизація', 'autorização'),
    ('Автентифікація', 'Autenticação'),
    ('Токен', 'Token'),
    ('Очікує підтвердження', 'A aguardar confirmação'),
    ('Переваги', 'Vantagens'),
    ('Планується', 'Planeado'),
    ('планується', 'planeado'),
    ('Встановлено', 'Instalado'),
    ('встановлено', 'instalado'),
    ('Реєстраційний номер', 'Número de registo'),
    ('Технічний паспорт', 'Manual técnico'),
    ('Паспорт', 'Passaporte'),
    ('Гарантія', 'Garantia'),
    ('гарантія', 'garantia'),
    ('Страхування', 'Seguro'),
    ('страхування', 'seguro'),
    ('Останній ТО', 'Última manutenção'),
    ('Наступний ТО', 'Próxima manutenção'),
    ('Дата ТО', 'Data de manutenção'),
    ('Вартість ТО', 'Custo de manutenção'),
    ('Тривалість', 'Duração'),
    ('тривалість', 'duração'),
    ('Гарантійний термін', 'Período de garantia'),
    ('Інспекційний', 'De inspecção'),
    ('Сертифікаційний', 'De certificação'),
    ('Відповідальний', 'Responsável'),
    ('відповідальний', 'responsável'),
    ('Контрактор', 'Contratante'),
    ('Замовник', 'Cliente'),
    ('замовник', 'cliente'),
    ('Договір', 'Contrato'),
    ('договір', 'contrato'),
    ('Оренда', 'Aluguer'),
    ('оренда', 'aluguer'),
    ('Технічні характеристики', 'Especificações técnicas'),
    ('Характеристики', 'Características'),
    ('характеристики', 'características'),
    ('Вантажопідйомність', 'Capacidade de carga'),
    ('Швидкість підйому', 'Velocidade de elevação'),
    ('Кількість зупинок', 'Número de paragens'),
    ('Тип кабіни', 'Tipo de cabine'),
    ('Ширина дверей', 'Largura das portas'),
    ('Розміри кабіни', 'Dimensões da cabine'),
    # Common remaining patterns
    ('Всього рядків', 'Total de linhas'),
    ('Рядків на сторінці', 'Linhas por página'),
    ('Немає результатів', 'Sem resultados'),
    ('Порядок', 'Ordem'),
    ('порядок', 'ordem'),
    ('Сортувати', 'Ordenar'),
    ('сортувати', 'ordenar'),
    ('Сортування', 'Ordenação'),
    ('Обрано', 'Selecionado'),
    ('обрано', 'selecionado'),
    ('Скасув', 'Cancelar'),
    ('Відміна', 'Cancelamento'),
    ('Надіслати звіт', 'Enviar relatório'),
    ('Попередній перегляд', 'Pré-visualização'),
    ('Друк', 'Impressão'),
    ('Вибрати файл', 'Selecionar ficheiro'),
    ('Перетягніть файл', 'Arraste o ficheiro'),
    ('Підтримувані формати', 'Formatos suportados'),
    ('Максимальний розмір', 'Tamanho máximo'),
    ('Відбудеться', 'Ocorrerá'),
    ('Відбулося', 'Ocorreu'),
    ('Успішна', 'Com sucesso'),
    ('успішна', 'com sucesso'),
    ('Успішний', 'Com sucesso'),
    ('успішний', 'com sucesso'),
    ('Неуспішний', 'Sem sucesso'),
    ('неуспішний', 'sem sucesso'),
    ('Потрібно', 'Necessário'),
    ('потрібно', 'necessário'),
    ('Необхідно', 'Necessário'),
    ('необхідно', 'necessário'),
    ('Авто', 'Auto'),
    ('Ручний', 'Manual'),
    ('ручний', 'manual'),
    ('Автоматичний', 'Automático'),
    ('автоматичний', 'automático'),
    ('Тест', 'Teste'),
    ('тест', 'teste'),
    ('Ключ', 'Chave'),
    ('ключ', 'chave'),
    ('Налагодження', 'Configuração'),
    ('налагодження', 'configuração'),
    ('Скидання', 'Reposição'),
    ('Перезапуск', 'Reiniciar'),
    ('перезапуск', 'reiniciar'),
]

def fix_corruption(txt):
    for pattern, replacement in CORRUPTIONS:
        txt = pattern.sub(replacement, txt)
    return txt

def apply_remaining(txt):
    for old, new in REMAINING:
        if old in txt:
            txt = txt.replace(old, new)
    return txt

def process_file(path):
    txt = path.read_text(encoding='utf-8')
    original = txt
    txt = fix_corruption(txt)
    txt = apply_remaining(txt)
    if txt != original:
        path.write_text(txt, encoding='utf-8')
        return True
    return False

base = Path('/workspaces/deapseak/pages')
for panel in ['admin', 'dispatcher', 'tech']:
    changed = skipped = 0
    for f in sorted((base / panel).glob('*.html')):
        if process_file(f):
            changed += 1
        else:
            skipped += 1
    print(f'{panel}: {changed} files updated, {skipped} unchanged')
print('Done.')
