"""Pass 30: pages/dispatcher/lifts.html - fix lang + critical Ukrainian UI strings."""
from pathlib import Path

TRANSLATIONS = [
    ('<html lang="uk">', '<html lang="pt">'),
    # CSS comments
    ('/* Спеціальні стилі для nested modal windows */',
     '/* Estilos especiais para janelas modais aninhadas */'),
    ('/* Покращення прокручування в nested modal */',
     '/* Melhorar o scroll em modal aninhado */'),
    ('/* Забезпечення правильного відображення на мобільних */',
     '/* Garantir renderização correcta em dispositivos móveis */'),
    ('/* Novos estilos limpos для поля інспектора */',
     '/* Novos estilos limpos para o campo do inspector */'),
    ('/* Estilos para нового динамічно criado textarea коментарів */',
     '/* Estilos para novo textarea de comentários criado dinamicamente */'),
    # UI strings
    ('placeholder="Pesquisar por modelo, endereço, ID..." aria-label="Pesquisar ліфтів"',
     'placeholder="Pesquisar por modelo, endereço, ID..." aria-label="Pesquisar elevadores"'),
    ('<option value="inactive">⛔ Неактивний</option>',
     '<option value="inactive">⛔ Inactivo</option>'),
    ('<p class="text-muted small mb-0"><i class="fas fa-info-circle mr-1"></i>Guarde o elevador para ver e adicionar relatórios інспекцій</p>',
     '<p class="text-muted small mb-0"><i class="fas fa-info-circle mr-1"></i>Guarde o elevador para ver e adicionar relatórios de inspecções</p>'),
    ('<span id="eLiftFooterTabLabel" class="text-muted">Таб: Instalação</span>',
     '<span id="eLiftFooterTabLabel" class="text-muted">Separador: Instalação</span>'),
    ("small.innerHTML = '<i class=\"fas fa-check-circle text-success\"></i> Обов\\'язковий · QR генерується автоматично на сторінці QR-кодів';",
     "small.innerHTML = '<i class=\"fas fa-check-circle text-success\"></i> Obrigatório · QR gerado automaticamente na página de QR-codes';"),
    ("small2.innerHTML = '<i class=\"fas fa-asterisk text-danger\" style=\"font-size:.6rem\"></i> Обов\\'язковий — унікальний ідентифікатор ліфта в камері';",
     "small2.innerHTML = '<i class=\"fas fa-asterisk text-danger\" style=\"font-size:.6rem\"></i> Obrigatório — identificador único do elevador na câmara';"),
    ('<p class="text-muted small">Клієнт повинен знати, що термін інспекції закінчується і що FestLift подбає про це.</p>',
     '<p class="text-muted small">O cliente deve saber que o prazo de inspecção está a terminar e que a FestLift tratará disso.</p>'),
    ('<p class="text-muted small">Офіційний лист з проханням призначити дату інспекції.</p>',
     '<p class="text-muted small">Carta oficial a solicitar a marcação de data de inspecção.</p>'),
    ('<small class="text-muted flex-grow-1"><i class="fas fa-info-circle mr-1"></i>Se o Brevo não estiver configurado — abrirá o seu cliente de email клієнт (mailto)</small>',
     '<small class="text-muted flex-grow-1"><i class="fas fa-info-circle mr-1"></i>Se o Brevo não estiver configurado — abrirá o seu cliente de email (mailto)</small>'),
    ('<i class="fas fa-trash"></i> Eliminar звіт',
     '<i class="fas fa-trash"></i> Eliminar relatório'),
    ('<i class="fas fa-trash mr-1"></i>Видалити',
     '<i class="fas fa-trash mr-1"></i>Eliminar'),
    ('<strong>Informação:</strong> O relatório será enviado automaticamente ao município correspondente com base no endereço do elта.',
     '<strong>Informação:</strong> O relatório será enviado automaticamente ao município correspondente com base no endereço do elevador.'),
    ('placeholder="Adicione informação adicional para municípioу..."',
     'placeholder="Adicione informação adicional para o município..."'),
    ("if (confirm('Видалити цей звіт з архіву назавжди?')) {",
     "if (confirm('Eliminar definitivamente este relatório do arquivo?')) {"),
    ("if (confirm('Widaлити цю інспекцію?')) {",
     "if (confirm('Eliminar esta inspecção?')) {"),
    ("const proceed = confirm(`⚠️ Atenção: Для цього ліфта вже є звіт від ${dateStr} (${Math.ceil(daysAgo)} днів тому).",
     "const proceed = confirm(`⚠️ Atenção: Já existe um relatório para este elevador de ${dateStr} (há ${Math.ceil(daysAgo)} dias)."),
    ("Додати ще один звіт?`);",
     "Adicionar outro relatório?`);"),
    ("alert('❌ Erro: Не вдалося визначити ID ліфта.\\nPor favor, закрийте та відкрийте detalhes ліфта ще раз.');",
     "alert('❌ Erro: Não foi possível determinar o ID do elevador.\\nPor favor, feche e abra novamente os detalhes do elevador.');"),
    ("const _successMsg = 'Звіт інспекції успішно guardado!' + (shouldUpdateMaintenance ? ' Дати ТО atualizado.' : '');",
     "const _successMsg = 'Relatório de inspecção guardado com sucesso!' + (shouldUpdateMaintenance ? ' Datas de manutenção actualizadas.' : '');"),
    ("if (!silent) alert('Адресу не encontrado. Уточніть назву вулиці та номер будинку.');",
     "if (!silent) alert('Endereço não encontrado. Especifique o nome da rua e número.');"),
    ("layer.bindPopup(`<strong>${address}</strong><br><small>Перетягніть маркер для точнішого позиціонування</small>`).openPopup();",
     "layer.bindPopup(`<strong>${address}</strong><br><small>Arraste o marcador para um posicionamento mais preciso</small>`).openPopup();"),
    ("if (!silent) alert('Erro геокодування. Перевірте з\\'єднання.');",
     "if (!silent) alert('Erro de geocodificação. Verifique a ligação.');"),
    ("document.getElementById('filterDescription').textContent = `Ліфти клієнта \"${name}\"`;",
     "document.getElementById('filterDescription').textContent = `Elevadores do cliente \"${name}\"`;"),
    ("textEl.textContent = `За цією адресою вже зареєстровано ${siblings.length} ліфт${siblings.length > 1 ? 'а' : ''} (№ ${nums}). Цей ліфт буде додано до цієї групи.`;",
     "textEl.textContent = `Neste endereço já estão registados ${siblings.length} elevador${siblings.length > 1 ? 'es' : ''} (n.º ${nums}). Este elevador será adicionado a este grupo.`;"),
    ('<p class="mb-0">Ліфти не знайдені</p>',
     '<p class="mb-0">Nenhum elevador encontrado</p>'),
    ('<small>Додайте перший ліфт, натиснувши кнопку &laquo;Adicionar elevador&raquo;</small>',
     '<small>Adicione o primeiro elevador clicando no botão &laquo;Adicionar elevador&raquo;</small>'),
    ("escalator: 'Ескалатор',",
     "escalator: 'Escada rolante',"),
    ("other: 'Інший'",
     "other: 'Outro'"),
    ("'out-of-service': 'Não a funcionar',",
     "'out-of-service': 'Fora de serviço',"),
    ("lift.inspectionFrequency === 24 ? '2 роки' : lift.inspectionFrequency === 12 ? '1 рік' : `${lift.inspectionFrequency} міс.`",
     "lift.inspectionFrequency === 24 ? '2 anos' : lift.inspectionFrequency === 12 ? '1 ano' : `${lift.inspectionFrequency} meses`"),
    ("inspection: 'Inspecção', maintenance: 'Manutenção técnica', repair: 'Reparação', emergency: 'Chamada de emergência', annual: 'Inspекція', routine: 'ТО', certification: 'Сертифікація'",
     "inspection: 'Inspecção', maintenance: 'Manutenção técnica', repair: 'Reparação', emergency: 'Chamada de emergência', annual: 'Inspecção', routine: 'Manutenção', certification: 'Certificação'"),
    ("'<i class=\"fas fa-exclamation-circle mr-1\"></i> <strong>Certificado прострочено!</strong> Necessário негайно convidar інспекцію.'",
     "'<i class=\"fas fa-exclamation-circle mr-1\"></i> <strong>Certificado expirado!</strong> Necessário agendar inspecção imediatamente.'"),
    ("'<i class=\"fas fa-clock mr-1\"></i> До закінчення сертифікату <strong>' + daysToExpiry + ' дн.</strong>",
     "'<i class=\"fas fa-clock mr-1\"></i> Até ao fim do certificado <strong>' + daysToExpiry + ' dias</strong>"),
    ("Час convidar інспекцію.'",
     "Hora de agendar inspecção.'"),
    ("'<i class=\"fas fa-info-circle mr-1\"></i> Дата сертифікату não especificado. Запросіть інспекцію вручну.'",
     "'<i class=\"fas fa-info-circle mr-1\"></i> Data do certificado não especificada. Solicite a inspecção manualmente.'"),
    ("munInput.title = 'Número municipal não можна змінити після реєстрації ліфта';",
     "munInput.title = 'O número municipal não pode ser alterado após o registo do elevador';"),
    ("'<strong>Контракт завантажено</strong> №${contract.contractNumber || '—'}'",
     "'<strong>Contrato carregado</strong> n.º ${contract.contractNumber || '—'}'"),
    ("banner.innerHTML = `<div class=\"alert alert-warning py-2 mb-0\"><i class=\"fas fa-exclamation-triangle\"></i> Ficheiro контракту не завантажено</div>`;",
     "banner.innerHTML = `<div class=\"alert alert-warning py-2 mb-0\"><i class=\"fas fa-exclamation-triangle\"></i> Ficheiro do contrato não carregado</div>`;"),
    ("if (banner) banner.innerHTML = `<div class=\"alert alert-light py-2 mb-0 text-muted\"><i class=\"fas fa-info-circle\"></i> Контракт ще не завантажено</div>`;",
     "if (banner) banner.innerHTML = `<div class=\"alert alert-light py-2 mb-0 text-muted\"><i class=\"fas fa-info-circle\"></i> Contrato ainda não carregado</div>`;"),
    ("if (!confirm('Ви хочете відправити запит на видалення цього ліфта? Адміністратор повинен confirmar.')) {",
     "if (!confirm('Pretende enviar um pedido de eliminação deste elevador? O administrador terá de confirmar.')) {"),
    ("alert('✅ Запит на видалення enviado! Адміністратор отримав сповіщення.');",
     "alert('✅ Pedido de eliminação enviado! O administrador recebeu a notificação.');"),
    ("liftCard.innerHTML += '<span class=\"badge badge-warning\">Очікує видалення</span>';",
     "liftCard.innerHTML += '<span class=\"badge badge-warning\">Aguarda eliminação</span>';"),
    ("alert('❌ Помилка відправки запиту: ' + (result.message || 'Спробуйте пізніше'));",
     "alert('❌ Erro ao enviar pedido: ' + (result.message || 'Tente mais tarde'));"),
    ("alert('❌ Не вдалося відправити запит на видалення');",
     "alert('❌ Não foi possível enviar o pedido de eliminação');"),
    ("inspection: 'інспекція', maintenance: 'то', repair: 'ремонт', emergency: 'аварія'",
     "inspection: 'inspecção', maintenance: 'manutenção', repair: 'reparação', emergency: 'emergência'"),
    ("inspection: 'Inspecção', maintenance: 'IT', repair: 'Reparação', emergency: 'Аварійний', annual: 'Inspекція', routine: 'ТО', certification: 'Сертифікація', technical: 'Технічна', safety: 'Verificação de segurança'",
     "inspection: 'Inspecção', maintenance: 'Manutenção', repair: 'Reparação', emergency: 'Emergência', annual: 'Inspecção', routine: 'Manutenção', certification: 'Certificação', technical: 'Técnico', safety: 'Verificação de segurança'"),
    ("${fileUrl ? '<i class=\"fas fa-paperclip text-success ml-1\" title=\"PDF прикріплено\"></i>' : ''}",
     "${fileUrl ? '<i class=\"fas fa-paperclip text-success ml-1\" title=\"PDF anexado\"></i>' : ''}"),
    ('<p class="mb-0"><small><strong>Dата:</strong>',
     '<p class="mb-0"><small><strong>Data:</strong>'),
    ('<p class="mb-0"><small><strong>Дата:</strong>',
     '<p class="mb-0"><small><strong>Data:</strong>'),
    ('title="Видалити звіт"',
     'title="Eliminar relatório"'),
    ("if (!confirm('Видалити цей звіт назавжди?')) return;",
     "if (!confirm('Eliminar definitivamente este relatório?')) return;"),
    ("if (!liftId) return alert('Не вдалося визначити ID ліфта');",
     "if (!liftId) return alert('Não foi possível determinar o ID do elevador');"),
    ("alert('Erro: ' + (result.message || 'Не вдалося видалити'));",
     "alert('Erro: ' + (result.message || 'Não foi possível eliminar'));"),
    ("alert('Erro видалення: ' + e.message);",
     "alert('Erro ao eliminar: ' + e.message);"),
    ("alert('Erro надсилання звіту: ' + e.message);",
     "alert('Erro ao enviar relatório: ' + e.message);"),
    ("if (reportIndex === null || reportIndex === undefined) { alert('Індекс звіту не визначено'); return; }",
     "if (reportIndex === null || reportIndex === undefined) { alert('Índice do relatório não definido'); return; }"),
    ("if (!liftId) return alert('Не вдалося визначити ID ліфта');",
     "if (!liftId) return alert('Não foi possível determinar o ID do elevador');"),
    ("alert('PDF успішно прикріплено!');",
     "alert('PDF anexado com sucesso!');"),
    ("alert('Erro: ' + (result.message || 'Не вдалося прикріпити PDF'));",
     "alert('Erro: ' + (result.message || 'Não foi possível anexar o PDF'));"),
    ("alert('Erro: ' + (result.message || result.error || 'Не вдалося додати звіт'));",
     "alert('Erro: ' + (result.message || result.error || 'Não foi possível adicionar o relatório'));"),
    ('<div class="col-6"><strong><i class="fas fa-calendar text-muted"></i> Дата:</strong><br>${date}</div>',
     '<div class="col-6"><strong><i class="fas fa-calendar text-muted"></i> Data:</strong><br>${date}</div>'),
    ("Contrato №<strong>${liftCn}</strong> (PDF não завантажено)",
     "Contrato n.º<strong>${liftCn}</strong> (PDF não carregado)"),
    ('<strong>Período ações:</strong>',
     '<strong>Período de acções:</strong>'),
    ("`Контракт успішно завантажено та застосовано до ${sharedCount + 1} elevadores neste endereço!`",
     "`Contrato carregado com sucesso e aplicado a ${sharedCount + 1} elevadores neste endereço!`"),
    ("alert('Exportar PDF буде доступний у наступній версії.\\n\\nНаразі використайте експорт CSV.');",
     "alert('Exportar PDF estará disponível na próxima versão.\\n\\nPor enquanto use a exportação CSV.');"),
    ("throw new Error(`Не вдалося descarregar modelo: ${response.statusText}`);",
     "throw new Error(`Não foi possível descarregar o modelo: ${response.statusText}`);"),
    ("'<div class=\"alert alert-warning mt-3\"><i class=\"fas fa-clock mr-2\"></i><strong>Atenção!</strong> Reinspecção necessária em 30 днів</div>'",
     "'<div class=\"alert alert-warning mt-3\"><i class=\"fas fa-clock mr-2\"></i><strong>Atenção!</strong> Reinspecção necessária em 30 dias</div>'"),
    # Bootstrap comment
    ('/* Bootstrap backdrop не потрібен — оверлей на батьківській сторінці */',
     '/* Bootstrap backdrop not needed — overlay on parent page */'),
    ('/* Модалка: займає весь простір iframe-документа */',
     '/* Modal: occupies full space of iframe document */'),
]

TARGET = Path("pages/dispatcher/lifts.html")

def main():
    if not TARGET.exists():
        print(f"❌ File not found: {TARGET}"); return
    content = TARGET.read_text(encoding="utf-8")
    orig = content; n = 0
    skipped = []
    for old, new in TRANSLATIONS:
        if old in content:
            content = content.replace(old, new, 1); n += 1
            print(f"✅ {old[:70]}")
        else:
            skipped.append(old[:70])
    if content != orig:
        TARGET.write_text(content, encoding="utf-8")
        print(f"\n🎉 Pass 30: {n}/{len(TRANSLATIONS)} replacements in {TARGET}")
    else:
        print(f"⚠️ No changes in {TARGET}")
    if skipped:
        print("\n⚠️ NOT FOUND:")
        for s in skipped:
            print(f"   {s}")

if __name__ == "__main__":
    main()
