"""Pass 4: comprehensive safe string-replacement translation (no regex)."""
from pathlib import Path

TRANSLATIONS = [
    # ── Page titles ────────────────────────────────────────────────────────────
    ('Адмін панель - Управління ліфтами', 'Painel Admin - Gestão de Elevadores'),
    ('Адмін панель - Аналітика', 'Painel Admin - Análise'),
    ('Адмін панель - Заявки', 'Painel Admin - Pedidos'),
    ('Адмін панель - Користувачі', 'Painel Admin - Utilizadores'),
    ('Адмін панель - Документи', 'Painel Admin - Documentos'),
    ('Адмін панель - Інспекції', 'Painel Admin - Inspecções'),
    ('Адмін панель - Налаштування', 'Painel Admin - Definições'),
    ('Адмін панель - Звіти', 'Painel Admin - Relatórios'),
    ('Адмін панель - Дашборд', 'Painel Admin - Dashboard'),
    ('Адмін панель - Кошторис', 'Painel Admin - Orçamento'),
    ('Адмін панель - QR', 'Painel Admin - QR'),
    ('Адмін панель -', 'Painel Admin -'),

    # ── Sidebar nav ────────────────────────────────────────────────────────────
    ('<p>Дашборд</p>', '<p>Dashboard</p>'),
    ('<p>Управління QR</p>', '<p>Gestão de QR</p>'),
    ('<p>Аналітика QR</p>', '<p>Análise QR</p>'),
    ('<p>Історія сканувань</p>', '<p>Histórico de leituras</p>'),
    ('<p>Ліфти<i class="right fas fa-angle-left"></i></p>', '<p>Elevadores<i class="right fas fa-angle-left"></i></p>'),
    ('<p>Управління ліфтами</p>', '<p>Gestão de elevadores</p>'),
    ('<p>Заявки</p>', '<p>Pedidos</p>'),
    ('<p>Мапа ліфтів</p>', '<p>Mapa de elevadores</p>'),
    ('<p>Користувачі</p>', '<p>Utilizadores</p>'),
    ('<p>Документи<i class="right fas fa-angle-left"></i></p>', '<p>Documentos<i class="right fas fa-angle-left"></i></p>'),
    ('<p>Кошторис (Створити)</p>', '<p>Orçamento (Criar)</p>'),
    ('<p>Кошторис (Список)</p>', '<p>Orçamento (Lista)</p>'),
    ('<p>Інспекції</p>', '<p>Inspecções</p>'),
    ('<p>Аналітика<i class="right fas fa-angle-left"></i></p>', '<p>Análise<i class="right fas fa-angle-left"></i></p>'),
    ('<p>Зведена аналітика</p>', '<p>Análise global</p>'),
    ('<p>AI Прогнозування</p>', '<p>AI Previsão</p>'),
    ('<p>Звіти</p>', '<p>Relatórios</p>'),
    ('<p>AI Асистент</p>', '<p>AI Assistente</p>'),
    ('<p>Підтримка<i class="right fas fa-angle-left"></i></p>', '<p>Suporte<i class="right fas fa-angle-left"></i></p>'),
    ('<p>Технічна підтримка</p>', '<p>Suporte técnico</p>'),
    ('<p>Сповіщення</p>', '<p>Notificações</p>'),
    ('<p>Налаштування</p>', '<p>Definições</p>'),
    ('<p>Профіль</p>', '<p>Perfil</p>'),
    ('<p>Вийти</p>', '<p>Sair</p>'),
    ('<p>Завдання</p>', '<p>Tarefas</p>'),
    ('<p>Мапи</p>', '<p>Mapas</p>'),
    ('<p>Мапи клієнтів</p>', '<p>Mapas de clientes</p>'),
    ('<p>Карта завдань</p>', '<p>Mapa de tarefas</p>'),
    ('<p>Картка ліфта</p>', '<p>Ficha do elevador</p>'),
    ('<p>Інструменти</p>', '<p>Ferramentas</p>'),
    ('<p>База знань</p>', '<p>Base de conhecimento</p>'),
    ('<p>Відео</p>', '<p>Vídeos</p>'),
    ('<p>Мої завдання</p>', '<p>As minhas tarefas</p>'),
    ('<p>Всі завдання</p>', '<p>Todas as tarefas</p>'),
    ('<p>Карта</p>', '<p>Mapa</p>'),
    ('<p>Клієнти</p>', '<p>Clientes</p>'),
    ('<p>Ліфти</p>', '<p>Elevadores</p>'),

    # ── Sidebar user role labels ────────────────────────────────────────────────
    ('>Адміністратор<', '>Administrador<'),
    ('>Диспетчер<', '>Despachante<'),
    ('>Технік<', '>Técnico<'),

    # ── Page headings / breadcrumbs ────────────────────────────────────────────
    ('>Управління ліфтами<', '>Gestão de elevadores<'),
    ('>Управління заявками<', '>Gestão de pedidos<'),
    ('>Управління користувачами<', '>Gestão de utilizadores<'),
    ('>Управління інспекціями<', '>Gestão de inspecções<'),
    ('>Управління документами<', '>Gestão de documentos<'),
    ('>Управління кошторисами<', '>Gestão de orçamentos<'),
    ('>Управління QR-кодами<', '>Gestão de códigos QR<'),
    ('>Аналітика та звіти<', '>Análise e relatórios<'),
    ('>Налаштування системи<', '>Definições do sistema<'),
    ('>Головна<', '>Início<'),
    ('href="admin-dashboard.html">Головна', 'href="admin-dashboard.html">Início'),
    ('href="dashboard.html">Головна', 'href="dashboard.html">Início'),
    ('href="../admin/admin-dashboard.html">Головна', 'href="../admin/admin-dashboard.html">Início'),

    # ── Filter / stats bar ─────────────────────────────────────────────────────
    ('Активний фільтр:', 'Filtro activo:'),
    ('Фільтр:', 'Filtro:'),
    ('Загальна quantidade ліфтів', 'Total de elevadores'),
    ('Активних ліфтів', 'Elevadores activos'),
    ('Inactivos ліфтів', 'Elevadores inactivos'),
    ('Список ліфтів <span', 'Lista de elevadores <span'),
    ('Список ліфтів', 'Lista de elevadores'),
    ('Adicionar ліфт', 'Adicionar elevador'),
    ('Adicionar novo ліфт', 'Adicionar novo elevador'),
    ('Filtro по статусу', 'Filtro por estado'),
    ('Filtro по типу', 'Filtro por tipo'),
    ('Всі статуси', 'Todos os estados'),
    ('Всі типи', 'Todos os tipos'),
    ('Manutовування', 'Manutenção'),

    # ── Table headers ──────────────────────────────────────────────────────────
    ('<th>Модель</th>', '<th>Modelo</th>'),
    ('<th>Тип</th>', '<th>Tipo</th>'),
    ('<th>Локація</th>', '<th>Localização</th>'),
    ('<th>Клієнт</th>', '<th>Cliente</th>'),
    ('<th>Статус</th>', '<th>Estado</th>'),
    ('Показано', 'A mostrar'),
    (' з <span id="totalCount">', ' de <span id="totalCount">'),
    (' з <span id="total">', ' de <span id="total">'),
    ('записів', 'registos'),
    ('записи', 'registos'),
    ('запис', 'registo'),

    # ── JS tab label array ─────────────────────────────────────────────────────
    ('var eLiftTabLabels = ["Instalação","Клієнт","Ліфт","Serviço"];',
     'var eLiftTabLabels = ["Instalação","Cliente","Elevador","Serviço"];'),
    ("var eLiftTabLabels = ['Instalação','Клієнт','Ліфт','Serviço'];",
     "var eLiftTabLabels = ['Instalação','Cliente','Elevador','Serviço'];"),
    ("'Таб: '", "'Separador: '"),
    ('"Таб: "', '"Separador: "'),

    # ── Object tab ─────────────────────────────────────────────────────────────
    ('К-ть ліфтів у будівлі', 'Nº de elevadores no edifício'),
    ('<span class="input-group-text">шт</span>', '<span class="input-group-text">un.</span>'),
    ('Скільки ліфтів у будівлі', 'Quantos elevadores no edifício'),
    ('Поки — introdução manual. Пізніше буде автоматично підтягуватись за адресою.',
     'Por enquanto — introdução manual. Será preenchido automaticamente pelo endereço.'),
    ("É utilizado para звіту про в'їзд / виїзд ліфта з обслуговування",
     "É utilizado para o relatório de entrada / saída do elevador da manutenção"),
    ('Динамічні рядки муніципальних номерів', 'Linhas dinâmicas de números municipais'),
    ('Прихований контейнер сумісності для існуючого JS', 'Contentor oculto de compatibilidade para JS existente'),
    # Address section
    ('Адреса та доступ', 'Endereço e acesso'),
    ('Повна адреса', 'Endereço completo'),
    ('Моя локація', 'A minha localização'),
    ('Інфо про ліфти за цією адресою', 'Info sobre elevadores neste endereço'),
    ('Увага:', 'Atenção:'),
    # Coordinates
    ('<!-- Координати -->', '<!-- Coordenadas -->'),
    ('Широта', 'Latitude'),
    ('Довгота', 'Longitude'),
    ('Визначається автоматично...', 'Determinado automaticamente...'),
    ('Копіювати координати', 'Copiar coordenadas'),
    # Map
    ('Інтерактивна карта', 'Mapa interactivo'),
    ('Клікніть щоб встановити розташування', 'Clique para definir a localização'),

    # ── Client tab ─────────────────────────────────────────────────────────────
    ('Контактні дані клієнта', 'Dados de contacto do cliente'),
    ("Ім'я / Назва організації", 'Nome / Nome da organização'),
    ("(необов'язково)", '(opcional)'),
    ("необов'язково", 'opcional'),
    ("Ім'я клієнта або назва ОСББ", 'Nome do cliente ou nome do condomínio'),
    ('Для групування всіх ліфтів клієнта', 'Para agrupar todos os elevadores do cliente'),
    ('Responsável менеджер / адміністратор', 'Responsável / administrador'),
    ('Надіслати клієнту email з кодом доступу', 'Enviar email ao cliente com código de acesso'),
    ('Тільки якщо для цього email ще не існує облікового запису',
     'Apenas se ainda não existe conta para este email'),
    ('Контактна особа', 'Pessoa de contacto'),

    # ── Contract tab ───────────────────────────────────────────────────────────
    ('Contrato / Контракт', 'Contrato'),
    ('Тип договору', 'Tipo de contrato'),
    ('— Оберіть —', '— Seleccione —'),
    ('Повне обслуговування', 'Manutenção completa'),
    ('Часткове обслуговування', 'Manutenção parcial'),
    ('Horaткове обслуговування', 'Manutenção periódica'),
    ('Тільки інспекції', 'Apenas inspecções'),
    ('Разові виклики', 'Chamadas pontuais'),
    ('Дата поchatку договору', 'Data de início do contrato'),
    ('Autoматичне продовження', 'Renovação automática'),
    ('Contrato продовжується автоматично якщо клієнт не розірвав',
     'O contrato renova-se automaticamente se o cliente não cancelar'),
    ('Номер договору', 'Número do contrato'),
    ('Вартість обслуговування / міс (€)', 'Custo de manutenção / mês (€)'),

    # ── Lift tab ───────────────────────────────────────────────────────────────
    ('Тип та виробник', 'Tipo e fabricante'),
    ('Тип ліфта', 'Tipo de elevador'),
    ('Безмашинний', 'Sem casa das máquinas'),
    ('Гідравлічний', 'Hidráulico'),
    ('Канатний (MRL)', 'Por cabo (MRL)'),
    ('Канатний (з машинним залом)', 'Por cabo (com casa das máquinas)'),
    ('Гвинтовий / Платформний', 'Por parafuso / Plataforma'),
    ('Autoматичні (2-стулкові)', 'Automáticas (2 folhas)'),
    ('Autoматичні (4-стулкові / телескопічні)', 'Automáticas (4 folhas / telescópicas)'),
    ('Напівавтоматичні / Розпашні', 'Semiautomáticas / Batentes'),
    ('Ручні (ґрати)', 'Manuais (grades)'),
    ('Ano виготовлення', 'Ano de fabrico'),
    ('Ano встановлення', 'Ano de instalação'),
    ('Серійний номер', 'Número de série'),
    ('<span class="input-group-text">кг</span>', '<span class="input-group-text">kg</span>'),
    ('осіб', 'pessoas'),
    ('<span class="input-group-text">м/с</span>', '<span class="input-group-text">m/s</span>'),
    ('Quantidade поверхів', 'Número de pisos'),
    ('<span class="input-group-text">пов.</span>', '<span class="input-group-text">piso(s)</span>'),
    ('Тип приводу', 'Tipo de accionamento'),
    ('Тип дверей', 'Tipo de portas'),
    ('<option value="other">Інший</option>', '<option value="other">Outro</option>'),

    # ── Service tab ────────────────────────────────────────────────────────────
    ('Статус та responsável', 'Estado e responsável'),
    ('Поточний статус', 'Estado actual'),
    ('На технічному обслуговуванні', 'Em manutenção técnica'),
    ('Неактивний (Inativo)', 'Inactivo'),
    ('Призначений технік', 'Técnico atribuído'),
    ('Autoматичне призначення', 'Atribuição automática'),
    ('Технік 1', 'Técnico 1'),
    ('Технік 2', 'Técnico 2'),
    ('Технік 3', 'Técnico 3'),
    ('Технічні огляди (ТО)', 'Inspecções técnicas (IT)'),
    ('Дата останньої технічної інспекції', 'Data da última inspecção técnica'),
    ('Планова дата наступної інспекції', 'Data prevista da próxima inspecção'),
    ('Періодичність', 'Periodicidade'),
    ('Кожні 3 місяці', 'Cada 3 meses'),
    ('Кожні 6 місяців', 'Cada 6 meses'),
    ('Щорічно', 'Anualmente'),
    ('Кожні 2 роки', 'Cada 2 anos'),
    ('Дата ліцензії / сертифікату', 'Data da licença / certificado'),
    ('Validade ліцензії', 'Validade da licença'),
    ('Нотатки обслуговування', 'Notas de manutenção'),
    ('Записи про ТО, ремонти, заміни деталей, особливості...',
     'Registos de manutenção, reparações, substituição de peças, particularidades...'),
    ('Звіти інспекцій', 'Relatórios de inspecção'),
    ('Збережіть ліфт, щоб переглянути звіти інспекцій',
     'Guarde o elevador para ver os relatórios de inspecção'),
    ('Додати звіт інспекції', 'Adicionar relatório de inspecção'),
    ('PDF Звіт', 'Relatório PDF'),
    ("обов'язкові поля", 'campos obrigatórios'),
    ('Guardar ліфт', 'Guardar elevador'),

    # ── Detail modal ───────────────────────────────────────────────────────────
    ('Detalhes ліфта', 'Detalhes do elevador'),
    ('Основна інформація', 'Informação principal'),
    ('<td><strong>Модель:</strong></td>', '<td><strong>Modelo:</strong></td>'),
    ('<td><strong>Тип:</strong></td>', '<td><strong>Tipo:</strong></td>'),
    ('<td><strong>Статус:</strong></td>', '<td><strong>Estado:</strong></td>'),
    ('<td><strong>Місткість:</strong></td>', '<td><strong>Capacidade:</strong></td>'),
    ('<td><strong>Кількість поверхів:</strong></td>', '<td><strong>Número de pisos:</strong></td>'),
    ('<td><strong>Тип приводу:</strong></td>', '<td><strong>Tipo de accionamento:</strong></td>'),
    ('<td><strong>Тип дверей:</strong></td>', '<td><strong>Tipo de portas:</strong></td>'),
    ('<td><strong>Ano виготовлення:</strong></td>', '<td><strong>Ano de fabrico:</strong></td>'),
    ('<td><strong>Ano встановлення:</strong></td>', '<td><strong>Ano de instalação:</strong></td>'),
    ('<td><strong>Частота інспекцій:</strong></td>', '<td><strong>Frequência de inspecções:</strong></td>'),
    ('Розташування', 'Localização'),
    ('<td><strong>Адреса:</strong></td>', '<td><strong>Endereço:</strong></td>'),
    ('<td><strong>Координати:</strong></td>', '<td><strong>Coordenadas:</strong></td>'),

    # ── Dynamic JS municipal numbers ───────────────────────────────────────────
    ('Муніципальні номери — по одному на кожен ліфт:', 'Números municipais — um por elevador:'),
    ('ліфти</span>', 'elevadores</span>'),
    ("'Nº Municipal ліфта 1'", "'Nº Municipal do elevador 1'"),
    ('"Nº Municipal ліфта 1"', '"Nº Municipal do elevador 1"'),
    ("'Nº Municipal ліфта ' + i", "'Nº Municipal do elevador ' + i"),
    ('"Nº Municipal ліфта " + i', '"Nº Municipal do elevador " + i'),
    ("Обов'язковий · QR генерується автоматично", 'Obrigatório · QR gerado automaticamente'),
    ("Обов'язковий", 'Obrigatório'),

    # ── Common UI button/label strings ─────────────────────────────────────────
    ('>Завантаження...<', '>A carregar...<'),
    ('>Завантаження<', '>A carregar<'),
    ("'Завантаження...'", "'A carregar...'"),
    ('"Завантаження..."', '"A carregar..."'),
    ('Завантаження...', 'A carregar...'),
    ('Завантаження', 'A carregar'),
    ('>Оновити<', '>Actualizar<'),
    ("'Оновити'", "'Actualizar'"),
    ('"Оновити"', '"Actualizar"'),
    ('>Зберегти<', '>Guardar<'),
    ("'Зберегти'", "'Guardar'"),
    ('"Зберегти"', '"Guardar"'),
    ('>Скасувати<', '>Cancelar<'),
    ("'Скасувати'", "'Cancelar'"),
    ('"Скасувати"', '"Cancelar"'),
    ('>Видалити<', '>Eliminar<'),
    ("'Видалити'", "'Eliminar'"),
    ('"Видалити"', '"Eliminar"'),
    ('>Закрити<', '>Fechar<'),
    ("'Закрити'", "'Fechar'"),
    ('"Закрити"', '"Fechar"'),
    ('>Підтвердити<', '>Confirmar<'),
    ("'Підтвердити'", "'Confirmar'"),
    ('"Підтвердити"', '"Confirmar"'),
    ('>Редагувати<', '>Editar<'),
    ("'Редагувати'", "'Editar'"),
    ('"Редагувати"', '"Editar"'),
    ('>Переглянути<', '>Ver<'),
    ("'Переглянути'", "'Ver'"),
    ('"Переглянути"', '"Ver"'),
    ('>Додати<', '>Adicionar<'),
    ("'Додати'", "'Adicionar'"),
    ('"Додати"', '"Adicionar"'),
    ('>Вийти<', '>Sair<'),
    ("'Вийти'", "'Sair'"),
    ('"Вийти"', '"Sair"'),
    ('>Профіль<', '>Perfil<'),
    ("'Профіль'", "'Perfil'"),
    ('"Профіль"', '"Perfil"'),
    ('>Налаштування<', '>Definições<'),
    ("'Налаштування'", "'Definições'"),
    ('"Налаштування"', '"Definições"'),
    ('>Створити<', '>Criar<'),
    ("'Створити'", "'Criar'"),
    ('"Створити"', '"Criar"'),

    # ── Alert / confirm messages ────────────────────────────────────────────────
    ("'Не вказано'", "'Não especificado'"),
    ('"Не вказано"', '"Não especificado"'),
    ('Не вказано', 'Não especificado'),
    ("'Невідомо'", "'Desconhecido'"),
    ('"Невідомо"', '"Desconhecido"'),
    ('Невідомо', 'Desconhecido'),
    ("'Помилка", "'Erro"),
    ('"Помилка', '"Erro'),
    ('>Помилка<', '>Erro<'),
    ('Помилка:', 'Erro:'),
    ("'Успіх'", "'Sucesso'"),
    ('"Успіх"', '"Sucesso"'),
    (">Успіх<", ">Sucesso<"),
    ("'Будь ласка,", "'Por favor,"),
    ('"Будь ласка,', '"Por favor,'),
    ('Будь ласка,', 'Por favor,'),
    ("'Будь ласка", "'Por favor"),
    ('"Будь ласка"', '"Por favor"'),
    ('Будь ласка', 'Por favor'),
    ("'Ви впевнені", "'Tem a certeza"),
    ('"Ви впевнені', '"Tem a certeza'),
    ('Ви впевнені', 'Tem a certeza'),
    ("'Увага'", "'Aviso'"),
    ('"Увага"', '"Aviso"'),
    ('>Увага<', '>Aviso<'),
    ('Увага!', 'Atenção!'),
    ('Попередження:', 'Aviso:'),
    ('Попередження', 'Aviso'),
    ("'Невірний", "'Inválido"),
    ('"Невірний', '"Inválido'),
    ('Невірний', 'Inválido'),
    ("'Дані збережено'", "'Dados guardados'"),
    ('"Дані збережено"', '"Dados guardados"'),
    ("'Дані оновлено'", "'Dados actualizados'"),
    ('"Дані оновлено"', '"Dados actualizados"'),
    ("'Видалено'", "'Eliminado'"),
    ('"Видалено"', '"Eliminado"'),
    ("'Не знайдено'", "'Não encontrado'"),
    ('"Не знайдено"', '"Não encontrado"'),

    # ── Status labels ───────────────────────────────────────────────────────────
    ('>Активний<', '>Activo<'),
    ('>Неактивний<', '>Inactivo<'),
    ('>Очікує<', '>Pendente<'),
    ('>Виконано<', '>Concluído<'),
    ('>Скасовано<', '>Cancelado<'),
    ('>Відхилено<', '>Recusado<'),
    ('>Прийнято<', '>Aceite<'),
    ('>Новий<', '>Novo<'),
    ("'Активний'", "'Activo'"),
    ('"Активний"', '"Activo"'),
    ("'Неактивний'", "'Inactivo'"),
    ('"Неактивний"', '"Inactivo"'),
    ("'Очікує'", "'Pendente'"),
    ('"Очікує"', '"Pendente"'),
    ("'Виконано'", "'Concluído'"),
    ('"Виконано"', '"Concluído"'),
    ("'Скасовано'", "'Cancelado'"),
    ('"Скасовано"', '"Cancelado"'),
    ("'Відхилено'", "'Recusado'"),
    ('"Відхилено"', '"Recusado"'),

    # ── Priority labels ─────────────────────────────────────────────────────────
    ('>Високий<', '>Alto<'),
    ('>Середній<', '>Médio<'),
    ('>Низький<', '>Baixo<'),
    ('>Критичний<', '>Crítico<'),
    ("'Високий'", "'Alto'"),
    ('"Високий"', '"Alto"'),
    ("'Середній'", "'Médio'"),
    ('"Середній"', '"Médio"'),
    ("'Низький'", "'Baixo'"),
    ('"Низький"', '"Baixo"'),
    ("'Критичний'", "'Crítico'"),
    ('"Критичний"', '"Crítico"'),

    # ── Users page ──────────────────────────────────────────────────────────────
    ('Дата реєстрації', 'Data de registo'),
    ('Тип облікового запису', 'Tipo de conta'),
    ('Заблокований', 'Bloqueado'),
    ('Не заблокований', 'Não bloqueado'),
    ('Надіслати лист', 'Enviar carta'),
    ('Скинути пароль', 'Repor palavra-passe'),
    ('Підтвердити email', 'Confirmar email'),

    # ── Requests page ───────────────────────────────────────────────────────────
    ('Тип запиту', 'Tipo de pedido'),
    ('Терміновість', 'Urgência'),
    ('Причина відмови', 'Motivo de recusa'),
    ('Описіть проблему', 'Descreva o problema'),
    ('Призначити техніка', 'Atribuir técnico'),
    ('Призначити технікa', 'Atribuir técnico'),

    # ── QR management ───────────────────────────────────────────────────────────
    ('Генерувати QR коди', 'Gerar códigos QR'),
    ('Завантажити PDF', 'Descarregar PDF'),
    ('Розмір коду', 'Tamanho do código'),
    ('Колір коду', 'Cor do código'),
    ('Перевірити код', 'Verificar código'),
    ('Історія сканувань', 'Histórico de leituras'),
    ('сканувань', 'leituras'),

    # ── Analytics ───────────────────────────────────────────────────────────────
    ('Зведена аналітика', 'Análise global'),
    ('Детальний звіт', 'Relatório detalhado'),
    ('Завантажити звіт', 'Descarregar relatório'),
    ('Зведений звіт', 'Relatório de síntese'),
    ('Динаміка', 'Evolução'),
    ('Порівняння', 'Comparação'),
    ('по місяцях', 'por mês'),
    ('по тижнях', 'por semana'),
    ('по роках', 'por ano'),
    ('AI Прогнозування', 'AI Previsão'),
    ('Прогнозування', 'Previsão'),

    # ── Inspections ─────────────────────────────────────────────────────────────
    ('Дата інспекції', 'Data de inspecção'),
    ('Тип інспекції', 'Tipo de inspecção'),
    ('Результат інспекції', 'Resultado da inspecção'),
    ('Технік-інспектор', 'Técnico inspector'),
    ('Наступна інспекція', 'Próxima inspecção'),
    ('Відповідний орган', 'Entidade responsável'),
    ('Пройдено', 'Aprovado'),
    ('Не пройдено', 'Reprovado'),
    ('Умовно пройдено', 'Aprovado condicionalmente'),

    # ── Tech panel tasks ────────────────────────────────────────────────────────
    ('Прийняти завдання', 'Aceitar tarefa'),
    ('Відхилити завдання', 'Recusar tarefa'),
    ('Час виїзду', 'Hora de saída'),
    ('Час прибуття', 'Hora de chegada'),
    ('На місці', 'No local'),
    ('Дорогою', 'A caminho'),
    ('Потрібна запчастина', 'Peça necessária'),
    ('Гарантійний ремонт', 'Reparação em garantia'),
    ('Мої завдання', 'As minhas tarefas'),
    ('Всі завдання', 'Todas as tarefas'),

    # ── Dispatcher tasks ────────────────────────────────────────────────────────
    ('Призначити завдання', 'Atribuir tarefa'),
    ('Перепризначити', 'Reatribuir'),
    ('Черга завдань', 'Fila de tarefas'),
    ('Завдання на сьогодні', 'Tarefas para hoje'),

    # ── Generic empty/loading states ────────────────────────────────────────────
    ('Не знайдено', 'Não encontrado'),
    ('Пошуку не знайдено', 'Sem resultados de pesquisa'),
    ('Нічого не знайдено', 'Nada encontrado'),
    ('Список порожній', 'Lista vazia'),
    ('Дані відсутні', 'Sem dados'),
    ('Немає даних', 'Sem dados'),
    ('Немає записів', 'Sem registos'),
    ('Оберіть', 'Seleccione'),
    ('Необов\'язково', 'Opcional'),
    ('Дякуємо', 'Obrigado'),
    ('Хвилину...', 'Um momento...'),
    ('Секунду...', 'Um segundo...'),
    ('Чекайте...', 'Aguarde...'),
    ('Обробляється...', 'A processar...'),
    ('Зберігаємо...', 'A guardar...'),
    ('Видаляємо...', 'A eliminar...'),
    ('Завантажуємо...', 'A carregar...'),

    # ── HTML comments ───────────────────────────────────────────────────────────
    ('<!-- Навігаційна панель -->', '<!-- Barra de navegação -->'),
    ('<!-- Бічна панель -->', '<!-- Painel lateral -->'),
    ('<!-- Дашборд -->', '<!-- Dashboard -->'),
    ('<!-- Ліфти -->', '<!-- Elevadores -->'),
    ('<!-- Користувачі -->', '<!-- Utilizadores -->'),
    ('<!-- Документи -->', '<!-- Documentos -->'),
    ('<!-- Аналітика -->', '<!-- Análise -->'),
    ('<!-- AI Асистент -->', '<!-- AI Assistente -->'),
    ('<!-- Підтримка -->', '<!-- Suporte -->'),
    ('<!-- Координати -->', '<!-- Coordenadas -->'),
    ('<!-- Карта -->', '<!-- Mapa -->'),
    ('<!-- Пагінація буде додана через JavaScript -->', '<!-- Paginação via JavaScript -->'),
    ('<!-- Дані будуть додані через JavaScript -->', '<!-- Dados via JavaScript -->'),
    ('<!-- Динамічні рядки', '<!-- Linhas dinâmicas'),
    ('<!-- Прихований контейнер', '<!-- Contentor oculto'),

    # ── CSS comments ─────────────────────────────────────────────────────────────
    ('оптимізований, без зайвих !important', 'optimizado, sem !important desnecessários'),
    ('Фіксована мінімальна ширина для таблиці', 'Largura mínima fixa para a tabela'),
    ('Стилі для elevadores за однією адресою', 'Estilos para elevadores no mesmo endereço'),
    ('Маркер поточного localização', 'Marcador da localização actual'),
    ('Novos чисті стилі', 'Novos estilos limpos'),
    ('Стилі для нового динамічно criadoго input поля',
     'Estilos para o campo input criado dinamicamente'),
    ('Стилі для нового динамічно criadoго textarea comentáriosв',
     'Estilos para o textarea criado dinamicamente'),
    ('Стилі для', 'Estilos para'),
    ('чергування кольорів', 'alternância de cores'),

    # ── Email templates ─────────────────────────────────────────────────────────
    ('Email modeloи', 'Modelos de email'),
    ('Modeloи звітів', 'Modelos de relatórios'),

    # ── Map page strings ────────────────────────────────────────────────────────
    ('Мапа ліфтів', 'Mapa de elevadores'),
    ('<p>Мапа elevadores</p>', '<p>Mapa de elevadores</p>'),
    ('Список elevadores <span', 'Lista de elevadores <span'),
    ('Інфо про elevadores за цією адресою', 'Info sobre elevadores neste endereço'),
    ('<h3 class="card-title">Список elevadores', '<h3 class="card-title">Lista de elevadores'),

    # ── Hybrid corruptions (PT word + UA suffix) ────────────────────────────────
    ('relatórioу', 'relatório'),
    ('clienteа', 'cliente'),
    ('clienteу', 'ao cliente'),
    ('registoу', 'registo'),
    ('elevadorа', 'elevador'),
    ('Técnicoа', 'Técnico'),
    ('técnicoа', 'técnico'),
    ('comentáriosв', 'comentários'),
    ('criadoго', 'criado'),

    # ── Lift status options ─────────────────────────────────────────────────────
    ('В обслуговуванні', 'Em manutenção'),
    ('В резерві', 'Em reserva'),
    ('На ремонті', 'Em reparação'),
    ('Списаний', 'Abatido'),
    ('Зупинено', 'Parado'),

    # ── Profile / settings ──────────────────────────────────────────────────────
    ('Змінити пароль', 'Alterar palavra-passe'),
    ('Поточний пароль', 'Palavra-passe actual'),
    ('Новий пароль', 'Nova palavra-passe'),
    ('Підтвердити пароль', 'Confirmar palavra-passe'),
    ('Зберегти зміни', 'Guardar alterações'),
    ('Скасувати зміни', 'Cancelar alterações'),
    ('Особисті дані', 'Dados pessoais'),

    # ── Orcamento / docs ────────────────────────────────────────────────────────
    ('Кошторис', 'Orçamento'),
    ('кошторис', 'orçamento'),
    ('Кошториси', 'Orçamentos'),
    ('кошториси', 'orçamentos'),
    ('Кошторисів', 'Orçamentos'),
    ('Створити кошторис', 'Criar orçamento'),
    ('Список кошторисів', 'Lista de orçamentos'),

    # ── Notifications ───────────────────────────────────────────────────────────
    ('Сповіщення', 'Notificações'),
    ('Нові сповіщення', 'Novas notificações'),
    ('Позначити як прочитане', 'Marcar como lido'),
    ('Позначити всі як прочитані', 'Marcar todas como lidas'),

    # ── AI Assistant ───────────────────────────────────────────────────────────
    ('AI Асистент', 'AI Assistente'),
    ('Асистент', 'Assistente'),
    ('Чат з AI', 'Chat com AI'),
    ('Введіть запитання...', 'Introduza a pergunta...'),
    ('Очистити чат', 'Limpar chat'),

    # ── Tools ─────────────────────────────────────────────────────────────────
    ('Технічна підтримка', 'Suporte técnico'),
    ('Підтримка', 'Suporte'),
    ('Написати в підтримку', 'Contactar suporte'),
    ('Інструменти', 'Ferramentas'),
    ('База знань', 'Base de conhecimento'),
    ('Відеоінструкції', 'Tutoriais em vídeo'),

    # ── Standalone visible HTML labels ─────────────────────────────────────────
    ('>Статус<', '>Estado<'),
    ('>Тип<', '>Tipo<'),
    ('>Дата<', '>Data<'),
    ('>Адреса<', '>Endereço<'),
    ('>Клієнт<', '>Cliente<'),
    ('>Технік<', '>Técnico<'),
    ('>Пріоритет<', '>Prioridade<'),
    ('>Звіти<', '>Relatórios<'),
    ('>Документи<', '>Documentos<'),
    ('>Інспекції<', '>Inspecções<'),
    ('>Заявки<', '>Pedidos<'),
    ('>Завдання<', '>Tarefas<'),
    ('>Список<', '>Lista<'),
    ('>Модель<', '>Modelo<'),
    ('>Ліфт<', '>Elevador<'),
    ('>Ліфти<', '>Elevadores<'),
    ('>Надіслати<', '>Enviar<'),
    ("'Надіслати'", "'Enviar'"),
    ('"Надіслати"', '"Enviar"'),
    ('>Скасувати<', '>Cancelar<'),
]

# Deduplicate preserving order
seen = set()
DEDUP = []
for pair in TRANSLATIONS:
    if pair[0] not in seen:
        seen.add(pair[0])
        DEDUP.append(pair)

def process_file(path):
    txt = path.read_text(encoding='utf-8')
    original = txt
    for old, new in DEDUP:
        if old in txt:
            txt = txt.replace(old, new)
    if txt != original:
        path.write_text(txt, encoding='utf-8')
        return True
    return False

base = Path('/workspaces/deapseak/pages')
for panel in ['admin', 'dispatcher', 'tech']:
    changed = skipped = 0
    for f in sorted((base / panel).glob('*.html')):
        if process_file(f):
            changed += 1
        else:
            skipped += 1
    print(f'{panel}: {changed} files updated, {skipped} unchanged')
print('Done.')
