"""Pass 20: Remaining Ukrainian in assignments.html and requests.html."""
from pathlib import Path

TRANSLATIONS = [
    # ── assignments.html ─────────────────────────────────────────────────────
    ("<label>Período:</label>", "<label>Período:</label>"),  # already PT, skip
    ('placeholder="Escrever comenтár..."', 'placeholder="Escrever comentário..."'),
    ('placeholder="Escrever comenтар..."', 'placeholder="Escrever comentário..."'),
    ("// Менеджер призначень для диспетчерів (використовує уніфіковану систему)",
     "// Gestor de atribuições para despachantes (utiliza sistema unificado)"),
    ("console.warn('⚠️ Не вдалося descarregar техніків з API');",
     "console.warn('⚠️ Não foi possível carregar técnicos da API');"),
    ("// Fallback на demo дані", "// Fallback para dados demo"),
    ("// Отримати pedidos для диспетчера (незавершені)",
     "// Obter pedidos para o despachante (não concluídos)"),
    ("// Призначити заявку технічному фахівцю",
     "// Atribuir pedido ao técnico"),
    ("toastr.error('Не вдалося призначити заявку: ' + error.message);",
     "toastr.error('Não foi possível atribuir o pedido: ' + error.message);"),
    ("// Mostrar авансado модал призначення техніка (як в адмін панелі)",
     "// Mostrar modal avançado de atribuição de técnico (como no painel admin)"),
    ("// Mostrar авансado модал призначення техніка (як в адмін панелі)\n",
     "// Mostrar modal avançado de atribuição de técnico (como no painel admin)\n"),
    ("// Переназначити заявку", "// Reatribuir pedido"),
    ("// Descarregar та відобразити призначення", "// Carregar e mostrar atribuições"),
    ("// Descarregar призначення з API", "// Carregar atribuições da API"),
    ("throw new Error('Не вдалося descarregar призначення');",
     "throw new Error('Não foi possível carregar atribuições');"),
    ("// API v2 повертає: { success: true, data: { requests: [...] } }",
     "// API v2 retorna: { success: true, data: { requests: [...] } }"),
    ("// Конвертуємо формат API в формат UI",
     "// Converter formato API para formato UI"),
    ("// Витягуємо дані ліфта", "// Extrair dados do elevador"),
    ("// Перевіряємо різні варіанти структури даних",
     "// Verificar diferentes variantes da estrutura de dados"),
    ("// Якщо lift це ObjectId string, а не instalação",
     "// Se lift é ObjectId string e não instalação"),
    ("// Спробуємо взяти адресу з інших полів",
     "// Tentar obter endereço de outros campos"),
    ("// Lift це instalação з даними", "// Lift é instalação com dados"),
    ("// Пріоритет: address instalação > addressLine > municipalNumber",
     "// Prioridade: address instalação > addressLine > municipalNumber"),
    ("// Витягуємо дані техніка", "// Extrair dados do técnico"),
    ("// Якщо assignedTo це ObjectId string, а не instalação",
     "// Se assignedTo é ObjectId string e não instalação"),
    ("// Спробуємо знайти техніка зі списку", "// Tentar encontrar técnico da lista"),
    ("// Зберігаємо оригінальний instalação для дебагу",
     "// Guardar instalação original para debug"),
    ("// ✅ ВАЖЛИВО: Зберігаємо assignments для використання в viewAssignment()",
     "// ✅ IMPORTANTE: Guardar assignments para uso em viewAssignment()"),
    ("completed:   { cls: 'badge-success',  label: 'Виконана' },",
     "completed:   { cls: 'badge-success',  label: 'Concluída' },"),
    ("cancelled:   { cls: 'badge-danger',   label: 'Скасована' }",
     "cancelled:   { cls: 'badge-danger',   label: 'Cancelada' }"),
    ("title=\"Chamada falsa\"><i class=\"fas fa-phone-slash mr-1\"></i>Фальш. виклик</span>`",
     "title=\"Chamada falsa\"><i class=\"fas fa-phone-slash mr-1\"></i>Falsa chamada</span>`"),
    ("<i class=\"fas fa-archive mr-1\"></i>Архів</span>` : '');",
     "<i class=\"fas fa-archive mr-1\"></i>Arquivo</span>` : '');"),
    ("<i class=\"fas fa-redo mr-1\"></i>Відкрити</button>` : '';",
     "<i class=\"fas fa-redo mr-1\"></i>Reabrir</button>` : '';"),
    ("<i class=\"fas fa-calendar-plus mr-1\"></i>Продовжити</button>` : '';",
     "<i class=\"fas fa-calendar-plus mr-1\"></i>Prolongar</button>` : '';"),
    ("Заявок не encontrado</div>';", "Pedidos não encontrados</div>';"),
    ("${isOverdue ? '<span class=\"badge badge-pill badge-danger\">Протерм.</span>' : ''}",
     "${isOverdue ? '<span class=\"badge badge-pill badge-danger\">Atrasado</span>' : ''}"),
    ("<i class=\"fas fa-user-cog mr-1\"></i>Призначити</button>",
     "<i class=\"fas fa-user-cog mr-1\"></i>Atribuir</button>"),
    ("${isOverdue ? '<span class=\"badge badge-pill badge-danger ml-1\">Протерм.</span>' : ''}",
     "${isOverdue ? '<span class=\"badge badge-pill badge-danger ml-1\">Atrasado</span>' : ''}"),
    ("// Безпечне оновлення DOM елементів", "// Atualização segura de elementos DOM"),
    ("title: 'Закрити заявку?',", "title: 'Fechar pedido?',"),
    ("text: 'Заявку буде позначено як виконану.',",
     "text: 'O pedido será marcado como concluído.',"),
    ("confirmButtonText: 'Так, закрити',", "confirmButtonText: 'Sim, fechar',"),
    ("throw new Error('Erro оновлення статусу');",
     "throw new Error('Erro ao actualizar estado');"),
    ("if (window.toastr) toastr.success('Заявку fechado як виконану');",
     "if (window.toastr) toastr.success('Pedido fechado como concluído');"),
    ("title: 'Повторно відкрити?',", "title: 'Reabrir?',"),
    ("text: 'Заявку буде повернено в статус \"Em curso\".',",
     "text: 'O pedido será devolvido ao estado \"Em curso\".',"),
    ("confirmButtonText: 'Так, відкрити',", "confirmButtonText: 'Sim, reabrir',"),
    ("if (window.toastr) toastr.success('Заявку повторно aberto');",
     "if (window.toastr) toastr.success('Pedido reaberto com sucesso');"),
    ("console.log('🔍 Переглядаємо запит:', requestId);",
     "console.log('🔍 A visualizar pedido:', requestId);"),
    ("// Знайти запит в завантажених даних", "// Encontrar pedido nos dados carregados"),
    ("console.warn('⚠️ Запит не encontrado:', requestId);",
     "console.warn('⚠️ Pedido não encontrado:', requestId);"),
    ("alert(`Запит #${requestId} не encontrado`);",
     "alert(`Pedido #${requestId} não encontrado`);"),
    ("console.log('✅ Encontrado запит:', assignment);",
     "console.log('✅ Pedido encontrado:', assignment);"),
    ("// Заповнити модальне вікно даними", "// Preencher janela modal com dados"),
    ("// Статус з кольорами", "// Estado com cores"),
    ("// Пріоритет з кольорами", "// Prioridade com cores"),
    ("// Технік", "// Técnico"),
    ("// Опис", "// Descrição"),
    ("$('#modalDescription').text(assignment.description || 'Опис відсутній');",
     "$('#modalDescription').text(assignment.description || 'Sem descrição');"),
    ("// Адреса", "// Morada"),
    ("$('#modalLiftId').text(assignment.liftId || 'ID невідомий');",
     "$('#modalLiftId').text(assignment.liftId || 'ID desconhecido');"),
    ("// Клієнт", "// Cliente"),
    ("$('#modalClientName').text(assignment.client.name || 'Ім\\'я невідоме');",
     "$('#modalClientName').text(assignment.client.name || 'Nome desconhecido');"),
    ("$('#modalClientName').text('Інформація відсутня');",
     "$('#modalClientName').text('Informação indisponível');"),
    ("// Історія (timeline)", "// Histórico (timeline)"),
    ("title: 'Запит criado',", "title: 'Pedido criado',"),
    ("description: 'Клієнт подав запит на обслуговування'",
     "description: 'O cliente submeteu um pedido de assistência'"),
    ("title: 'Призначено техніка',", "title: 'Técnico atribuído',"),
    ("description: `Призначено: ${assignment.assignedToName}`",
     "description: `Atribuído: ${assignment.assignedToName}`"),
    ("title: 'Розпоchatо роботу',", "title: 'Trabalho iniciado',"),
    ("description: 'Технік розпочав виконання'",
     "description: 'O técnico iniciou a execução'"),
    ("description: 'Роботу успішно concluído'",
     "description: 'Trabalho concluído com sucesso'"),
    ("// Зберегти ID та дані для можливості редагування",
     "// Guardar ID e dados para possível edição"),
    ("// ── Дедлайн (4-та coluna info bar) ──",
     "// ── Prazo (4.ª coluna da barra de info) ──"),
    ("// ── PDF-кнопка ──", "// ── Botão PDF ──"),
    ("else Swal && Swal.fire('PDF', 'Функція PDF поки недоступна для диспетчера', 'info');",
     "else Swal && Swal.fire('PDF', 'Função PDF ainda não disponível para o despachante', 'info');"),
    ("// ── Mostrar правильні ações (hide/show status buttons у правій панелі) ──",
     "// ── Mostrar acções correctas (hide/show botões de estado no painel direito) ──"),
    ("// Ховаємо кнопки дій що не мають сенсу для завершених/скасованих",
     "// Ocultar botões de acção sem sentido para pedidos concluídos/cancelados"),
    ("// ── Repor на перший таб ──", "// ── Repor no primeiro separador ──"),
    ("// Descarregar карту", "// Carregar mapa"),
    ("// Descarregar найближчих техніків", "// Carregar técnicos mais próximos"),
    ("// Mostrar/сховати кнопки залежно від стану архіву",
     "// Mostrar/ocultar botões conforme estado do arquivo"),
    ("// Mostrar модальне вікно", "// Mostrar janela modal"),
    ("const name = (c.user && (c.user.username || c.user.firstName)) || 'Користувач';",
     "const name = (c.user && (c.user.username || c.user.firstName)) || 'Utilizador';"),
    ("if (!text) { toastr.warning('Введіть текст коментаря'); return; }",
     "if (!text) { toastr.warning('Introduza o texto do comentário'); return; }"),
    ("toastr.success('Comentário додано');", "toastr.success('Comentário adicionado');"),
    ("toastr.error('Не вдалось додати коментар: ' + e.message);",
     "toastr.error('Não foi possível adicionar comentário: ' + e.message);"),
    ("throw new Error(err.message || `Помилка ${resp.status}`);",
     "throw new Error(err.message || `Erro ${resp.status}`);"),
    ("toastr.success('Статус змінено');", "toastr.success('Estado alterado');"),
    ("// Закрити Bootstrap modal перш, тоді відкрити Swal (без конфлікту z-index та backdrop)",
     "// Fechar modal Bootstrap antes de abrir Swal (sem conflito z-index e backdrop)"),
    ("// Відкрити адресу в Google Maps", "// Abrir endereço no Google Maps"),
    ("// Перемикання режиму перегляду архіву", "// Alternar modo de visualização do arquivo"),
    ("<i class=\"fas fa-times mr-1\"></i>Вийти з архіву",
     "<i class=\"fas fa-times mr-1\"></i>Sair do arquivo"),
    ("<i class=\"fas fa-archive mr-1\"></i>Архів",
     "<i class=\"fas fa-archive mr-1\"></i>Arquivo"),
    ("// Restaurar заявку з архіву", "// Restaurar pedido do arquivo"),
    ("if (!confirm('Restaurar заявку із архіву?')) return;",
     "if (!confirm('Restaurar pedido do arquivo?')) return;"),
    ("await Swal.fire({ icon: 'success', title: 'Відновлено!', text: 'Заявку повернуто до активних.', timer: 1800, showConfirmButton: false });",
     "await Swal.fire({ icon: 'success', title: 'Restaurado!', text: 'Pedido devolvido aos activos.', timer: 1800, showConfirmButton: false });"),
    ("alert('Erro: ' + (result.message || 'Не вдалося restaurar'));",
     "alert('Erro: ' + (result.message || 'Não foi possível restaurar'));"),
    ("// Arquivar заявку з модального вікна", "// Arquivar pedido da janela modal"),
    ("title: 'Arquivar заявку?',", "title: 'Arquivar pedido?',"),
    ("html: `Заявку <b>#${assignment.id || assignment._id}</b> буде переміщено до архіву.<br>Вона зникне зі списку активних pedidos.`,",
     "html: `O pedido <b>#${assignment.id || assignment._id}</b> será movido para o arquivo.<br>Desaparecerá da lista de pedidos activos.`,"),
    ("Swal.fire({ icon: 'error', title: 'Erro', text: (data && data.message) || 'Не вдалось arquivar' });",
     "Swal.fire({ icon: 'error', title: 'Erro', text: (data && data.message) || 'Não foi possível arquivar' });"),
    ("Swal.fire({ icon: 'error', title: 'Erro', text: 'Erro з\\'єднання' });",
     "Swal.fire({ icon: 'error', title: 'Erro', text: 'Erro de ligação' });"),
    ("// Позначити як фальшивий виклик і arquivar",
     "// Marcar como falsa chamada e arquivar"),
    ("html: `Заявку <b>#${assignment.id || assignment._id}</b> буде позначено як <b>фальшивий виклик</b> і автоматично архівовано.`,",
     "html: `O pedido <b>#${assignment.id || assignment._id}</b> será marcado como <b>falsa chamada</b> e arquivado automaticamente.`,"),
    ("confirmButtonText: '<i class=\"fas fa-phone-slash mr-1\"></i>Так, фальшивий виклик',",
     "confirmButtonText: '<i class=\"fas fa-phone-slash mr-1\"></i>Sim, falsa chamada',"),
    ("Swal.fire({ icon: 'success', title: 'Позначено', text: data.message, timer: 1800, showConfirmButton: false });",
     "Swal.fire({ icon: 'success', title: 'Marcado', text: data.message, timer: 1800, showConfirmButton: false });"),
    ("Swal.fire({ icon: 'error', title: 'Erro', text: (data && data.message) || 'Не вдалось виконати операцію' });",
     "Swal.fire({ icon: 'error', title: 'Erro', text: (data && data.message) || 'Não foi possível executar a operação' });"),
    ("// Descarregar карту (Leaflet + OpenStreetMap / Nominatim)",
     "// Carregar mapa (Leaflet + OpenStreetMap / Nominatim)"),
    ("// Відновлюємо структуру div якщо вона була замінена mensagemм",
     "// Restaurar estrutura div se foi substituída por mensagem"),
    ("// Знищуємо попередній екземпляр мапи", "// Destruir instância anterior do mapa"),
    ("// Ініціалізуємо Leaflet з дефолтним центром (Лісабон)",
     "// Inicializar Leaflet com centro padrão (Lisboa)"),
    ("// Геокодуємо адресу через Nominatim (безкоштовно, без chaveа)",
     "// Geocodificar endereço via Nominatim (gratuito, sem chave)"),
    ("// Адреса не знайдена — показуємо Лісабон з mensagemм",
     "// Endereço não encontrado — mostrar Lisboa com mensagem"),
    (".setContent(`Адресу не вдалося знайти: <b>${address}</b>`)",
     ".setContent(`Endereço não encontrado: <b>${address}</b>`)"),
    ("// Fallback: показуємо карту без маркера", "// Fallback: mostrar mapa sem marcador"),
    ("// Примусово оновлюємо tamanho після відображення модалу",
     "// Forçar atualização do tamanho após exibir modal"),
    ("// Descarregar найближчих техніків", "// Carregar técnicos mais próximos"),
    ("// Отримуємо список всіх техніків", "// Obter lista de todos os técnicos"),
    ("container.html('<div class=\"col-12 text-center text-muted\">Немає доступних техніків</div>');",
     "container.html('<div class=\"col-12 text-center text-muted\">Sem técnicos disponíveis</div>');"),
    ("// В реальному застосунку тут була б геолокація",
     "// Numa aplicação real seria usada geolocalização"),
    ("// Поки що сортуємо за доступністю", "// Por agora ordenar por disponibilidade"),
    (".slice(0, 3); // Показуємо топ 3", ".slice(0, 3); // Mostrar top 3"),
    ("const distance = ((index + 1) * 1.5).toFixed(1); // Демо відстань",
     "const distance = ((index + 1) * 1.5).toFixed(1); // Distância demo"),
    ("const eta = (index + 1) * 15; // Демо час прибуття",
     "const eta = (index + 1) * 15; // Tempo de chegada demo"),
    ("<small class=\"d-block\">${distance} км</small>",
     "<small class=\"d-block\">${distance} km</small>"),
    ("<small class=\"d-block\">${eta} хв</small>",
     "<small class=\"d-block\">${eta} min</small>"),
    ("container.html('<div class=\"col-12 text-center text-muted\">Немає доступних техніків поблизу</div>');",
     "container.html('<div class=\"col-12 text-center text-muted\">Sem técnicos disponíveis nas proximidades</div>');"),
    ("console.error('Erro завантаження техніків:', error);",
     "console.error('Erro ao carregar técnicos:', error);"),
    ("// Швидке призначення техніка", "// Atribuição rápida de técnico"),
    ("alert('Erro: ID запиту не encontrado');",
     "alert('Erro: ID do pedido não encontrado');"),
    ("console.log('⚡ Швидке призначення:', { requestId: this.currentViewingId, technicianId });",
     "console.log('⚡ Atribuição rápida:', { requestId: this.currentViewingId, technicianId });"),
    ("if (confirm('Призначити цього техніка на запит?')) {",
     "if (confirm('Atribuir este técnico ao pedido?')) {"),
    ("// Закрити модальне вікно після призначення",
     "// Fechar janela modal após atribuição"),
    ("// Editar призначення", "// Editar atribuição"),
    ("console.log('✏️ Редагуємо призначення:', this.currentViewingId);",
     "console.log('✏️ A editar atribuição:', this.currentViewingId);"),
    ("alert('Erro: дані запиту не encontrado');",
     "alert('Erro: dados do pedido não encontrados');"),
    ("// Закрити модальне вікно перегляду", "// Fechar janela modal de visualização"),
    ("// Відкрити форму редагування (можна створити окреме модальне вікно)",
     "// Abrir formulário de edição (pode criar janela modal separada)"),
    ("const newDescription = prompt('Novo опис проблеми:', assignment.description);",
     "const newDescription = prompt('Nova descrição do problema:', assignment.description);"),
    ("// Actualizar опис призначення", "// Actualizar descrição da atribuição"),
    ("alert('Опис успішно atualizado!');", "alert('Descrição actualizada com sucesso!');"),
    ("throw new Error('Erro оновлення');", "throw new Error('Erro ao actualizar');"),
    ("console.error('Erro оновлення опису:', error);",
     "console.error('Erro ao actualizar descrição:', error);"),
    ("alert('Не вдалося оновити опис: ' + error.message);",
     "alert('Não foi possível actualizar a descrição: ' + error.message);"),
    ("// Reatribuir техніка з модального вікна",
     "// Reatribuir técnico da janela modal"),
    ("alert('Erro: ID запиту не encontrado');",
     "alert('Erro: ID do pedido não encontrado');"),
    ("// Дочекатись закриття viewAssignmentModal, потім відкрити completo діалог",
     "// Aguardar fecho de viewAssignmentModal, depois abrir diálogo completo"),
    ("throw new Error(error.message || 'Erro підтвердження');",
     "throw new Error(error.message || 'Erro de confirmação');"),
    ("alert('Заявку confirmado!');", "alert('Pedido confirmado!');"),
    ("console.error('Erro підтвердження pedidos:', error);",
     "console.error('Erro ao confirmar pedido:', error);"),
    ("alert('Не вдалося confirmar заявку: ' + error.message);",
     "alert('Não foi possível confirmar o pedido: ' + error.message);"),
    ("// Ініціалізація AdminLTE", "// Inicialização AdminLTE"),
    ("// Темна тема", "// Tema escuro"),
    ("// Verificação з'єднання", "// Verificação de ligação"),
    ("// A carregar dados диспетчера", "// A carregar dados do despachante"),
    ("// Ініціалізація систем", "// Inicialização de sistemas"),
    ("// 🔧 ВИПРАВЛЕННЯ: Додаємо функції для модальних вікон",
     "// 🔧 CORRECÇÃO: Adicionar funções para janelas modais"),
    ("// Mostrar сповіщення", "// Mostrar notificações"),
    ("alert('Notificações: У вас 3 нових pedidos!');",
     "alert('Notificações: Tem 3 novos pedidos!');"),
    ("// Застосувати filtros", "// Aplicar filtros"),
    ("console.log('Застосування фільтрів...');",
     "console.log('A aplicar filtros...');"),
    ("alert(`Filtros застосовано: Пріоритет=${priority}, Статус=${status}`);",
     "alert(`Filtros aplicados: Prioridade=${priority}, Estado=${status}`);"),
    ("console.log('Filtros скинуто');", "console.log('Filtros limpos');"),
    ("alert('Filtros скинуто');", "alert('Filtros limpos');"),
    ("// Exportar призначень", "// Exportar atribuições"),
    ("console.log('Exportar призначень...');", "console.log('A exportar atribuições...');"),
    ("alert('Exportar розпоchatо. Ficheiro буде завантажено через кілька секунд.');",
     "alert('Exportação iniciada. O ficheiro será descarregado em breve.');"),
    ("// Mostrar календар", "// Mostrar calendário"),
    ("alert('Відкриття календарного вигляду...');",
     "alert('A abrir vista de calendário...');"),
    ("// Тут можна перенаправити на календар", "// Aqui pode redirecionar para o calendário"),
    ("// Pesquisar призначень", "// Pesquisar atribuições"),
    ("alert(`Pesquisar за запитом: \"${query}\"`);",
     "alert(`Pesquisar por: \"${query}\"`);"),
    ("alert('Перехід на попередню сторінку');", "alert('Ir para a página anterior');"),
    ("alert('Перехід на наступну сторінку');", "alert('Ir para a página seguinte');"),
    ("// Створити нове призначення", "// Criar nova atribuição"),
    ("title: 'Нове призначення',", "title: 'Nova atribuição',"),
    ("placeholder=\"Детально опишіть avaria або необхідні роботи...\">",
     "placeholder=\"Descreva detalhadamente a avaria ou trabalhos necessários...\">"),
    ("<option value=\"low\">🟢  Низький</option>",
     "<option value=\"low\">🟢  Baixo</option>"),
    ("<option value=\"medium\" selected>🟡  Середній</option>",
     "<option value=\"medium\" selected>🟡  Médio</option>"),
    ("<option value=\"high\">🟠  Високий</option>",
     "<option value=\"high\">🟠  Alto</option>"),
    ("<option value=\"critical\">🔴  Критичний</option>",
     "<option value=\"critical\">🔴  Crítico</option>"),
    ("<label class=\"swal-label\">Призначити техніку (опційно)</label>",
     "<label class=\"swal-label\">Atribuir a técnico (opcional)</label>"),
    ("<option value=\"\">— Не признаchatи зараз —</option>",
     "<option value=\"\">— Não atribuir agora —</option>"),
    ("confirmButtonText: 'Criar paавку',", "confirmButtonText: 'Criar pedido',"),
    ("confirmButtonText: 'Criar заявку',", "confirmButtonText: 'Criar pedido',"),
    ("Swal.showValidationMessage('Введіть опис проблеми');",
     "Swal.showValidationMessage('Introduza a descrição do problema');"),
    ("throw new Error('Не вдалося створити заявку');",
     "throw new Error('Não foi possível criar o pedido');"),
    ("Swal.fire({ icon: 'success', title: 'Готово!', text: 'Нове призначення criado!', confirmButtonColor: '#28a745', customClass: { popup: 'swal-dispatch' } });",
     "Swal.fire({ icon: 'success', title: 'Feito!', text: 'Nova atribuição criada!', confirmButtonColor: '#28a745', customClass: { popup: 'swal-dispatch' } });"),
    ("// Масове призначення", "// Atribuição em massa"),
    ("<p class=\"text-muted p-2\">Натисніть на заявку щоб вибрати</p>",
     "<p class=\"text-muted p-2\">Clique num pedido para seleccionar</p>"),
    ("// Продовжити дедлайн з модального вікна (закриває модалку споchatку)",
     "// Prolongar prazo da janela modal (fecha modal primeiro)"),
    ("// Reatribuir прострочені", "// Reatribuir atrasados"),
    ("title: '📅 Продовжити дедлайн',", "title: '📅 Prolongar prazo',"),
    ("<p class=\"text-muted small mb-2\">Нова дата = сьогодні + обрана quantidade днів</p>",
     "<p class=\"text-muted small mb-2\">Nova data = hoje + quantidade de dias seleccionada</p>"),

    # ── requests.html specific ────────────────────────────────────────────────
    ("console.error('❌ Помилка створення pedidos:', error);",
     "console.error('❌ Erro ao criar pedido:', error);"),
    ("console.error('Заявку не encontrado:', requestId);",
     "console.error('Pedido não encontrado:', requestId);"),
    ("// ── Tab①: Опис ──", "// ── Tab①: Descrição ──"),
    ("$('#vrmDescription').text(request.description || 'Опис відсутній');",
     "$('#vrmDescription').text(request.description || 'Sem descrição');"),
    ("// ── Tab③: Клієнт ──", "// ── Tab③: Cliente ──"),
    ("timelineEl.html('<p class=\"text-muted\"><i class=\"fas fa-inbox mr-1\"></i>Cronologia відсутня</p>');",
     "timelineEl.html('<p class=\"text-muted\"><i class=\"fas fa-inbox mr-1\"></i>Cronologia indisponível</p>');"),
    ("$('#vrmCompleteBtn').html('<i class=\"fas fa-undo mr-1\"></i>Повернути в роботу').removeClass('btn-primary').addClass('btn-warning').attr('onclick', 'reopenRequest()');",
     "$('#vrmCompleteBtn').html('<i class=\"fas fa-undo mr-1\"></i>Devolver ao trabalho').removeClass('btn-primary').addClass('btn-warning').attr('onclick', 'reopenRequest()');"),
    ("// Mostrar/сховати кнопки архіву залежно від стану pedidos",
     "// Mostrar/ocultar botões de arquivo conforme estado do pedido"),
    ("// Для завершених pedidos показуємо тільки кнопку повернення (тільки для admin)",
     "// Para pedidos concluídos mostrar apenas botão de devolução (só admin)"),
    ("<i class=\"fas fa-check-circle\"></i> Pedido завершена",
     "<i class=\"fas fa-check-circle\"></i> Pedido concluído"),
    ("<i class=\"fas fa-undo\"></i> Повернути в роботу",
     "<i class=\"fas fa-undo\"></i> Devolver ao trabalho"),
    ("// Для активних pedidos показуємо контекстні кнопки",
     "// Para pedidos activos mostrar botões contextuais"),
    ("alert('Pedido не знайдена');", "alert('Pedido não encontrado');"),
    ("// Встановлюємо мінімальну дату (поточна)", "// Definir data mínima (actual)"),
    ("// Заповнюємо форму редагування", "// Preencher formulário de edição"),
    ("// Показуємо модальне вікно", "// Mostrar janela modal"),
    ("// Використовуємо реальний MongoDB _id замість display ID (REQ-001)",
     "// Usar _id real do MongoDB em vez de display ID (REQ-001)"),
    ("throw new Error('ID pedidos не encontrado');",
     "throw new Error('ID do pedido não encontrado');"),
    ("console.log('🔄 Оновлення pedidos:', requestId, updateData);",
     "console.log('🔄 A actualizar pedido:', requestId, updateData);"),
    ("throw new Error(error.message || 'Erro оновлення pedidos');",
     "throw new Error(error.message || 'Erro ao actualizar pedido');"),
    ("alert('Заявку успішно atualizado!');", "alert('Pedido actualizado com sucesso!');"),
    ("// Закриваємо модальне вікно", "// Fechar janela modal"),
    ("// Перезавантажуємо список pedidos", "// Recarregar lista de pedidos"),
    ("console.error('Erro оновлення pedidos:', error);",
     "console.error('Erro ao actualizar pedido:', error);"),
    ("alert('Не вдалося оновити заявку: ' + error.message);",
     "alert('Não foi possível actualizar o pedido: ' + error.message);"),
    ("// Закрити Bootstrap modal перш, тоді відкрити Swal (без конфлікту z-index та backdrop)",
     "// Fechar modal Bootstrap antes de abrir Swal (sem conflito z-index e backdrop)"),
    ("title: '📅 Продовжити дедлайн',", "title: '📅 Prolongar prazo',"),
    ("<p class=\"text-muted small mb-2\">Нова дата = сьогодні + обрана quantidade днів</p>",
     "<p class=\"text-muted small mb-2\">Nova data = hoje + quantidade de dias seleccionada</p>"),
    ("confirmButtonText: 'Prodовжити',", "confirmButtonText: 'Prolongar',"),
    ("confirmButtonText: 'Продовжити',", "confirmButtonText: 'Prolongar',"),
    ("toastr.success(`Дедлайн продовжено на ${days} днів — ${newDeadline.toLocaleDateString('pt-PT')}`);",
     "toastr.success(`Prazo prolongado em ${days} dias — ${newDeadline.toLocaleDateString('pt-PT')}`);"),
    ("toastr.error('Не вдалося оновити дедлайн: ' + (err.message || r?.status || 'помилка сервера'));",
     "toastr.error('Não foi possível actualizar o prazo: ' + (err.message || r?.status || 'erro do servidor'));"),
    ("console.log('🗑️ Видалення pedidos:', requestId);",
     "console.log('🗑️ A eliminar pedido:', requestId);"),
    ("if (!request) { toastr.error('Заявку не encontrado'); return; }",
     "if (!request) { toastr.error('Pedido não encontrado'); return; }"),
    ("title: 'Видалити заявку назавжди?',", "title: 'Eliminar pedido definitivamente?',"),
    ("html: `Заявку <b>#${requestId}</b> буде <b>безповоротно eliminado</b>.<br><small class=\"text-muted\">Розгляньте архівування як безпечнішу альтернативу.</small>`,",
     "html: `O pedido <b>#${requestId}</b> será <b>permanentemente eliminado</b>.<br><small class=\"text-muted\">Considere arquivar como alternativa mais segura.</small>`,"),
    ("confirmButtonText: '<i class=\"fas fa-trash mr-1\"></i>Видалити назавжди',",
     "confirmButtonText: '<i class=\"fas fa-trash mr-1\"></i>Eliminar definitivamente',"),
    ("cancelButtonText: '<i class=\"fas fa-archive mr-1\"></i>Arquivar натомість',",
     "cancelButtonText: '<i class=\"fas fa-archive mr-1\"></i>Arquivar em vez disso',"),
    ("// Якщо натиснули \"Arquivar натомість\"", "// Se clicou em \"Arquivar em vez disso\""),
    ("if (!mongoId) throw new Error('Відсутній MongoDB ID pedidos');",
     "if (!mongoId) throw new Error('MongoDB ID do pedido em falta');"),
    ("throw new Error(error.message || 'Erro видалення через API');",
     "throw new Error(error.message || 'Erro ao eliminar via API');"),
    ("console.error('❌ Помилка видалення pedidos:', error);",
     "console.error('❌ Erro ao eliminar pedido:', error);"),
    ("toastr.error('Не вдалося видалити: ' + error.message);",
     "toastr.error('Não foi possível eliminar: ' + error.message);"),
    ("console.log('📦 Архівування pedidos:', requestId);",
     "console.log('📦 A arquivar pedido:', requestId);"),
    ("title: 'Arquivar заявку?',", "title: 'Arquivar pedido?',"),
    ("html: `Заявку <b>#${requestId}</b> буде переміщено до архіву.<br>Ви зможете restaurar її будь-коли.`,",
     "html: `O pedido <b>#${requestId}</b> será movido para o arquivo.<br>Poderá restaurá-lo a qualquer momento.`,"),
    ("throw new Error('Відсутній MongoDB ID pedidos');",
     "throw new Error('MongoDB ID do pedido em falta');"),
    ("throw new Error((data && data.message) || 'Erro архівування');",
     "throw new Error((data && data.message) || 'Erro ao arquivar');"),
    ("console.error('❌ Помилка архівування:', error);",
     "console.error('❌ Erro ao arquivar:', error);"),
    ("toastr.error('Не вдалося arquivar: ' + error.message);",
     "toastr.error('Não foi possível arquivar: ' + error.message);"),
    ("if (!this.currentRequest) { toastr.error('Заявку не aberto'); return; }",
     "if (!this.currentRequest) { toastr.error('Nenhum pedido aberto'); return; }"),
    ("// Перемикання режиму перегляду архіву (адмін)",
     "// Alternar modo de visualização do arquivo (admin)"),
    ("// Restaurar заявку з архіву (тільки адмін)",
     "// Restaurar pedido do arquivo (só admin)"),
    ("if (!request) { toastr.error('Заявку не aberto'); return; }",
     "if (!request) { toastr.error('Nenhum pedido aberto'); return; }"),
    ("title: 'Restaurar заявку?',", "title: 'Restaurar pedido?',"),
    ("text: 'Заявку буде повернуто до активних.',",
     "text: 'O pedido será devolvido aos activos.',"),
    ("Swal.fire({ icon: 'success', title: 'Відновлено!', text: 'Заявку повернуто до активних.', timer: 1800, showConfirmButton: false });",
     "Swal.fire({ icon: 'success', title: 'Restaurado!', text: 'Pedido devolvido aos activos.', timer: 1800, showConfirmButton: false });"),
    ("console.error('❌ Помилка recuperação:', error);",
     "console.error('❌ Erro ao restaurar:', error);"),
    ("toastr.error('Não вдалося restaurar: ' + error.message);",
     "toastr.error('Não foi possível restaurar: ' + error.message);"),
    ("html: `Заявку <b>${displayId}</b> буде позначено як фальшивий виклик та fechado.`,",
     "html: `O pedido <b>${displayId}</b> será marcado como falsa chamada e fechado.`,"),
    ("Swal.fire({ icon: 'success', title: 'Відмічено', text: data.message || 'Pedido позначена як фальшивий виклик', timer: 1800, showConfirmButton: false });",
     "Swal.fire({ icon: 'success', title: 'Marcado', text: data.message || 'Pedido marcado como falsa chamada', timer: 1800, showConfirmButton: false });"),
    ("console.error('❌ Помилка фальшивий виклик:', error);",
     "console.error('❌ Erro falsa chamada:', error);"),
    ("toastr.error('Не вдалося: ' + error.message);",
     "toastr.error('Não foi possível: ' + error.message);"),
    ("console.log('🔍 Застосування фільтрів...');",
     "console.log('🔍 A aplicar filtros...');"),
    ("console.warn('⚠️ Dados pedidos ще не завантажені');",
     "console.warn('⚠️ Dados de pedidos ainda não carregados');"),
    ("// Якщо всі filtros порожні - показуємо все",
     "// Se todos os filtros estão vazios - mostrar tudo"),
    ("console.log('✅ Filtros очищені - показуємо всі pedidos');",
     "console.log('✅ Filtros limpos - a mostrar todos os pedidos');"),
    ("// Filtroуємо pedidos", "// Filtrar pedidos"),
    ("// Filtro по техніку - перевіряємо technicianId або technician",
     "// Filtro por técnico - verificar technicianId ou technician"),
    ("console.log(`✅ Encontrado pedidos: ${filtered.length} з ${allRequests.length}`);",
     "console.log(`✅ Pedidos encontrados: ${filtered.length} de ${allRequests.length}`);"),
    ("// Тимчасово замінюємо requests на відфільтровані",
     "// Substituir temporariamente requests pelos filtrados"),
    ("console.log('✏️ Редагування pedidos:', requestId);",
     "console.log('✏️ A editar pedido:', requestId);"),
    ("// Завантажуємо заявку з API", "// Carregar pedido da API"),
    ("throw new Error('Не вдалося descarregar заявку');",
     "throw new Error('Não foi possível carregar o pedido');"),
    ("// Заповнюємо форму редагування", "// Preencher formulário de edição"),
    ("// Відкриваємо модальне вікно", "// Abrir janela modal"),
    ("throw new Error('Заявку не encontrado');",
     "throw new Error('Pedido não encontrado');"),
    ("toastr.error('Не вдалося descarregar заявку: ' + error.message);",
     "toastr.error('Não foi possível carregar o pedido: ' + error.message);"),
    ("throw new Error('Не вдалося оновити заявку');",
     "throw new Error('Não foi possível actualizar o pedido');"),
    ("// Закриваємо модальне вікно", "// Fechar janela modal"),
    ("// Перезавантажуємо список", "// Recarregar lista"),
    ("toastr.success('Заявку успішно atualizado');",
     "toastr.success('Pedido actualizado com sucesso');"),
    ("console.error('❌ Помилка оновлення pedidos:', error);",
     "console.error('❌ Erro ao actualizar pedido:', error);"),
    ("toastr.error('Не вдалося оновити заявку: ' + error.message);",
     "toastr.error('Não foi possível actualizar o pedido: ' + error.message);"),
    ("// Export функції", "// Funções de exportação"),
    ("throw new Error('Не авторизовано');", "throw new Error('Não autorizado');"),
    ("throw new Error('Erro експорту');", "throw new Error('Erro de exportação');"),
    ("console.error('Erro експорту:', error);",
     "console.error('Erro de exportação:', error);"),
    ("toastr.error('Erro експорту: ' + error.message);",
     "toastr.error('Erro de exportação: ' + error.message);"),
    ("throw new Error('Erro експорту PDF');", "throw new Error('Erro de exportação PDF');"),
    ("toastr.success('PDF експортовано');", "toastr.success('PDF exportado');"),
    ("console.error('Erro експорту PDF:', error);",
     "console.error('Erro de exportação PDF:', error);"),
    ("toastr.error('Erro експорту PDF: ' + error.message);",
     "toastr.error('Erro de exportação PDF: ' + error.message);"),
    ("// Глобальні функції", "// Funções globais"),
    ("// Завантажуємо список ліфтів перед показом модалки",
     "// Carregar lista de elevadores antes de mostrar modal"),
    ("// Встановлюємо мінімальну дату (поточна)", "// Definir data mínima (actual)"),
    ("// Просто відкриваємо модальне вікно - ліфти вже завантажені в openNewRequestModal",
     "// Apenas abrir janela modal - elevadores já carregados em openNewRequestModal"),
    ("toastr.success('Pedidos експортовано!');", "toastr.success('Pedidos exportados!');"),
    ("// Функції для роботи з pedidoми", "// Funções para trabalhar com pedidos"),
    ("// Verificação наявності AuthManager", "// Verificar disponibilidade de AuthManager"),
    ("// Детальне логування для діагностики", "// Registo detalhado para diagnóstico"),
    ("console.log('🔍 Verificação авторизації...');",
     "console.log('🔍 A verificar autorização...');"),
    ("// Verificação авторизації", "// Verificação de autorização"),
    ("// Verificação чи pedido не завершена", "// Verificar se pedido não está concluído"),
    ("alert('Неможливо призначити техніка.\\nЦя pedido вже завершена.\\n\\nЯкщо necessário внести зміни, споchatку поверніть заявку в роботу.');",
     "alert('Não é possível atribuir técnico.\\nEste pedido já está concluído.\\n\\nSe necessário fazer alterações, devolva primeiro o pedido ao trabalho.');"),
    ("alert('У вас немає прав для призначення техніків');",
     "alert('Não tem permissão para atribuir técnicos');"),
    ("// Показуємо модальне вікно призначення техніка",
     "// Mostrar janela modal de atribuição de técnico"),
    ("// Verificação чи pedido не завершена",
     "// Verificar se pedido não está concluído"),
    ("alert('Неможливо змінити статус.\\nЦя pedido вже завершена.\\n\\nЯкщо necessário внести зміни, споchatку поверніть заявку в роботу.');",
     "alert('Não é possível alterar estado.\\nEste pedido já está concluído.\\n\\nSe necessário fazer alterações, devolva primeiro o pedido ao trabalho.');"),
    ("// Використовуємо MongoDB _id, а не красивий ID",
     "// Usar _id real do MongoDB em vez de display ID"),
    ("console.log(`Зміна статусу pedidos ${requestId} на ${newStatus}`);",
     "console.log(`A alterar estado do pedido ${requestId} para ${newStatus}`);"),
    ("let errorMessage = 'Erro зміни статусу';",
     "let errorMessage = 'Erro ao alterar estado';"),
    ("// Якщо відповідь не JSON (наприклад HTML 404)",
     "// Se resposta não é JSON (ex.: HTML 404)"),
    ("errorMessage = `Помилка сервера (${response.status})`;",
     "errorMessage = `Erro do servidor (${response.status})`;"),
    ("console.log('Статус змінено:', result);", "console.log('Estado alterado:', result);"),
    ("alert('Статус pedidos успішно змінено!');",
     "alert('Estado do pedido alterado com sucesso!');"),
    ("// Закриваємо модальне вікно", "// Fechar janela modal"),
    ("// Перезавантажуємо список pedidos", "// Recarregar lista de pedidos"),
    ("console.error('Erro зміни статусу:', error);",
     "console.error('Erro ao alterar estado:', error);"),
    ("alert('Не вдалося змінити статус: ' + error.message);",
     "alert('Não foi possível alterar o estado: ' + error.message);"),
    ("alert('Потрібна autorização');", "alert('Autorização necessária');"),
    ("const workDescription = prompt('Введіть опис concluídoї роботи:');",
     "const workDescription = prompt('Introduza a descrição do trabalho concluído:');"),
    ("alert('Опис concluídoї роботи обов\\'язковий');",
     "alert('A descrição do trabalho concluído é obrigatória');"),
    ("throw new Error(errBody.message || (response ? `Помилка ${response.status}` : 'Erro авторизації'));",
     "throw new Error(errBody.message || (response ? `Erro ${response.status}` : 'Erro de autorização'));"),
    ("alert('Заявку concluído успішно!');", "alert('Pedido concluído com sucesso!');"),
    ("console.error('Erro завершення:', error);",
     "console.error('Erro ao concluir:', error);"),
    ("alert('Não вдалося завершити заявку: ' + error.message);",
     "alert('Não foi possível concluir o pedido: ' + error.message);"),
    ("alert('Введіть текст коментаря');", "alert('Introduza o texto do comentário');"),
    ("alert('Не вибрана pedido');", "alert('Nenhum pedido seleccionado');"),
    ("throw new Error('Erro додавання коментаря');",
     "throw new Error('Erro ao adicionar comentário');"),
    ("alert('Comentário додано успішно');", "alert('Comentário adicionado com sucesso');"),
    ("alert('Erro додавання коментаря: ' + error.message);",
     "alert('Erro ao adicionar comentário: ' + error.message);"),
    ("// Verificação ролі - тільки admin може повертати в роботу",
     "// Verificar papel - só admin pode devolver ao trabalho"),
    ("alert('Тільки адміністратор може повертати завершені pedidos в роботу');",
     "alert('Apenas o administrador pode devolver pedidos concluídos ao trabalho');"),
    ("if (!confirm('Tem a certeza que quer повернути цю заявку в роботу?\\n\\nPedido отримає статус \"Em progresso\" і її можна буде редагувати.')) {",
     "if (!confirm('Tem a certeza que quer devolver este pedido ao trabalho?\\n\\nO pedido receberá o estado \"Em progresso\" e poderá ser editado.')) {"),
    ("throw new Error('ID pedidos не encontrado');",
     "throw new Error('ID do pedido não encontrado');"),
    ("console.log(`Повернення pedidos ${requestId} в роботу`);",
     "console.log(`A devolver pedido ${requestId} ao trabalho`);"),
    ("alert('Заявку повернуто в роботу!');", "alert('Pedido devolvido ao trabalho!');"),
    ("// Закриваємо модальне вікно", "// Fechar janela modal"),
    ("// Перезавантажуємо список pedidos", "// Recarregar lista de pedidos"),
    ("alert('Не вдалося повернути заявку в роботу: ' + error.message);",
     "alert('Não foi possível devolver o pedido ao trabalho: ' + error.message);"),
    ("if (!requestId) { toastr.warning('Не вдалося визначити заявку'); return; }",
     "if (!requestId) { toastr.warning('Não foi possível identificar o pedido'); return; }"),
    ("toastr.error('Потрібна autorização');", "toastr.error('Autorização necessária');"),
    ("if (!resp || !resp.ok) throw new Error('Не вдалося descarregar список техніків');",
     "if (!resp || !resp.ok) throw new Error('Não foi possível carregar lista de técnicos');"),
    ("toastr.warning('Техніків не encontrado в системі.');",
     "toastr.warning('Técnicos não encontrados no sistema.');"),
    ("<label class=\"custom-control-label small\" for=\"eaNotifyPush\">Push техніку</label>",
     "<label class=\"custom-control-label small\" for=\"eaNotifyPush\">Push ao técnico</label>"),
    ("<label class=\"custom-control-label small\" for=\"eaNotifyEmail\">Email техніку</label>",
     "<label class=\"custom-control-label small\" for=\"eaNotifyEmail\">Email ao técnico</label>"),
    ("<label class=\"custom-control-label small\" for=\"eaNotifyClient\">Сповістити клієнта</label>",
     "<label class=\"custom-control-label small\" for=\"eaNotifyClient\">Notificar cliente</label>"),
    ("toastr.error('Erro завантаження техніків: ' + error.message);",
     "toastr.error('Erro ao carregar técnicos: ' + error.message);"),
    ("if (!techId) { toastr.warning('Seleccione техніка'); return; }",
     "if (!techId) { toastr.warning('Seleccione o técnico'); return; }"),
    ("throw new Error(err.message || 'Erro призначення');",
     "throw new Error(err.message || 'Erro de atribuição');"),
    ("toastr.success('Técника призначено! Notificações enviado.');",
     "toastr.success('Técnico atribuído! Notificações enviadas.');"),
    ("toastr.success('Técnica призначено! Notificações enviado.');",
     "toastr.success('Técnico atribuído! Notificações enviadas.');"),
    ("toastr.success('Техніка призначено! Notificações enviado.');",
     "toastr.success('Técnico atribuído! Notificações enviadas.');"),
    ("alert('Seleccione техніка');", "alert('Seleccione o técnico');"),
    ("alert('Не вибрана pedido для призначення');",
     "alert('Nenhum pedido seleccionado para atribuição');"),
    ("// Використовуємо MongoDB _id, а не красивий ID",
     "// Usar _id real do MongoDB em vez de display ID"),
    ("console.log(`Atribuições техніка ${selectedTechnician} до pedidos ${requestId}`);",
     "console.log(`A atribuir técnico ${selectedTechnician} ao pedido ${requestId}`);"),
    ("throw new Error(error.message || 'Erro призначення техніка');",
     "throw new Error(error.message || 'Erro ao atribuir técnico');"),
    ("// Закриваємо модальні вікна", "// Fechar janelas modais"),
    ("// Mensagem про успіх", "// Mensagem de sucesso"),
    ("alert('Техніка успішно призначено!');", "alert('Técnico atribuído com sucesso!');"),
    ("// Перезавантажуємо дані pedidos", "// Recarregar dados do pedido"),
    ("alert('Erro призначення техніка: ' + error.message);",
     "alert('Erro ao atribuir técnico: ' + error.message);"),
    ("// TODO: Логіка для отримання ID поточно selecionadoї pedidos",
     "// TODO: Lógica para obter ID do pedido actualmente seleccionado"),
    ("// Це може бути guardado в глобальній змінній або recebido з UI",
     "// Pode estar guardado em variável global ou recebido da UI"),
    ("// 🆕 Функції для роботи з коментарями",
     "// 🆕 Funções para trabalhar com comentários"),
    ("<i class=\"fas fa-inbox\"></i> Comentáriosв поки немає",
     "<i class=\"fas fa-inbox\"></i> Ainda sem comentários"),
    ("const username = comment.user?.username || comment.user?.firstName || 'Користувач';",
     "const username = comment.user?.username || comment.user?.firstName || 'Utilizador';"),
    ("// Функція оновлення списку pedidos", "// Função de actualização da lista de pedidos"),
    ("toastr.success('Список pedidos atualizado');",
     "toastr.success('Lista de pedidos actualizada');"),
    ("// A carregar техніків у фільтр", "// Carregar técnicos no filtro"),
    ("select.find('option:not(:first)').remove(); // Видаляємо всі крім \"Всі техніки\"",
     "select.find('option:not(:first)').remove(); // Remover todas excepto \"Todos os técnicos\""),
    ("console.log(`✅ Завантажено техніків у фільтр: ${technicians.length}`);",
     "console.log(`✅ Técnicos carregados no filtro: ${technicians.length}`);"),
    ("console.error('❌ Erro ao carregar техніків:', error);",
     "console.error('❌ Erro ao carregar técnicos:', error);"),
    ("// Ініціалізація", "// Inicialização"),
    ("console.log('🚀 Запуск системи pedidos на обслуговування...');",
     "console.log('🚀 A iniciar sistema de pedidos de assistência...');"),
    ("// Виправлення aria-hidden warning: прибирати фокус перед закриттям будь-якого модалу",
     "// Correcção aria-hidden warning: remover foco antes de fechar qualquer modal"),
    ("// М'яка verificação завантаження AuthManager з затримкою",
     "// Verificação suave do carregamento de AuthManager com atraso"),
    ("console.error('❌ AuthManager не завантажено після затримки!');",
     "console.error('❌ AuthManager não carregado após atraso!');"),
    ("console.log('✅ AuthManager завантажено');",
     "console.log('✅ AuthManager carregado');"),
    ("// Завантажуємо техніків у фільтр", "// Carregar técnicos no filtro"),
    ("// Ініціалізуємо serviceManager в будь-якому випадку",
     "// Inicializar serviceManager em qualquer caso"),
    ("// ✅ ДОДАНО: Обробник пошуку pedidos",
     "// ✅ ADICIONADO: Handler de pesquisa de pedidos"),
    ("console.warn('⚠️ Dados pedidos ще не завантажені');",
     "console.warn('⚠️ Dados de pedidos ainda não carregados');"),
    ("// Mostrar всі pedidos", "// Mostrar todos os pedidos"),
    ("// Filtroуємо pedidos", "// Filtrar pedidos"),
    ("console.log(`✅ Encontrado pedidos: ${filtered.length} з ${allRequests.length}`);",
     "console.log(`✅ Pedidos encontrados: ${filtered.length} de ${allRequests.length}`);"),
    ("// Тимчасово замінюємо requests на відфільтровані",
     "// Substituir temporariamente requests pelos filtrados"),
    ("window.serviceManager.requests = originalRequests; // Повертаємо назад",
     "window.serviceManager.requests = originalRequests; // Devolver"),
    ("// Toastr налаштування", "// Configurações Toastr"),

    # ── Mostrar авансado (typo variant) ───────────────────────────────────────
    ("// Mostrar авансado модал призначення техніка (як в адмін панелі)",
     "// Mostrar modal avançado de atribuição de técnico (como no painel admin)"),
]

# Deduplicate
seen = set()
DEDUP = []
for pair in TRANSLATIONS:
    if pair[0] not in seen and pair[0] != pair[1]:
        seen.add(pair[0])
        DEDUP.append(pair)

def process_file(path):
    txt = path.read_text(encoding='utf-8')
    original = txt
    for old, new in DEDUP:
        if old in txt:
            txt = txt.replace(old, new)
    if txt != original:
        path.write_text(txt, encoding='utf-8')
        return True
    return False

base = __import__('pathlib').Path('/workspaces/deapseak/pages')
for panel in ['admin', 'dispatcher', 'tech']:
    changed = skipped = 0
    for f in sorted((base / panel).glob('*.html')):
        if process_file(f):
            changed += 1
        else:
            skipped += 1
    print(f'{panel}: {changed} files updated, {skipped} unchanged')
print('Done.')
