#!/usr/bin/env python3
# Третій прохід - виправлення зламаних перекладів + залишки UI

import glob

FIXES = [
    # === Виправлення зламаних перекладів ===
    # 'таб' → 'separador' помилково замінив частини слів:
    ('сseparadorільність', 'estabilidade'),
    ('сseparadorільний', 'estável'),
    ('сseparadorільній', 'estável'),
    ('сseparadorільно', 'estavelmente'),
    ('неseparadorільний', 'instável'),
    ('неseparadorільність', 'instabilidade'),
    ('чисeparadorьний', 'numérico'),
    ('чиseparadorельний', 'significativo'),
    ('budseparadorет', 'orçamento'),
    # 'час' → 'hora' помилково замінив частини слів 'тимчасов*':
    ('тимhoraово', 'temporariamente'),
    ('тимhoraовий', 'temporário'),
    ('тимhoraова', 'temporária'),
    ('тимhoraового', 'temporário'),
    ('тимhoraове', 'temporário'),
    ('тимhoraових', 'temporários'),
    # Fix 'Período:' from label tag
    ('Período:', 'Período:'),
    # Fix specific analytics lines
    ('Financeira сseparadorільність', 'Estabilidade financeira'),
    ('Рекомendações', 'Recomendações'),

    # === Залишки UI з pass 2 ===
    # Analytics
    ('Рекомендуexisteться найняти додаткового do técnico para покриття пікового навантаження',
     'Recomenda-se contratar um técnico adicional para cobrir o pico de carga'),
    ('Planeado 12 планових Manutenção na seguinte місяць',
     'Planeadas 12 manutenções para o próximo mês'),
    ('Planeado 12 планових Manutenção на seguinte місяць',
     'Planeadas 12 manutenções para o próximo mês'),
    ('Рекомендуexisteться', 'Recomenda-se'),
    ('рекомендуexisteться', 'recomenda-se'),
    ('існуexiste', 'existe'),
    ('isnuexiste', 'existe'),

    # Audit log
    ('Користувач', 'Utilizador'),

    # Import checklists
    ('Lista de verificaçãoи com sucesso імпортовано!', 'Listas de verificação importadas com sucesso!'),
    ('Erro імпорту: ', 'Erro de importação: '),
    ('пунктів', 'itens'),
    ('пункт', 'item'),

    # Admin lifts remaining
    ('Obrigatório · QR gerado automaticamente на сторінці', 'Obrigatório · QR gerado automaticamente na página'),
    ('na сторінці', 'na página'),
    ('на сторінці', 'na página'),
    ('на сторінку', 'para a página'),
    ('на сторінці входу', 'na página de login'),
    ('Cliqueь к', 'Clique em'),
    ('Clique para', 'Clique para'),
    ('Sem relatórios. Clique em', 'Sem relatórios. Clique em'),
    ('ID do elevador не encontrado', 'ID do elevador não encontrado'),
    ('${siblings.length} elevadора', '${siblings.length} elevadores'),
    ('Pode alterar', 'Pode alterar'),
    ('Pode-se alterar', 'Pode alterar'),

    # Admin login
    ('Ви seráте перенаправлені на сторінку входу...', 'Será redirecionado para a página de login...'),
    ('Se це не сталося автоматично, натисніть aqui', 'Se não aconteceu automaticamente, clique aqui'),

    # Maps
    ('Переглянути detalhes', 'Ver detalhes'),
    ('Активних', 'Ativos'),
    ('З несправностями', 'Com avarias'),
    ('Filtro за estadoом:', 'Filtro por estado:'),
    ('Endereço, número, кліexisteнт...', 'Endereço, número, cliente...'),
    ('Прокласти rota до do elevador:', 'Traçar rota para o elevador:'),
    ('Прокласти rota', 'Traçar rota'),
    ('Виправляexiste coordenadas de elevadores, що показуються в неправильному місці',
     'Corrigir coordenadas de elevadores que aparecem no local errado'),
    ('Виправити coordenadas (Re-geocode)', 'Corrigir coordenadas (Re-geocode)'),
    ('Використовуйте se elevadores відображаються в неправильному місці',
     'Use quando os elevadores aparecem no local errado'),
    ('Клікніть на мапі куди перемістити elevador:', 'Clique no mapa para onde mover o elevador:'),
    ('Mapa тимhoraово недоступна', 'Mapa temporariamente indisponível'),
    ('Mapa тимhoraово н', 'Mapa temporariamente in'),
    ('Alterar позицію маркера', 'Alterar posição do marcador'),
    ('Alterar місце', 'Alterar localização'),
    ('Маркер não encontrado', 'Marcador não encontrado'),
    ('Позицію do elevador guardado!', 'Posição do elevador guardada!'),
    ('Erro збереження: ', 'Erro ao guardar: '),
    ("Erro z'existeднання: ", 'Erro de ligação: '),
    ("Erro z'existeднання:", 'Erro de ligação:'),
    ("existeднання", 'ligação'),
    ('Будуexisteться...', 'A construir...'),
    ('Виправлення...', 'A corrigir...'),
    ('Geocodificação concluído!\nВиправлено: ', 'Geocodificação concluída!\nCorrigidos: '),
    ('Виправлено: ', 'Corrigidos: '),
    ('Помилок: ', 'Erros: '),
    ('Total оброблено: ', 'Total processados: '),
    ('Err запиту: ', 'Erro de pedido: '),
    ('Seleccione elevador para прокладання rotaу', 'Selecione um elevador para traçar a rota'),
    ('ПОПЕРЕДЖЕННЯ', 'AVISO'),
    ('Відстань до do elevador: ', 'Distância ao elevador: '),
    ('Це занадто мало. Можливо:', 'É muito pouco. Possivelmente:'),
    ('Não foi possível побудувати rota. Можливо, endereço занадто д', 'Não foi possível traçar a rota. Possivelmente, o endereço é demasiado d'),

    # Notifications
    ('Прочитані', 'Lidas'),
    ('Системні', 'Do sistema'),
    ('Користувацькі', 'Do utilizador'),
    ('Período:', 'Período:'),

    # AI diagnostics
    ('AI скриптів', 'AI scripts'),
    ('Перевіряємо завантажені скрипти', 'A verificar scripts carregados'),
    ('Перевіряємо acessoність класів', 'A verificar acessibilidade das classes'),
    ('Знайдено', 'Encontrado'),
    ('Можна створити екземпляр', 'É possível criar uma instância de'),
    ('Метод ', 'Método '),
    ('відсутній', 'ausente'),
    ('відсутня', 'ausente'),
    ('Err створення екземпляра:', 'Erro ao criar instância:'),
    ('НЕ ЗНАЙДЕНО', 'NÃO ENCONTRADO'),
    ('ЗНАЙДЕНО', 'ENCONTRADO'),
    ('Функція ', 'Função '),
    ('Testeуємо ініціалізацію до sistema...', 'A testar a inicialização do sistema...'),
    ('Testeуємо ініціалізацію do sistema...', 'A testar a inicialização do sistema...'),
    ('Викликаємо initPredictiveAnalytics()...', 'A chamar initPredictiveAnalytics()...'),
    ('Resultado ініціалізації:', 'Resultado da inicialização:'),
    ('initPredictiveAnalytics não encontrado', 'initPredictiveAnalytics não encontrado'),
    ('Створюємо testeовий екземпляр do sistema...', 'A criar instância de teste do sistema...'),
    ('Testeовий екземпляр criado', 'Instância de teste criada'),
    ('Err ініціалізації:', 'Erro de inicialização:'),
    ('Testeуємо створення gráficoа...', 'A testar a criação do gráfico...'),
    ('Canvas не encontrado', 'Canvas não encontrado'),
    ('Err створення gráficoа:', 'Erro ao criar gráfico:'),
    ('Завантажуємо testeові AI recomendações...', 'A carregar recomendações de IA de teste...'),
    ('Контейнер recomendações não encontrado', 'O contêiner de recomendações não foi encontrado'),
    ('Контейнер рекомендацій não encontrado', 'O contêiner de recomendações não foi encontrado'),
    ('Чудово: Elevadores ', 'Ótimo: Elevadores '),
    ('працюють оптимально', 'a funcionar de forma ótima'),
    ('Симулюємо роботу оригінальної сторінки...', 'A simular o funcionamento da página original...'),
    ('Симулюємо hash:', 'A simular hash:'),
    ('Hash збігається, активуємо AI таб', 'Hash coincide, a ativar separador de IA'),
    ('Викликаємо activateAIPredictive()...', 'A chamar activateAIPredictive()...'),
    ('Resultado активації:', 'Resultado da ativação:'),
    ('Err активації:', 'Erro de ativação:'),
    ('activateAIPredictive não encontrado', 'activateAIPredictive não encontrado'),
    ('Діагностика розпоchatа автоматично...', 'Diagnóstico iniciado automaticamente...'),

    # Remaining common Ukrainian visible words
    ('тимчасовий', 'temporário'),
    ('тимчасова', 'temporária'),
    ('тимчасово', 'temporariamente'),
    ('тимчасового', 'temporário'),
    ('стабільність', 'estabilidade'),
    ('стабільний', 'estável'),
    ('стабільна', 'estável'),
    ('нестабільний', 'instável'),
    ('нестабільність', 'instabilidade'),
    ('нестабільна', 'instável'),
    ('частково', 'parcialmente'),
    ('часто', 'frequentemente'),
    ('тикетів', 'tickets'),
    ('тикета', 'ticket'),
    ('місяць', 'mês'),
    ('місяця', 'do mês'),
    ('місяців', 'de meses'),
    ('тижня', 'da semana'),
    ('тиждень', 'semana'),
    ('тижнів', 'semanas'),
    ('рік', 'ano'),
    ('року', 'do ano'),
    ('роки', 'anos'),
    ('роки', 'anos'),
    ('день', 'dia'),
    ('дні', 'dias'),
    ('днів', 'dias'),
    ('дня', 'do dia'),
    ('хвилин', 'minutos'),
    ('хвилини', 'minutos'),
    ('годин', 'horas'),
    ('години', 'horas'),
    ('адміна', 'do administrador'),
    ('адмін', 'administrador'),
    ('адміністратора', 'do administrador'),
    ('адміністратору', 'ao administrador'),
    ('адміністраторів', 'de administradores'),
    ('диспетчеру', 'ao dispatcher'),
    ('диспетчерів', 'dispatchers'),
    ('диспетчера', 'do dispatcher'),
    ('клієнту', 'ao cliente'),
    ('клієнтів', 'de clientes'),
    ('клієнта', 'do cliente'),
    ('технікам', 'aos técnicos'),
    ('техніку', 'ao técnico'),
    ('техніків', 'de técnicos'),
    ('техніка', 'do técnico'),

    # Specific remaining strings
    ('Período:', 'Período:'),
    ('сторінки', 'da página'),
    ('сторінку', 'a página'),
    ('сторінці', 'na página'),
    ('сторінок', 'de páginas'),
    ('сторінка', 'página'),
    ('Сторінка', 'Página'),
    ('натисніть', 'clique em'),
    ('Натисніть', 'Clique em'),
    ('натискаючи', 'clicando'),
    ('перевірте', 'verifique'),
    ('Перевірте', 'Verifique'),
    ('підтверджено', 'confirmado'),
    ('підтверджую', 'confirmo'),
    ('підтверджуємо', 'confirmamos'),
    ('перейдіть', 'vá para'),
    ('Перейдіть', 'Vá para'),
    ('введіть', 'introduza'),
    ('Введіть', 'Introduza'),
    ('виберіть', 'selecione'),
    ('Виберіть', 'Selecione'),
    ('запишіть', 'escreva'),
    ('зверніться', 'contacte'),
    ('заповніть', 'preencha'),
    ('Заповніть', 'Preencha'),
    ('підключіться', 'ligue-se'),
    ('оновіть', 'atualize'),
    ('Оновіть', 'Atualize'),
    ('перезавантажте', 'recarregue'),
    ('Перезавантажте', 'Recarregue'),
    ('спробуйте', 'tente'),
    ('Спробуйте', 'Tente'),
    ('повторіть', 'repita'),
    ('Повторіть', 'Repita'),
    ('завантажте', 'carregue'),
    ('інспекторату', 'do inspetorado'),
    ('муніципалітету', 'do município'),
    ('муніципалітет', 'município'),
    ('муніципальний', 'municipal'),
    ('муніципальна', 'municipal'),
    ('реєстрації', 'do registo'),
    ('реєстрацію', 'o registo'),
    ('реєстрація', 'registo'),
    ('Реєстрація', 'Registo'),
    ('Реєстрацію', 'O registo'),
    ('законодавства', 'da legislação'),
    ('законодавство', 'legislação'),
    ('технічного', 'técnico'),
    ('технічних', 'técnicos'),
    ('технічна', 'técnica'),
    ('технічний', 'técnico'),
    ('технічні', 'técnicos'),
    ('технічно', 'tecnicamente'),
    ('обслуговування', 'de manutenção'),
    ('обслуговувати', 'manter'),
    ('обслуговування', 'manutenção'),
    ('обслуговує', 'mantém'),
    ('підрозділу', 'da unidade'),
    ('підрозділ', 'unidade'),
    ('Підрозділ', 'Unidade'),
    ('повідомлення', 'mensagem'),
    ('Повідомлення', 'Mensagem'),
    ('повідомлення', 'mensagens'),
    ('повідомити', 'notificar'),
    ('Повідомити', 'Notificar'),
    ('призначено', 'atribuído'),
    ('призначений', 'atribuído'),
    ('призначена', 'atribuída'),
    ('призначених', 'atribuídos'),
    ('перевірка', 'verificação'),
    ('Перевірка', 'Verificação'),
    ('перевірки', 'de verificação'),
    ('проводити', 'realizar'),
    ('проводиться', 'realiza-se'),
    ('проведення', 'realização'),
    ('проведено', 'realizado'),
    ('список', 'lista'),
    ('Список', 'Lista'),
    ('списку', 'da lista'),
    ('списком', 'lista'),
    ('нотатки', 'notas'),
    ('нотаток', 'notas'),
    ('нотатку', 'nota'),
    ('нотатка', 'nota'),
    ('поточний', 'atual'),
    ('поточна', 'atual'),
    ('поточних', 'atuais'),
    ('поточне', 'atual'),
    ('поточно', 'atualmente'),
    ('зміни', 'alterações'),
    ('зміну', 'alteração'),
    ('зміна', 'alteração'),
    ('змінити', 'alterar'),
    ('Змінити', 'Alterar'),
    ('змінено', 'alterado'),
    ('Змінено', 'Alterado'),
    ('кількість', 'quantidade'),
    ('Кількість', 'Quantidade'),
    ('кількості', 'de quantidade'),
    ('значення', 'valor'),
    ('Значення', 'Valor'),
    ('значень', 'de valores'),
    ('вміст', 'conteúdo'),
    ('Вміст', 'Conteúdo'),
    ('результат', 'resultado'),
    ('Результат', 'Resultado'),
    ('результату', 'do resultado'),
    ('результатів', 'de resultados'),
    ('результати', 'resultados'),
    ('ідентифікатор', 'identificador'),
    ('Ідентифікатор', 'Identificador'),
    ('коментар', 'comentário'),
    ('Коментар', 'Comentário'),
    ('коментарі', 'comentários'),
    ('коментарів', 'de comentários'),
    ('коментаря', 'do comentário'),
    ('підтверджений', 'confirmado'),
    ('підтверджена', 'confirmada'),
    ('підтверджений', 'confirmado'),
    ('відхилений', 'rejeitado'),
    ('відхилена', 'rejeitada'),
    ('відхилено', 'rejeitado'),
    ('відхилити', 'rejeitar'),
    ('Відхилити', 'Rejeitar'),
    ('схвалений', 'aprovado'),
    ('схвалена', 'aprovada'),
    ('схвалено', 'aprovado'),
    ('схвалити', 'aprovar'),
    ('Схвалити', 'Aprovar'),
    ('виконано', 'concluído'),
    ('виконаний', 'concluído'),
    ('виконана', 'concluída'),
    ('виконати', 'executar'),
    ('виконання', 'execução'),
    ('виконати', 'executar'),
    ('запит', 'pedido'),
    ('Запит', 'Pedido'),
    ('запиту', 'do pedido'),
    ('запити', 'pedidos'),
    ('запитів', 'de pedidos'),
    ('замовлення', 'pedido'),
    ('замовлень', 'de pedidos'),
    ('замовити', 'encomendar'),
    ('скаргу', 'reclamação'),
    ('скарга', 'reclamação'),
    ('скарги', 'reclamações'),
    ('оцінку', 'avaliação'),
    ('оцінка', 'avaliação'),
    ('оцінки', 'avaliações'),
    ('лічильник', 'contador'),
    ('Лічильник', 'Contador'),
    ('відображається', 'é exibido'),
    ('відображаються', 'são exibidos'),
    ('відображатися', 'ser exibido'),
    ('показується', 'é mostrado'),
    ('показуються', 'são mostrados'),
    ('показати', 'mostrar'),
    ('Показати', 'Mostrar'),
    ('приховати', 'ocultar'),
    ('Приховати', 'Ocultar'),
    ('прихований', 'oculto'),
    ('прихована', 'oculta'),
    ('приховано', 'oculto'),
    ('відкрити', 'abrir'),
    ('Відкрити', 'Abrir'),
    ('відкритий', 'aberto'),
    ('відкрита', 'aberta'),
    ('відкрито', 'aberto'),
    ('закрити', 'fechar'),
    ('Закрити', 'Fechar'),
    ('закрийте', 'feche'),
    ('скасувати', 'cancelar'),
    ('Скасувати', 'Cancelar'),
    ('скасований', 'cancelado'),
    ('скасована', 'cancelada'),
    ('скасовано', 'cancelado'),
    ('та', 'e'),
    ('без', 'sem'),
    ('після', 'após'),
    ('перед', 'antes de'),
    ('між', 'entre'),
    ('крім', 'exceto'),
    ('разом', 'juntos'),
    ('зараз', 'agora'),
    ('нині', 'agora'),
    ('раніше', 'anteriormente'),
    ('пізніше', 'mais tarde'),
    ('завжди', 'sempre'),
    ('ніколи', 'nunca'),
    ('майже', 'quase'),
    ('одразу', 'imediatamente'),
    ('швидко', 'rapidamente'),
    ('повільно', 'lentamente'),
    ('справно', 'corretamente'),
    ('правильно', 'corretamente'),
    ('неправильно', 'incorretamente'),
    ('точно', 'exatamente'),
    ('приблизно', 'aproximadamente'),
    ('взагалі', 'geralmente'),
    ('обов\'язково', 'obrigatoriamente'),
    ("обов'язково", 'obrigatoriamente'),
    ('необов\'язково', 'opcionalmente'),
    ("необов'язково", 'opcionalmente'),
]

files = sorted(glob.glob('pages/**/*.html', recursive=True))

total_replacements = 0
total_files = 0
files_with_changes = []

for filepath in files:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f'ERROR reading {filepath}: {e}')
        continue

    original = content
    replacements = 0

    for uk, pt in FIXES:
        count = content.count(uk)
        if count > 0:
            content = content.replace(uk, pt)
            replacements += count

    if content != original:
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            files_with_changes.append((filepath, replacements))
            total_replacements += replacements
            total_files += 1
        except Exception as e:
            print(f'ERROR writing {filepath}: {e}')

print(f'\n{"="*60}')
print(f'ПРОХІД 3: {total_files} файлів, {total_replacements} замін')
print(f'{"="*60}')
for fp, count in files_with_changes:
    print(f'  {count:4d} замін: {fp}')
