#!/usr/bin/env python3
# Масовий перекладач Ukrainian → Portuguese для всіх HTML файлів FestLift
# Порядок: від довшого до коротшого, щоб уникнути часткових замін

import os
import re
import glob

# ======================== СЛОВНИК ПЕРЕКЛАДІВ ========================
# (ukrainian, portuguese) — від довшого до коротшого
TRANSLATIONS = [
    # === Спеціальні фрази / словосполучення (найдовші спочатку) ===
    ('Заявки на обслуговування', 'Pedidos de manutenção'),
    ('Аналітика та звіти', 'Análise e relatórios'),
    ('Технічна підтримка', 'Suporte técnico'),
    ('Управління ліфтами', 'Gestão de elevadores'),
    ('Керування QR-кодами', 'Gestão de QR-codes'),
    ('Аналітика QR-кодів', 'Análise de QR-codes'),
    ('Історія сканувань', 'Histórico de leituras'),
    ('Шаблони звітів', 'Modelos de relatórios'),
    ('Призначення завдань', 'Gestão de tarefas'),
    ('Шаблони ТО', 'Modelos de manutenção'),
    ('AI Прогнозування', 'Previsão por IA'),
    ('Мапа ліфтів', 'Mapa de elevadores'),
    ('AI Асистент', 'Assistente de IA'),
    ('Головна панель', 'Painel principal'),
    ('Email шаблони', 'Modelos de Email'),
    ('Кошторис (Створити)', 'Criar Orçamento'),
    ('Кошторис (Список)', 'Lista de Orçamentos'),
    ('QR Система', 'Sistema QR'),
    ('QR-коди', 'QR-codes'),
    ('Підтримка', 'Suporte'),

    # === Навігація ===
    ('Дашборд', 'Painel'),
    ('Моніторинг', 'Monitorização'),
    ('Аналітика', 'Análise'),
    ('Документи', 'Documentos'),
    ('Користувачі', 'Utilizadores'),
    ('Налаштування', 'Configurações'),
    ('Сповіщення', 'Notificações'),
    ('Профіль', 'Perfil'),
    ('Інспекції', 'Inspeções'),
    ('Звіти', 'Relatórios'),
    ('Ліфти', 'Elevadores'),
    ('Клієнти', 'Clientes'),
    ('Техніки', 'Técnicos'),
    ('Календар', 'Calendário'),
    ('Головна', 'Principal'),
    ('Вийти', 'Sair'),

    # === Роль / Заголовки ===
    ('Адміністратор', 'Administrador'),
    ('Диспетчер', 'Dispatcher'),
    ('Панель диспетчера', 'Painel do dispatcher'),
    ('Технік панель', 'Painel do técnico'),

    # === Статуси ===
    ('Не визначено', 'Não definido'),
    ('Призначено', 'Atribuído'),
    ('В очікуванні', 'Em espera'),
    ('Активні', 'Ativos'),
    ('Прострочені', 'Atrasados'),
    ('Протерміновано', 'Atrasado'),
    ('Терміновий', 'Urgente'),
    ('Термінові', 'Urgentes'),
    ('Вільних техніків', 'Técnicos disponíveis'),
    ('Всього pedidos', 'Total de pedidos'),
    ('Вільний', 'Disponível'),

    # === Форма / Поля ===
    ('Пароль', 'Palavra-passe'),
    ('залиште порожнім для автоматичної генерації', 'deixe vazio para geração automática'),
    ('Введіть примітку до', 'Digite uma nota para'),
    ('Опишіть що було зроблено', 'Descreva o que foi feito'),
    ('Використані запчастини/матеріали', 'Peças/materiais utilizados'),
    ('Текст примітки', 'Texto da nota'),
    ('Введіть', 'Digite'),
    ('Номер:', 'Número:'),
    ('Тип:', 'Tipo:'),
    ('Пріоритет:', 'Prioridade:'),
    ('Статус:', 'Estado:'),
    ('Адреса:', 'Endereço:'),
    ('Год. роботи:', 'H. de trabalho:'),
    ('Ліфт:', 'Elevador:'),
    ('Час', 'Hora'),
    ('Тип роботи', 'Tipo de trabalho'),
    ('Дата', 'Data'),

    # === Кнопки та дії ===
    ('Зберегти', 'Guardar'),
    ('Завершити', 'Concluir'),
    ('Додати примітку', 'Adicionar nota'),
    ('Маршрут до ліфта', 'Rota ao elevador'),
    ('Поchatи', 'Iniciar'),
    ('Активних завдань немає', 'Sem tarefas ativas'),

    # === Таблиці / Списки ===
    ('Виконана робота', 'Trabalho realizado'),
    ('Приміток немає', 'Sem notas'),

    # === Сповіщення / JS рядки ===
    ('Відключено від системи', 'Desligado do sistema'),
    ('Відchaveено від системи', 'Desligado do sistema'),
    ('Відchaveено', 'Desligado'),
    ('Помилка з\'єднання', 'Erro de ligação'),
    ('Помилка входу', 'Erro de login'),
    ('Помилка', 'Erro'),
    ('Не вдалося', 'Não foi possível'),
    ('Перевірте підchaveення до сервера', 'Verifique a ligação ao servidor'),
    ('Координати ліфта не encontrado', 'Coordenadas do elevador não encontradas'),
    ('Не вдалося отримати координати ліфта', 'Não foi possível obter as coordenadas do elevador'),
    ('Nota успішно додана', 'Nota adicionada com sucesso'),
    ('Nota збережена локально', 'Nota guardada localmente'),
    ('Користувача успішно guardado', 'Utilizador guardado com sucesso'),
    ('Не вдалося зберегти користувача', 'Não foi possível guardar o utilizador'),
    ('Користувача успішно eliminado', 'Utilizador eliminado com sucesso'),
    ('Не вдалося видалити користувача', 'Não foi possível eliminar o utilizador'),
    ('Не вдалося змінити статус користувача', 'Não foi possível alterar o estado do utilizador'),
    ('Користувача не encontrado', 'Utilizador não encontrado'),
    ('Доступ proibido. Необхідні права техніка.', 'Acesso proibido. Necessários direitos de técnico.'),
    ('Нове tarefas', 'Nova tarefa'),
    ('ТЕРМІНОВО', 'URGENTE'),
    ('Нових сповіщень немає', 'Sem novas notificações'),
    ('Немає нових сповіщень', 'Sem novas notificações'),
    ('Всі сповіщення', 'Ver todas as notificações'),
    ('Спробуйте оновити сторінку', 'Tente atualizar a página'),
    ('API недоступний', 'API indisponível'),
    ('Ваша поточна позиція', 'A sua posição atual'),

    # === Titles ===
    ('Диспетчер - Головна панель', 'Dispatcher - Painel principal'),
    ('Технік панель - FestLift', 'Técnico - FestLift'),

    # === Breadcrumbs ===
    ('Дашборд', 'Painel'),

    # === Misc stray kyrillic ===
    ('Ініціалізація клієнтської панелі', 'Inicialização do painel cliente'),
    ('клієнтської панелі', 'do painel cliente'),
    ('клієнтської', 'do cliente'),
    ('Controlador техніка', 'Dados do técnico'),
    ('Ligado до системи', 'Ligado ao sistema'),
    ('Нове завдання', 'Nova tarefa'),
    ('Призначення завдань', 'Gestão de tarefas'),
    ('завдань', 'de tarefas'),
    ('завдань немає', 'sem tarefas'),
    ('завдання', 'tarefa'),
    ('таrefas', 'tarefas'),
    ('Novas tarefas з\'являться тут автоматично', 'Novas tarefas aparecerão aqui automaticamente'),
    ('з\'являться тут автоматично', 'aparecerão aqui automaticamente'),
    ('Маршрут до ліфта', 'Rota ao elevador'),
    ('Виконання tarefas', 'Execução de tarefas'),
    ('Завершення tarefas', 'Conclusão de tarefas'),
    ('Завершити tarefas', 'Concluir tarefa'),
    ('Додати примітку', 'Adicionar nota'),
    ('Não foi possível descarregar detalhes tarefas', 'Não foi possível carregar os detalhes da tarefa'),

    # === Панель Диспетчера ===
    ('Панель диспетчера', 'Painel do dispatcher'),
    ('Всього pedidos', 'Total de pedidos'),
    ('В очікуванні', 'Em espera'),
    ('Вільних техніків', 'Técnicos disponíveis'),
    ('Терміновos pedidos', 'Pedidos urgentes'),
    ('Останні pedidos', 'Últimos pedidos'),
    ('Ordenar: Novos споchatку', 'Ordenar: Mais recentes primeiro'),
    ('Дата', 'Data'),

    # === Admin Users ===
    ('(залиште порожнім для автоматичної генерації)', '(deixe vazio para geração automática)'),
    ('Не вдалося descarregar користувачів', 'Não foi possível carregar utilizadores'),
    ('Створення нового користувача', 'Criar novo utilizador'),
    ('Erro створення користувача', 'Erro ao criar utilizador'),
    ('Erro оновлення користувача', 'Erro ao atualizar utilizador'),
    ('Estado do utilizador змінено на', 'Estado do utilizador alterado para'),
    ('Não foi possível змінити статус', 'Não foi possível alterar o estado'),
    ('Não foi possível eliminado', 'Não foi possível eliminar'),
    ('Err зміни статусу', 'Erro ao alterar estado'),
    ('Користувача criado', 'Utilizador criado'),

    # === Tech dashboard strings ===
    ('Активні pedidos', 'Pedidos ativos'),
    ('Concluído сьогодні', 'Concluídos hoje'),
    ('Термінові', 'Urgentes'),
    ('Прострочені', 'Atrasados'),
    ('Активні tarefas', 'Tarefas ativas'),
    ('Опис concluídoї роботи', 'Descrição do trabalho concluído'),
    ('Опишіть що було зроблено...', 'Descreva o que foi feito...'),
    ('Mастильний матеріал, Ремінь приводу', 'Óleo lubrificante, Correia de transmissão'),
    ('ex. Мастильний матеріал, Ремінь приводу...', 'ex. Óleo lubrificante, Correia de transmissão...'),
    ('Витрачено часу (horas)', 'Tempo gasto (horas)'),
    ('Завершити tarefas', 'Concluir tarefa'),
    ('Додати примітку', 'Adicionar nota'),
    ('Текст примітки', 'Texto da nota'),
    ('Введіть примітку до tarefas...', 'Digite uma nota para a tarefa...'),
    ('Зберегти', 'Guardar'),
    ('Autoризовано як', 'Autorizado como'),

    # === Sidebar Admin ===
    ('Управління ліфтами', 'Gestão de elevadores'),
    ('Заявки на обслуговування', 'Pedidos de manutenção'),
    ('Кошторис (Створити)', 'Criar Orçamento'),
    ('Кошторис (Список)', 'Lista de Orçamentos'),
    ('Email шаблони', 'Modelos de Email'),
    ('Шаблони звітів', 'Modelos de relatórios'),
    ('Технічна підтримка', 'Suporte técnico'),

    # === Login ===
    ('Bem-vindo! Por favor змініть тимчасовий пароль перед початком роботи.', 'Bem-vindo! Por favor altere a sua palavra-passe temporária antes de começar.'),
    ('Demo акаунти', 'Contas de demonstração'),
    ('Система авторизації', 'Sistema de autenticação'),
    ('Модал примусової зміни пароля', 'Modal de alteração obrigatória de palavra-passe'),
    ('Тимчасовий пароль', 'Palavra-passe temporária'),
    ('показується поки mustChangePassword = true', 'exibido enquanto mustChangePassword = true'),

    # === Common words ===
    ('ліфта', 'do elevador'),
    ('ліфтів', 'de elevadores'),
    ('ліфти', 'elevadores'),
    ('ліфт', 'elevador'),
    ('Ліфт', 'Elevador'),
    ('техніків', 'de técnicos'),
    ('техніка', 'do técnico'),
    ('техніку', 'ao técnico'),
    ('Техніка', 'Técnico'),
    ('Диспетчер', 'Dispatcher'),
    ('диспетчера', 'do dispatcher'),
    ('заявки', 'pedidos'),
    ('заявок', 'de pedidos'),
    ('заявку', 'o pedido'),
    ('Заявки', 'Pedidos'),
    ('Заявку', 'Pedido'),
    ('примітки', 'notas'),
    ('примітку', 'nota'),
    ('Примітки', 'Notas'),
    ('замовлення', 'pedidos'),
    ('оновлення', 'atualização'),
    ('сповіщення', 'notificações'),
    ('Сповіщення', 'Notificação'),
    ('сповіщень', 'de notificações'),
    ('користувача', 'do utilizador'),
    ('користувачів', 'de utilizadores'),
    ('Користувача', 'Utilizador'),
    ('статус', 'estado'),
    ('Статус', 'Estado'),
    ('адресу', 'endereço'),
    ('Адреса', 'Endereço'),
    ('адреса', 'endereço'),
    ('звіт', 'relatório'),
    ('звіту', 'do relatório'),
    ('Звіт', 'Relatório'),
    ('помилка', 'erro'),
    ('Помилка', 'Erro'),
    ('помилки', 'de erros'),
    ('підтримка', 'suporte'),
    ('Підтримка', 'Suporte'),
    ('налаштування', 'configurações'),
    ('Налаштування', 'Configurações'),
    ('профіль', 'perfil'),
    ('Профіль', 'Perfil'),
    ('виходити', 'sair'),
    ('вийти', 'sair'),
    ('Вийти', 'Sair'),
    ('документів', 'de documentos'),
    ('Документи', 'Documentos'),
    ('документ', 'documento'),
    ('аналітика', 'análise'),
    ('Аналітика', 'Análise'),
    ('інспекцій', 'de inspeções'),
    ('інспекції', 'inspeções'),
    ('Інспекції', 'Inspeções'),
    ('інспекцію', 'inspeção'),
    ('Інспекцію', 'Inspeção'),
    ('моніторинг', 'monitorização'),
    ('Моніторинг', 'Monitorização'),
    ('завдань', 'de tarefas'),
    ('завдання', 'tarefa'),
    ('Завдань', 'De tarefas'),
    ('Завдання', 'Tarefa'),
    ('календар', 'calendário'),
    ('Календар', 'Calendário'),
    ('дашборд', 'painel'),
    ('Дашборд', 'Painel'),
    ('маршрут', 'rota'),
    ('Маршрут', 'Rota'),
    ('карту', 'mapa'),
    ('карті', 'no mapa'),
    ('карта', 'mapa'),
    ('Карта', 'Mapa'),
    ('карту', 'mapa'),
    ('координати', 'coordenadas'),
    ('Координати', 'Coordenadas'),
    ('пароль', 'palavra-passe'),
    ('Пароль', 'Palavra-passe'),
    ('паролю', 'da palavra-passe'),
    ('паролів', 'de palavras-passe'),
    ('ролі', 'de função'),
    ('роль', 'função'),
    ('Роль', 'Função'),
    ('ролей', 'de funções'),
    ('знайдено', 'encontrado'),
    ('Знайдено', 'Encontrado'),
    ('видалити', 'eliminar'),
    ('видалення', 'eliminação'),
    ('Видалити', 'Eliminar'),
    ('видалено', 'eliminado'),
    ('Видалено', 'Eliminado'),
    ('додано', 'adicionado'),
    ('додати', 'adicionar'),
    ('Додати', 'Adicionar'),
    ('відмінити', 'cancelar'),
    ('Відмінити', 'Cancelar'),
    ('закрити', 'fechar'),
    ('Закрити', 'Fechar'),
    ('зберегти', 'guardar'),
    ('Зберегти', 'Guardar'),
    ('редагувати', 'editar'),
    ('Редагувати', 'Editar'),
    ('редагування', 'edição'),
    ('Редагування', 'Edição'),
    ('перевірити', 'verificar'),
    ('Перевірити', 'Verificar'),
    ('оновити', 'atualizar'),
    ('Оновити', 'Atualizar'),
    ('завантажити', 'carregar'),
    ('Завантажити', 'Carregar'),
    ('завантажено', 'carregado'),
    ('Завантажено', 'Carregado'),
    ('відображення', 'apresentação'),
    ('Відображення', 'Apresentação'),
    ('відображати', 'mostrar'),
    ('Відображати', 'Mostrar'),
    ('призначити', 'atribuir'),
    ('Призначити', 'Atribuir'),
    ('призначення', 'atribuição'),
    ('Призначення', 'Atribuição'),
    ('очікування', 'espera'),
    ('Очікування', 'Espera'),
    ('номер', 'número'),
    ('Номер', 'Número'),
    ('тип', 'tipo'),
    ('Тип', 'Tipo'),
    ('пріоритет', 'prioridade'),
    ('Пріоритет', 'Prioridade'),
    ('дата', 'data'),
    ('Дата', 'Data'),
    ('час', 'hora'),
    ('Час', 'Hora'),
    ('адрес', 'endereço'),
    ('Адрес', 'Endereço'),
    ('опис', 'descrição'),
    ('Опис', 'Descrição'),
    ('назва', 'nome'),
    ('Назва', 'Nome'),
    ('нотатка', 'nota'),
    ('Нотатка', 'Nota'),
    ('нові', 'novos'),
    ('Нові', 'Novos'),
    ('нового', 'novo'),
    ('Нового', 'Novo'),
    ('нова', 'nova'),
    ('Нова', 'Nova'),
    ('новий', 'novo'),
    ('Новий', 'Novo'),
    ('немає', 'não há'),
    ('Немає', 'Não há'),
    ('реєстрація', 'registo'),
    ('Реєстрація', 'Registo'),
    ('підключення', 'ligação'),
    ('Підключення', 'Ligação'),
    ('підключено', 'ligado'),
    ('Підключено', 'Ligado'),
    ('відключено', 'desligado'),
    ('Відключено', 'Desligado'),
    ('помилки', 'erros'),
    ('Помилки', 'Erros'),
    ('попередження', 'aviso'),
    ('Попередження', 'Aviso'),
    ('успішно', 'com sucesso'),
    ('Успішно', 'Com sucesso'),
    ('підтвердити', 'confirmar'),
    ('Підтвердити', 'Confirmar'),
    ('підтвердження', 'confirmação'),
    ('Підтвердження', 'Confirmação'),
    ('відправити', 'enviar'),
    ('Відправити', 'Enviar'),
    ('відправлено', 'enviado'),
    ('Відправлено', 'Enviado'),
    ('пошук', 'pesquisa'),
    ('Пошук', 'Pesquisa'),
    ('фільтр', 'filtro'),
    ('Фільтр', 'Filtro'),
    ('фільтрувати', 'filtrar'),
    ('Фільтрувати', 'Filtrar'),
    ('ввімкнути', 'ativar'),
    ('Ввімкнути', 'Ativar'),
    ('вимкнути', 'desativar'),
    ('Вимкнути', 'Desativar'),
    ('активний', 'ativo'),
    ('Активний', 'Ativo'),
    ('активна', 'ativa'),
    ('Активна', 'Ativa'),
    ('неактивний', 'inativo'),
    ('Неактивний', 'Inativo'),
    ('заблокований', 'bloqueado'),
    ('Заблокований', 'Bloqueado'),
    ('критичний', 'crítico'),
    ('Критичний', 'Crítico'),
    ('терміново', 'urgente'),
    ('Терміново', 'Urgente'),
    ('термін', 'prazo'),
    ('Термін', 'Prazo'),
    ('рахунок', 'fatura'),
    ('Рахунок', 'Fatura'),
    ('рахунки', 'faturas'),
    ('Рахунки', 'Faturas'),
    ('оплата', 'pagamento'),
    ('Оплата', 'Pagamento'),
    ('контракт', 'contrato'),
    ('Контракт', 'Contrato'),
    ('контракти', 'contratos'),
    ('Контракти', 'Contratos'),
    ('тикет', 'ticket'),
    ('Тикет', 'Ticket'),
    ('тикети', 'tickets'),
    ('Тикети', 'Tickets'),
    ('категорія', 'categoria'),
    ('Категорія', 'Categoria'),
    ('категорії', 'categorias'),
    ('Категорії', 'Categorias'),
    ('мова', 'idioma'),
    ('Мова', 'Idioma'),
    ('версія', 'versão'),
    ('Версія', 'Versão'),
    ('система', 'sistema'),
    ('Система', 'Sistema'),
    ('логотип', 'logótipo'),
    ('Логотип', 'Logótipo'),
    ('головна', 'principal'),
    ('Головна', 'Principal'),
    ('панель', 'painel'),
    ('Панель', 'Painel'),
    ('інформація', 'informação'),
    ('Інформація', 'Informação'),
    ('загальна', 'geral'),
    ('Загальна', 'Geral'),
    ('загальні', 'gerais'),
    ('Загальні', 'Gerais'),
    ('детальна', 'detalhada'),
    ('Детальна', 'Detalhada'),
    ('деталі', 'detalhes'),
    ('Деталі', 'Detalhes'),
    ('детальніше', 'mais detalhes'),
    ('Детальніше', 'Mais detalhes'),
    ('зображення', 'imagem'),
    ('Зображення', 'Imagem'),
    ('фото', 'foto'),
    ('Фото', 'Foto'),
    ('відео', 'vídeo'),
    ('Відео', 'Vídeo'),
    ('файл', 'ficheiro'),
    ('Файл', 'Ficheiro'),
    ('файли', 'ficheiros'),
    ('Файли', 'Ficheiros'),
    ('шаблон', 'modelo'),
    ('Шаблон', 'Modelo'),
    ('шаблони', 'modelos'),
    ('Шаблони', 'Modelos'),
    ('модуль', 'módulo'),
    ('Модуль', 'Módulo'),
    ('посилання', 'ligação'),
    ('Посилання', 'Ligação'),
    ('URL', 'URL'),
    ('токен', 'token'),
    ('Токен', 'Token'),
    ('senha', 'palavra-passe'),
    ('Senha', 'Palavra-passe'),
    ('логін', 'login'),
    ('Логін', 'Login'),
    ('вхід', 'entrada'),
    ('Вхід', 'Entrada'),
    ('вийти', 'sair'),
    ('Вийти', 'Sair'),
    ('вихід', 'saída'),
    ('Вихід', 'Saída'),
    ('авторизація', 'autorização'),
    ('Авторизація', 'Autorização'),
    ('авторизований', 'autorizado'),
    ('Авторизований', 'Autorizado'),
    ('авторизовано', 'autorizado'),
    ('Авторизовано', 'Autorizado'),
    ('доступ', 'acesso'),
    ('Доступ', 'Acesso'),
    ('доступний', 'disponível'),
    ('Доступний', 'Disponível'),
    ('недоступний', 'indisponível'),
    ('Недоступний', 'Indisponível'),

    # === Dispatcher special ===
    ('Termin', 'Prazo'),
    ('Терміновos', 'Urgentes'),

    # === Comments for UI understanding ===
    ('Бічна панель', 'Painel lateral'),
    ('Навігаційна панель', 'Barra de navegação'),
    ('Модальне вікно', 'Janela modal'),
    ('Модальне підтвердження', 'Confirmação modal'),
    ('Модальні вікна', 'Janelas modais'),
    ('Легенда', 'Legenda'),
    ('Локації', 'Localizações'),
    ('Категорії підтримки', 'Categorias de suporte'),
    ('Доступні звіти', 'Relatórios disponíveis'),
    ('Доступність техніків', 'Disponibilidade de técnicos'),
    ('Загальна статистика', 'Estatísticas gerais'),
    ('Загальні рекомендації', 'Recomendações gerais'),
    ('Детальна статистика', 'Estatísticas detalhadas'),
    ('Денний gráfico', 'Gráfico diário'),
    ('Основні графи', 'Gráficos principais'),
    ('Додаткові графи', 'Gráficos adicionais'),
    ('Навігація по аналітиці', 'Navegação da análise'),
    ('Навігація по профілю', 'Navegação do perfil'),
    ('Особиста інформація', 'Informação pessoal'),
    ('Додаткова інформація', 'Informação adicional'),
    ('Активні тикети', 'Tickets ativos'),
    ('Активні тикети будуть завантажені тут', 'Os tickets ativos serão carregados aqui'),
    ('Активні tarefas будуть завантажені тут', 'As tarefas ativas serão carregadas aqui'),
    ('Буде заповнено динамічно', 'Será preenchido dinamicamente'),
    ('Заповнюється динамічно', 'Preenchido dinamicamente'),
    ('Динамічно', 'Dinamicamente'),
    ('Всі алерти будуть додані динамічно', 'Todos os alertas serão adicionados dinamicamente'),
    ('Критичні алерти будуть додані динамічно', 'Os alertas críticos serão adicionados dinamicamente'),
    ('Календар буде додано динамічно', 'O calendário será adicionado dinamicamente'),
    ('Матриця буде згенерована динамічно', 'A matriz será gerada dinamicamente'),
    ('Звіт буде згенеровано JS', 'O relatório será gerado por JS'),
    ('Звіти будуть завантажені тут', 'Os relatórios serão carregados aqui'),
    ('Клієнти будуть завантажені тут', 'Os clientes serão carregados aqui'),
    ('Навички будуть завантажені тут', 'As competências serão carregadas aqui'),
    ('Карта техніків', 'Mapa de técnicos'),
    ('Кнопки дій', 'Botões de ação'),
    ('Кнопка закриття маршруту', 'Botão fechar rota'),
    ('Кнопки згортання', 'Botões de colapso'),
    ('Кнопка додавання нового техніка', 'Botão adicionar novo técnico'),
    ('Контейнер для карток клієнтів', 'Contêiner para cartões de clientes'),
    ('Опції пакетного керування', 'Opções de gestão em lote'),
    ('Масові ações', 'Ações em massa'),
    ('Gruppові ações', 'Ações em grupo'),
    ('Вихід', 'Saída'),
    ('Вкладка пароля', 'Separador de palavra-passe'),
    ('Вкладка інформації', 'Separador de informação'),
    ('Власний період (прихований за замовчуванням)', 'Período personalizado (oculto por padrão)'),
    ('Версія: 2.0 Portugal (2026-01-13)', 'Versão: 2.0 Portugal (2026-01-13)'),
    ('Меню навігації', 'Menu de navegação'),
    ('Аватар та основна інформація', 'Avatar e informação principal'),
    ('Аватар', 'Avatar'),
    ('Логотип FestLift', 'Logótipo FestLift'),
    ('Контракти', 'Contratos'),
    ('Координати (скорочено)', 'Coordenadas (abreviado)'),
    ('Інформація про систему та користувача', 'Informação sobre o sistema e o utilizador'),
    ('Інформація про систему', 'Informação do sistema'),
    ('Індикатор завантаження даних ліфта', 'Indicador de carregamento de dados do elevador'),
    ('Інспекції будуть завантажені тут', 'As inspeções serão carregadas aqui'),
    ('Звіти інспекції', 'Relatórios de inspeção'),
    ('Імпорт QR-кодів', 'Importação de QR-codes'),
    ('Завантажувач профілю з API', 'Carregador de perfil da API'),
    ('Завантажувач профілю клієнта (специфічний)', 'Carregador de perfil do cliente (específico)'),
    ('8. AI Асистент', '8. Assistente de IA'),
    ('Доступні звіти', 'Relatórios disponíveis'),

    # === Comments Ukrainian-only ===
    ('Ініціалізація WebSocket для клієнтської панелі', 'Inicialização WebSocket para o painel cliente'),
    ('Ініціалізація WebSocket для технічної панелі', 'Inicialização WebSocket para o painel técnico'),
    ('Ініціалізація клієнтської панелі з даними API', 'Inicialização do painel cliente com dados da API'),
    ('Відображення останніх заявок', 'Exibição dos últimos pedidos'),
    ('Відображення сповіщень для техніка', 'Exibição de notificações para o técnico'),
    ('Відображення сповіщень', 'Exibição de notificações'),
    ('Допоміжні функції для статусів', 'Funções auxiliares para estados'),
    ('Обробка urgenteго сповіщення', 'Processamento de notificação urgente'),
    ('Обробка діагностики ліфта', 'Processamento do diagnóstico do elevador'),
    ('Обробка нового tarefas', 'Processamento de nova tarefa'),
    ('ВАЖЛИВО: Оголошуються ДО класу, щоб бути доступними одразу', 'IMPORTANTE: Declarados ANTES da classe para estarem disponíveis imediatamente'),
    ('Глобальні функції для onclick handlers', 'Funções globais para handlers onclick'),
    ('ROUTING CONTROL - Вікно з маршрутом (DRAGGABLE)', 'CONTROLO DE ROTA - Janela com rota (ARRASTÁVEL)'),
    ('ФІКС: Обробники мертвих кнопок', 'CORREÇÃO: Handlers de botões mortos'),
    ('Іконка перетягування в заголовку', 'Ícone de arrastar no cabeçalho'),
    ('Адаптивність', 'Responsividade'),
    ('Альтернативи маршруту', 'Alternativas de rota'),
    ('Анімація для сповіщень', 'Animação para notificações'),
    ('Анімація при перетягуванні', 'Animação ao arrastar'),
    ('Анімації', 'Animações'),
    ('Вікно маршруту - можна перетягувати', 'Janela de rota - arrastável'),
    ('Забезпечення правильного відображення на мобільних', 'Garantir exibição correta em dispositivos móveis'),
    ('Кастомні скроллбари', 'Barras de rolagem personalizadas'),
    ('Кастомні стилі для звітів', 'Estilos personalizados para relatórios'),
    ('Кастомні стилі для пагінації', 'Estilos personalizados para paginação'),
    ('Кнопки згортання', 'Botões de recolher'),
    ('Кольорові бейджі статусу', 'Badges coloridos de estado'),
    ('Менші кнопки для таблиць', 'Botões menores para tabelas'),
    ('Нотифікації', 'Notificações'),
    ('Покращення прокручування в nested modal', 'Melhoria de rolagem em modal encadeado'),
    ('Різні кольори для кожного типу pedidos', 'Cores diferentes para cada tipo de pedido'),
    ('Скролбар', 'Barra de rolagem'),
    ('Спеціальні стилі для AR', 'Estilos especiais para AR'),
    ('Спеціальні стилі для nested modal windows', 'Estilos especiais para janelas modais encadeadas'),
    ('Спеціальні стилі для карток', 'Estilos especiais para cartões'),
    ('Спеціальні стилі для перемикачів', 'Estilos especiais para interruptores'),
    ('Спеціальні стилі для форми', 'Estilos especiais para formulários'),
    ('Стилі для прогресу', 'Estilos para progresso'),
    ('Стилі для темного режиму', 'Estilos para modo escuro'),
    ('Стилізація заголовка - активна зона для перетягування', 'Estilização do cabeçalho - zona ativa para arrastar'),
    ('Конвертувати ISO date', 'Converter data ISO'),
    ('Карта тимчасово недоступна. Спробуйте оновити сторінку.', 'Mapa temporariamente indisponível. Tente atualizar a página.'),
    ('Прогнозується зmaisння витрат на ТО на 15% у наступному кварталі', 'Prevê-se uma redução de 15% nos custos de manutenção no próximo trimestre'),
    ('Рекомендується впровадити превентивне ТО для 3 ліфтів високого ризику', 'Recomenda-se implementar manutenção preventiva para 3 elevadores de alto risco'),
    ('Це виправить координати ВСІХ ліфтів з неправильними або відсутніми координатами.', 'Isto irá corrigir as coordenadas de TODOS os elevadores com coordenadas incorretas ou ausentes.'),
    ('Натисніть Cancel для виправлення лише ліфтів без координат.', 'Clique em Cancelar para corrigir apenas os elevadores sem coordenadas.'),
    ('Натисніть OK для повного re-geocoding (може зайняти кілька хвилин).', 'Clique em OK para re-geocoding completo (pode demorar vários minutos).'),
    ('Натисніть', 'Clique'),

    # === Alerts/Buttons visible in UI ===
    ('Переdescarregar', 'Recarregar'),
    ('Помилка', 'Erro'),
    ('для перезавантаження без кешу', 'para recarregar sem cache'),

    # === JS string mixes ===
    ("'maintenance': 'На обслуговуванні'", "'maintenance': 'Em manutenção'"),
    ("'new': 'Нове'", "'new': 'Novo'"),
    ("'revogado': { color: 'dark', text: 'Скасований' }", "'revogado': { color: 'dark', text: 'Revogado' }"),
    ("'vigente': { color: 'success', text: 'Діючий' }", "'vigente': { color: 'success', text: 'Vigente' }"),
    ("\"Обов'язковий\"", '"Obrigatório"'),
    ("'Обов\\'язковий'", "'Obrigatório'"),
    ("'Обов\\'язковий (умовно)'", "'Obrigatório (condicional)'"),
    ('Модернізація (обов.)', 'Modernização (obrig.)'),
    ("'Необов\\'язковий'", "'Opcional'"),
    ('Частково діючий', 'Parcialmente vigente'),
    ('Скасований', 'Revogado'),
    ('Діючий', 'Vigente'),
    ('На обслуговуванні', 'Em manutenção'),

    # === Stray mixed strings ===
    ('Не a funcionar', 'Fora de serviço'),
    ('Fora de serviço', 'Fora de serviço'),

    # === Generic JS log text that's partly translated ===
    ('Erro ao carregar профілю', 'Erro ao carregar o perfil'),
    ('API недоступний, використовуємо локальні дані', 'API indisponível, usando dados locais'),
    ('A carregar ліфтів клієнта з API', 'A carregar elevadores do cliente da API'),
    ('Erro ao carregar ліфтів', 'Erro ao carregar elevadores'),
    ('Elevadores завантажено', 'Elevadores carregados'),
    ('Err ao carregar ліфтів', 'Erro ao carregar elevadores'),
    ('A carregar заявок клієнта', 'A carregar pedidos do cliente'),
    ('Erro ao carregar заявок', 'Erro ao carregar pedidos'),
    ('Pedidos завантажено', 'Pedidos carregados'),
    ('Err ao carregar заявок', 'Erro ao carregar pedidos'),
    ('API недоступний для сповіщень', 'API indisponível para notificações'),
    ('Контейнер для заявок не знайдено', 'Contêiner de pedidos não encontrado'),
    ('UniversalWebSocketManager не знайдено', 'UniversalWebSocketManager não encontrado'),
    ('UniversalWebSocketManager не encontrado', 'UniversalWebSocketManager não encontrado'),
    ('WebSocket підключено', 'WebSocket ligado'),
    ('Atualização статусу заявки', 'Atualização do estado do pedido'),
    ('Atualização доступності ліфтів', 'Atualização de disponibilidade dos elevadores'),
    ('Сервісне повідомлення', 'Mensagem de serviço'),
    ('WebSocket відключено', 'WebSocket desligado'),
    ('Відключено від системи', 'Desligado do sistema'),
    ("showNotification('Відключено від системи', 'warning')", "showNotification('Desligado do sistema', 'warning')"),
    ("showNotification('Помилка з\\'єднання', 'error')", "showNotification('Erro de ligação', 'error')"),
    ('WebSocket помилка', 'Erro WebSocket'),
    ('Помилка ініціалізації WebSocket', 'Erro de inicialização WebSocket'),

    # === Tech Dashboard ===
    ('A carregar dados техніка', 'A carregar dados do técnico'),
    ('Dados техніка завантажено', 'Dados do técnico carregados'),
    ('Erro ao carregar даних техніка', 'Erro ao carregar dados do técnico'),
    ('Erro ao carregar деталей', 'Erro ao carregar detalhes'),
    ('Tabela de tarefas не знайдена', 'Tabela de tarefas não encontrada'),
    ('Активних завдань для відображення', 'Tarefas ativas para exibição'),
    ('всього', 'total'),
    ('Всього', 'Total'),
    ('Відкриття деталей tarefas', 'Abertura dos detalhes da tarefa'),
    ('Поchatок виконання tarefas', 'Início de execução da tarefa'),
    ('Завершення tarefas', 'Conclusão da tarefa'),
    ('Помилка завершення', 'Erro ao concluir'),
    ('Err при завершенні tarefas', 'Erro ao concluir a tarefa'),
    ('Erro при завершенні tarefas', 'Erro ao concluir a tarefa'),
    ('Додавання примітки до tarefas', 'Adição de nota à tarefa'),
    ('Mostrar маршрут до do elevador', 'Mostrar rota para o elevador'),
    ('Nota додана', 'Nota adicionada'),
    ('Nota успішно додана', 'Nota adicionada com sucesso'),
    ('Erro додавання примітки', 'Erro ao adicionar nota'),
    ('Помилка додавання примітки', 'Erro ao adicionar nota'),
    ('Nota збережена локально', 'Nota guardada localmente'),
    ('Статус tarefas atualizado', 'Estado da tarefa atualizado'),
    ('Помилка оновлення статусу', 'Erro ao atualizar estado'),
    ('Erro оновлення статусу tarefas', 'Erro ao atualizar estado da tarefa'),
    ('User не передано в initTechWebSocket', 'User não passado para initTechWebSocket'),
    ('User ID не encontrado', 'ID de utilizador não encontrado'),
    ('Ligado до системи', 'Ligado ao sistema'),
    ('showTechNotification', 'showTechNotification'),
    ('Нове tarefas', 'Nova tarefa'),
    ('ТЕРМІНОВО', 'URGENTE'),
    ('Діагностика do elevador', 'Diagnóstico do elevador'),
    ('WebSocket відchaveено', 'WebSocket desligado'),
    ('Відchaveено від системи', 'Desligado do sistema'),
    ("Err з'єднання", 'Erro de ligação'),
    ('Помилка ініціалізації WebSocket', 'Erro de inicialização WebSocket'),

    # === Remaining mixed ones ===
    ('Не вдалося descarregar користувачів. Перевірте підchaveення до сервера.', 'Não foi possível carregar utilizadores. Verifique a ligação ao servidor.'),
    ('Не вдалося otrimati дані користувача', 'Não foi possível obter os dados do utilizador'),
    ('Не вдалося отримати дані користувача', 'Não foi possível obter os dados do utilizador'),
    ('Не вдалося descarregar detalhes tarefas', 'Não foi possível carregar os detalhes da tarefa'),
    ('Não foi possível descarregar detalhes tarefas', 'Não foi possível carregar os detalhes da tarefa'),
    ('підchaveення', 'ligação'),
    ('підключення', 'ligação'),

    # === Admin Users mixed ===
    ('Не вдалося зберегти користувача', 'Não foi possível guardar o utilizador'),
    ('Estado do utilizador змінено на', 'Estado do utilizador alterado para'),
    ('Сriado', 'Criado'),
    ('Користувача criado', 'Utilizador criado'),
    ('criado!', 'criado!'),

    # === Misc remaining ===
    ('показується поки', 'exibido enquanto'),
    ('тимчасовий пароль перед початком роботи', 'palavra-passe temporária antes de começar'),
    ('Bem-vindo! Por favor змініть', 'Bem-vindo! Por favor altere'),
    ('змініть тимчасовий пароль', 'altere a palavra-passe temporária'),
    ('перед початком роботи', 'antes de começar'),

    # === Breadcrumbs ===
    ('Дашборд', 'Painel'),

    # === Short stray words ===
    ('не знайдено', 'não encontrado'),
    ('Не знайдено', 'Não encontrado'),
    ('не вдалося', 'não foi possível'),
    ('вдалося', 'foi possível'),
    ('від системи', 'do sistema'),
    ('до системи', 'ao sistema'),
    ('від серверу', 'do servidor'),
    ('сервера', 'do servidor'),
    ('сервер', 'servidor'),
    ('оновлення', 'atualização'),
    ('зміни', 'de alteração'),
    ('зміну', 'alteração'),
    ('зміна', 'alteração'),
    ('системи', 'do sistema'),
    ('перегляд', 'visualização'),
    ('Перегляд', 'Visualização'),
    ('завантаження', 'carregamento'),
    ('Завантаження', 'Carregamento'),
    ('відображає', 'apresenta'),
    ('відображення', 'apresentação'),
    ('додавання', 'adição'),
    ('Добавлення', 'Adição'),
    ('видалення', 'eliminação'),
    ('видалити', 'eliminar'),
    ('Видалити', 'Eliminar'),
    ('підтвердити', 'confirmar'),
    ('Підтвердити', 'Confirmar'),
    ('скасувати', 'cancelar'),
    ('Скасувати', 'Cancelar'),
    ('готово', 'concluído'),
    ('Готово', 'Concluído'),
    ('відмова', 'recusa'),
    ('Відмова', 'Recusa'),

    # stray Ukrainian words that appear as partial strings in JS
    ('ліфтів', 'de elevadores'),
    ('ліфта', 'do elevador'),
    ('ліфт', 'elevador'),
    ('Ліфт', 'Elevador'),
    ('техніка', 'do técnico'),
    ('техніків', 'de técnicos'),
    ('Технік', 'Técnico'),
    ('заявок', 'de pedidos'),
    ('заявки', 'pedidos'),
    ('Заявки', 'Pedidos'),
    ('сповіщень', 'de notificações'),
    ('сповіщення', 'notificações'),
    ('Сповіщення', 'Notificações'),
    ('користувача', 'do utilizador'),
    ('Користувача', 'Utilizador'),
    ('користувачів', 'de utilizadores'),
]

# ======================== ФАЙЛИ ДЛЯ ПЕРЕКЛАДУ ========================
files = sorted(glob.glob('pages/**/*.html', recursive=True))

total_replacements = 0
total_files = 0
files_with_changes = []

for filepath in files:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f'ERROR reading {filepath}: {e}')
        continue

    original = content
    replacements = 0

    for uk, pt in TRANSLATIONS:
        count = content.count(uk)
        if count > 0:
            content = content.replace(uk, pt)
            replacements += count

    if content != original:
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            files_with_changes.append((filepath, replacements))
            total_replacements += replacements
            total_files += 1
        except Exception as e:
            print(f'ERROR writing {filepath}: {e}')

print(f'\n{"="*60}')
print(f'ПЕРЕКЛАДЕНО: {total_files} файлів, {total_replacements} замін')
print(f'{"="*60}')
for fp, count in files_with_changes:
    print(f'  {count:4d} замін: {fp}')
