#!/usr/bin/env python3
# Pass 6 - tools, reports, technicians, dashboard, AR, QR remaining
import glob

FIXES6 = [
    # === 'але'→'mas' artifacts ===
    ("Ковmasнко", "Kovalenko"),
    ("Коваmasнко", "Kovalenko"),
    ("Сeтистика", "Estatísticas"),
    ("сeтистика", "estatísticas"),

    # === Acessoні artifacts (Доступні with дост→Acesso) ===
    ("Acessoні", "Disponíveis"),
    ("acessoні", "disponíveis"),
    ("Acessoний", "Disponível"),
    ("acessoно", "disponível"),
    ("неacessoна", "indisponível"),
    ("неacessoний", "indisponível"),
    ("неacessoні", "indisponíveis"),

    # === Tools page ===
    ("Управління інструменeми", "Gestão de ferramentas"),
    ("Управління інструментами", "Gestão de ferramentas"),
    ("інструментів", "de ferramentas"),
    ("інструменти", "ferramentas"),
    ("інструмент", "ferramenta"),
    ("Filtros інструментів", "Filtros de ferramentas"),
    ("Використовуються", "Em uso"),
    ("використовуються", "em uso"),
    ("Несправні", "Avariadas"),
    ("несправний", "avariado"),
    ("Механічні", "Mecânicas"),
    ("механічн", "mecânicos"),
    ("Електричні", "Elétricas"),
    ("електричн", "elétricas"),
    ("Вимірювальні", "De medição"),
    ("Вимірювання", "Medição"),
    ("Todas локації", "Todas as localizações"),

    # === Reports page ===
    ("Швидка сeтистика", "Estatísticas rápidas"),
    ("Exportar всіх relatórioів", "Exportar todos os relatórios"),
    ("Período relatório:", "Período do relatório:"),
    ("Цей semana", "Esta semana"),
    ("Цей кварeл", "Este trimestre"),
    ("Цей ano", "Este ano"),
    ("Фінансовий", "Financeiro"),
    ("Технічний", "Técnico"),
    ("Якість", "Qualidade"),
    ("По do técnicoх", "Por técnico"),
    ("По categoriaх", "Por categoria"),
    ("Data з:", "Data de início:"),
    ("Результatosи relatório", "Resultados do relatório"),
    ("Planeados relatórioи", "Relatórios agendados"),
    ("Planeados relatórioи відсутні", "Sem relatórios agendados"),
    ("Clique «Criar relatório» para генерації", "Clique «Criar relatório» para gerar"),
    ("Data завершення", "Data de conclusão"),

    # === QR Batch remaining ===
    ("desde ficheiroу", "do ficheiro"),
    ("desde QR-codeами", "de QR-codes"),
    ("Iniciar імпорт", "Iniciar importação"),
    ("Тільки активні", "Apenas ativos"),
    ("Тільки неактивні", "Apenas inativos"),
    ("Тільки протерміnovaні", "Apenas expirados"),
    ("Тільки elevadores", "Apenas elevadores"),
    ("Тільки техніки", "Apenas técnicos"),
    ("Seleccione дію:", "Selecione ação:"),
    ("Seleccione дію", "Selecione ação"),
    ("Seleccione", "Selecione"),
    ("Validade (diasв)", "Validade (dias)"),
    ("Pré-configurados modeloи", "Modelos pré-configurados"),

    # === Dispatcher dashboard ===
    ("Терміnovos pedidos", "Pedidos urgentes"),
    ("Сeрі spoatku", "Mais antigos"),
    ("Ordenar: Сeрі spoatku", "Ordenar: Mais antigos primeiro"),
    ("Ordenar: Високий prioridade", "Ordenar: Alta prioridade"),
    ("Ordenar: Низький prioridade", "Ordenar: Baixa prioridade"),
    ("Ver всі", "Ver todos"),
    ("онлайн", "online"),
    ("Онлайн", "Online"),
    ("Gestão do técnicoми", "Gestão de técnicos"),
    ("Швидкі ações", "Ações rápidas"),
    ("Реальний hora", "Hora em tempo real"),
    ("Розсилка повідомлень", "Envio de notificações"),
    ("Надіслати всім техникам", "Enviar a todos os técnicos"),
    ("Управління кодами", "Gestão de códigos"),

    # === AR Helper ===
    ("Допомога desde доповненою реальністю", "Ajuda de realidade aumentada"),
    ("доповненою реальністю", "realidade aumentada"),
    ("доповненою реальністю", "realidade aumentada"),
    ("Неактивно", "Inativo"),
    ("Модель do elevador", "Modelo do elevador"),
    ("Аноeції", "Anotações"),
    ("Знімок", "Fotografia"),
    ("Хот-споти", "Pontos de referência"),
    ("Запустити AR", "Iniciar AR"),
    ("Запустити", "Iniciar"),
    ("على elevador ou робоче середовиainda", "o elevador ou ambiente de trabalho"),
    ("середовиainda", "ambiente"),
    ("робоче середовище", "ambiente de trabalho"),

    # === Technicians page ===
    ("Управління do técnicoми", "Gestão de técnicos"),
    ("Зайняті", "Ocupados"),
    ("Офлайн", "Offline"),
    ("Спеціалізація", "Especialização"),
    ("Todas спеціалізації", "Todas as especializações"),
    ("Мережі", "Redes"),
    ("Будь-яке carregamento", "Qualquer carga de trabalho"),
    ("Низьке", "Baixo"),
    ("Середнexiste", "Médio"),
    ("Середнє", "Médio"),
    ("середнє", "médio"),
    ("Середній", "Médio"),
    ("середній", "médio"),

    # === QR History ===
    ("За mês", "Por mês"),
    ("Успішні", "Com sucesso"),
    ("Для de elevadores", "Para elevadores"),
    ("Для de técnicos", "Para técnicos"),
    ("Período leitura:", "Período de leitura:"),
    ("Exportar в Excel", "Exportar para Excel"),
    ("Очистити історію", "Limpar histórico"),
    ("Rua Centroальна", "Rua Central"),
    ("Rua Бічна", "Rua Lateral"),
    ("Ківmasнко", "Kovalenko"),
    ("Марія Сидоренко", "Maria Sidorenko"),
    ("Петро Іваненко", "Pedro Ivanenko"),

    # === Common remaining ===
    ("Розклад", "Calendário"),
    ("розклад", "calendário"),
    ("Реальний час", "Tempo real"),
    ("реальному часі", "tempo real"),
    ("Управління", "Gestão"),
    ("управління", "gestão"),
    ("терміновий", "urgente"),
    ("терміновi", "urgentes"),
    ("Терміново", "Urgente"),
    ("терміновий", "urgente"),
    ("Терміновий", "Urgente"),
    ("неактивний", "inativo"),
    ("Неактивний", "Inativo"),
    ("неактивна", "inativa"),
    ("Неактивна", "Inativa"),
    ("активний", "ativo"),
    ("Активний", "Ativo"),
    ("активна", "ativa"),
    ("Активна", "Ativa"),
    ("Онлайн", "Online"),
    ("онлайн", "online"),
    ("Офлайн", "Offline"),
    ("офлайн", "offline"),
    ("Зайнятий", "Ocupado"),
    ("зайнятий", "ocupado"),
    ("Зайнята", "Ocupada"),
    ("зайнята", "ocupada"),
    ("Порожній", "Vazio"),
    ("порожній", "vazio"),
    ("Доступний", "Disponível"),
    ("доступний", "disponível"),
    ("Доступна", "Disponível"),
    ("доступна", "disponível"),
    ("Доступно", "Disponível"),
    ("доступно", "disponível"),
    ("Доступні", "Disponíveis"),
    ("доступні", "disponíveis"),
    ("Недоступний", "Indisponível"),
    ("недоступний", "indisponível"),
    ("Закрити", "Fechar"),
    ("закрити", "fechar"),
    ("Скасувати", "Cancelar"),
    ("скасувати", "cancelar"),
    ("Додати", "Adicionar"),
    ("додати", "adicionar"),
    ("Видалити", "Eliminar"),
    ("видалити", "eliminar"),
    ("Редагувати", "Editar"),
    ("редагувати", "editar"),
    ("Зберегти", "Guardar"),
    ("зберегти", "guardar"),
    ("Скопіювати", "Copiar"),
    ("скопіювати", "copiar"),
    ("Надіслати", "Enviar"),
    ("надіслати", "enviar"),
    ("Завантажити", "Descarregar"),
    ("завантажити", "descarregar"),
    ("Оновити", "Atualizar"),
    ("оновити", "atualizar"),
    ("Перезавантажити", "Recarregar"),
    ("перезавантажити", "recarregar"),
    ("Підтвердити", "Confirmar"),
    ("підтвердити", "confirmar"),
    ("Відхилити", "Rejeitar"),
    ("відхилити", "rejeitar"),
    ("Переглянути", "Visualizar"),
    ("переглянути", "visualizar"),
    ("Призначити", "Atribuir"),
    ("призначити", "atribuir"),
    ("призначено", "atribuído"),
    ("Призначено", "Atribuído"),
    ("Фільтр", "Filtro"),
    ("фільтр", "filtro"),
    ("Пошук", "Pesquisa"),
    ("пошук", "pesquisa"),
    ("Знайти", "Encontrar"),
    ("знайти", "encontrar"),
    ("Сортування", "Ordenação"),
    ("сортування", "ordenação"),
    ("Сторінка", "Página"),
    ("сторінка", "página"),
    ("Наступна", "Próxima"),
    ("наступна", "próxima"),
    ("Попередня", "Anterior"),
    ("попередня", "anterior"),
    ("Повернутися", "Voltar"),
    ("повернутися", "voltar"),
    ("Продовжити", "Continuar"),
    ("продовжити", "continuar"),
    ("Поновити", "Renovar"),
    ("поновити", "renovar"),
    ("Деталі", "Detalhes"),
    ("деталі", "detalhes"),
    ("Додаткова", "Adicional"),
    ("додаткова", "adicional"),
    ("Інформація", "Informação"),
    ("інформація", "informação"),
    ("Опис", "Descrição"),
    ("опис", "descrição"),
    ("Назва", "Nome"),
    ("назва", "nome"),
    ("Кількість", "Quantidade"),
    ("кількість", "quantidade"),
    ("Вартість", "Valor"),
    ("вартість", "valor"),
    ("Сума", "Total"),
    ("сума", "total"),
    ("Код", "Código"),
    ("Тип", "Tipo"),
    ("тип", "tipo"),
    ("Стан", "Estado"),
    ("стан", "estado"),
    ("Статус", "Estado"),
    ("статус", "estado"),
    ("Дата", "Data"),
    ("дата", "data"),
    ("Час", "Hora"),
    ("час", "hora"),
    ("Дій", "Ações"),
    ("дій", "ações"),
    ("Дія", "Ação"),
    ("дія", "ação"),
    ("Рядок", "Linha"),
    ("рядок", "linha"),
    ("Черга", "Fila"),
    ("черга", "fila"),
    ("Очікування", "Espera"),
    ("очікування", "espera"),
    ("Завдання", "Tarefa"),
    ("завдання", "tarefa"),
    ("завдань", "tarefas"),
    ("Звіт", "Relatório"),
    ("звіт", "relatório"),
    ("звіти", "relatórios"),
    ("Звіти", "Relatórios"),
    ("Звітів", "Relatórios"),
    ("Протокол", "Protocolo"),
    ("протокол", "protocolo"),
    ("Журнал", "Registo"),
    ("журнал", "registo"),
    ("Помилка", "Erro"),
    ("помилка", "erro"),
    ("Помилок", "Erros"),
    ("помилок", "erros"),
    ("Успіх", "Sucesso"),
    ("успіх", "sucesso"),
    ("Попередження", "Aviso"),
    ("попередження", "aviso"),
    ("Сповіщення", "Notificação"),
    ("сповіщення", "notificação"),
    ("Повідомлення", "Mensagem"),
    ("повідомлення", "mensagem"),
    ("Підтвердження", "Confirmação"),
    ("підтвердження", "confirmação"),
    ("Запит", "Pedido"),
    ("запит", "pedido"),
    ("Відповідь", "Resposta"),
    ("відповідь", "resposta"),
    ("Запис", "Registo"),
    ("запис", "registo"),
    ("Записи", "Registos"),
    ("записи", "registos"),
    ("Плановий", "Planeado"),
    ("плановий", "planeado"),
    ("Планова", "Planeada"),
    ("планова", "planeada"),
    ("Регулярний", "Regular"),
    ("регулярний", "regular"),
    ("Строковий", "Prazo"),
    ("строковий", "prazo"),
    ("Термін", "Prazo"),
    ("термін", "prazo"),
    ("Прострочений", "Em atraso"),
    ("прострочений", "em atraso"),
    ("Новий", "Novo"),
    ("новий", "novo"),
    ("нового", "novo"),
    ("нові", "novos"),
    ("Нові", "Novos"),
]

files = sorted(glob.glob("pages/**/*.html", recursive=True))
total_replacements = 0
total_files = 0
files_with_changes = []

for filepath in files:
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception as e:
        print(f"ERROR reading {filepath}: {e}")
        continue

    original = content
    replacements = 0

    for uk, pt in FIXES6:
        count = content.count(uk)
        if count > 0:
            content = content.replace(uk, pt)
            replacements += count

    if content != original:
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            files_with_changes.append((filepath, replacements))
            total_replacements += replacements
            total_files += 1
        except Exception as e:
            print(f"ERROR writing {filepath}: {e}")

print(f"\n{'='*60}")
print(f"PASS 6: {total_files} files changed, {total_replacements} replacements")
print(f"{'='*60}")
for fp, count in files_with_changes:
    print(f"  {count:4d}  {fp}")
