import glob, re

files = glob.glob('pages/**/*.html', recursive=True)

FIXES = [
    # === Backup file ===
    ("Gestão Elevadorами", "Gestão de Elevadores"),
    ("Неактивні", "Inativos"),
    ("Pesquisar за назвою ou endereço", "Pesquisar por nome ou endereço"),
    ("Todas municípioи", "Todos os municípios"),
    ("Осeння inspeção", "Última inspeção"),
    ("Visualização інформації про elevador", "Visualização de informações do elevador"),
    ("Técnicos дані", "Dados técnicos"),

    # === tools.html ===
    ("не há de ferramentas, які потребують негайного поповнення", "não há ferramentas que necessitem reposição imediata"),
    ("Não há de ferramentas, які потребують негайного поповнення", "Não há ferramentas que necessitem reposição imediata"),
    ("Leitura ferramentaу", "Leitura da ferramenta"),
    ("Aponte a câmara на QR-code ferramentaу", "Aponte a câmara para o QR-code da ferramenta"),
    ("Або introduza ID вручну", "Ou introduza o ID manualmente"),
    ("ID ferramentaу", "ID da ferramenta"),
    ("Видача ferramentaу", "Entrega da ferramenta"),
    ("Інструмент *", "Ferramenta *"),
    ("ferramentaу", "da ferramenta"),
    ("ferramentam", "das ferramentas"),

    # === reports.html ===
    ("Швидка estatísticas", "Estatísticas rápidas"),
    ("Período relatório", "Período do relatório"),
    ("Aplicar período", "Aplicar período"),
    ("Total priде valores", "Total de valores"),
    ("Total priде", "Total de"),
    ("Показник", "Indicador"),
    ("Поточний період", "Período atual"),
    ("Anterior período", "Período anterior"),
    ("Зміна", "Variação"),

    # === ar-helper.html ===
    ("Selecione модель", "Selecione o modelo"),
    ("Aponte a câmara на elevador ou робоче ambiente", "Aponte a câmara para o elevador ou ambiente de trabalho"),
    ("Selecione компонент para visualizaçãoу детmasй", "Selecione um componente para visualizar detalhes"),
    ("visualizaçãoу детmasй", "visualizar detalhes"),
    ("title=\"Збільшити\"", "title=\"Aproximar\""),
    ("title=\"Зменшити\"", "title=\"Afastar\""),
    ("title=\"Оберeти\"", "title=\"Rodar\""),
    ("title=\"Пауза\"", "title=\"Pausa\""),
    ("Керівництва e documentoація", "Manuais e documentação"),
    ("documentoація", "documentação"),

    # === qr-management common ===
    ("Orçamentos (Створити)", "Orçamentos (Criar)"),
    ("Selecione конкретне atribuição dependendoо від tipoу", "Selecione a atribuição específica dependendo do tipo"),
    ("dependendoо від tipoу", "dependendo do tipo"),
    ("placeholder=\"ПІБ\"", "placeholder=\"Nome completo\""),
    ("Електрик", "Eletricista"),
    ("електрик", "eletricista"),
    ("Механік", "Mecânico"),
    ("механік", "mecânico"),
    ("Інженер", "Engenheiro"),
    ("інженер", "engenheiro"),
    ("Універсал", "Polivalente"),
    ("універсал", "polivalente"),
    ("Detalhes локації", "Detalhes da localização"),

    # === qr-analytics ===
    ("По tipos", "Por tipo"),
    ("Mapa de calor de atividade leituras по do diaх da semana e horas", "Mapa de calor de leituras por dia da semana e hora"),
    ("leituras по do diaх da semana e horas", "leituras por dia da semana e hora"),
    ("Розподіл по tipos de QR-codes", "Distribuição por tipo de QR-codes"),
    ("Rozподіл по tipos", "Distribuição por tipo"),
    ("Estatísticas по tipos", "Estatísticas por tipo"),
    ("Top utilizувачі", "Top utilizadores"),
    ("utilizувачі", "utilizadores"),
    ("utilizувач", "utilizador"),
    ("Олексій Kovalenko", "Oleksiy Kovalenko"),
    ("Іван Петренко", "Ivan Petrenko"),
    ("Інші utilizувачі", "Outros utilizadores"),

    # === qr-batch ===
    ("Деativar", "Desativar"),
    ("Açõesсний до", "Válido até"),
    ("Меeдані", "Metadados"),
    ("Вchaveити imagem de QR-codes", "Incluir imagem dos QR-codes"),
    ("Стиснути ficheiro (ZIP)", "Comprimir ficheiro (ZIP)"),
    ("Додаткові опції", "Opções adicionais"),
    ("Поля para експорту", "Campos para exportação"),

    # === qr-generator ===
    ("Конкретне atribuição QR", "Atribuição específica do QR"),
    ("Do utilizador дані", "Dados do utilizador"),
    ("текст ou інші дані", "texto ou outros dados"),
    ("Для спеціальних tipoів de QR-codes", "Para tipos especiais de QR-codes"),
    ("Колір do QR-code", "Cor do QR-code"),
    ("Додаткові параметри", "Parâmetros adicionais"),
    ("Adicionar логоtipo", "Adicionar logótipo"),
    ("Adicionar текст", "Adicionar texto"),

    # === ai-assistant ===
    ("В системі encontrado apenas o português do Brasil (pt-BR)", "O sistema encontrou apenas o português do Brasil (pt-BR)"),
    ("В системі encontrado apenas", "O sistema encontrou apenas"),
    ("'Ви'", "'Você'"),
    ("Будь ласка, опишіть вашу ситуацію", "Por favor, descreva a sua situação"),
    ("Análiseую", "A analisar"),
    ("Юридична консультація", "Consulta jurídica"),
    ("Щось пішло не eк", "Algo correu mal"),
    ("Erro з'ligação desde servidorом", "Erro de ligação com o servidor"),
    ("servidorом", "servidor"),

    # === tasks.html ===
    ("será відображено ваші tarefas у вигляді calendárioя", "as suas tarefas serão apresentadas em formato de calendário"),
    ("calendárioя", "calendário"),
    ("Emergência ситуація", "Situação de emergência"),
    ("Digite назву tarefas", "Digite o título da tarefa"),
    ("Selecione категорію", "Selecione a categoria"),
    ("Чистka e de manutenção", "Limpeza e manutenção"),
    ("Чистка e de manutenção", "Limpeza e manutenção"),
    ("Função ство", "Função de cria"),
    ("de tarefas acessoна através de головну pa", "de tarefas disponível através da página principal"),
    ("acessoна через головну", "disponível através da principal"),
    ("Розпоchatи", "Iniciar"),
    ("Tarefas розпоchatо", "Tarefas iniciadas"),
    ("розпоchatо", "iniciadas"),

    # === dispatcher/support ===
    ("Ваша função:", "A sua função:"),
    ("Мої recentes pedidoи", "Os meus pedidos recentes"),
    ("recentes pedidoи", "pedidos recentes"),
    ("Sistema não guarda atribuição se технік já tem 3 ativos tarefas", "O sistema não guarda a atribuição se o técnico já tiver 3 tarefas ativas"),
    ("TKT-2026-001: Notificações não приходять", "TKT-2026-001: Notificações não chegam"),
    ("Пересeли надходити email-notificações про novos pedidos", "Deixei de receber notificações por email sobre novos pedidos"),
    ("Пересeли надходити", "Deixei de receber"),
    ("Horaті pedidoання", "Histório de pedidos"),
    ("Vá para до розділу", "Aceda à secção"),
    ("знайдіть потрібну o pedido e clique em кнопку", "encontre o pedido pretendido e clique em"),
    ("знайдіть потрібну", "encontre o pretendido"),
    ("кнопку", "botão"),

    # === dispatcher/dashboard ===
    ("Ordenar: Сeрі споchatку", "Ordenar: dos mais antigos"),
    ("Сeрі споchatку", "dos mais antigos"),
    ("Швидкий inspeção", "Inspeção rápida"),
    ("Relatório по do técnicoх", "Relatório por técnico"),
    ("Аварійний", "Emergência"),
    ("Нове atribuição", "Nova atribuição"),
    ("Крайній prazo *", "Prazo limite *"),
    ("Додаткові notas", "Notas adicionais"),
    ("Сповістити cliente", "Notificar cliente"),

    # === dispatcher/settings ===
    ("Gestão вашим pessoal perfil e configurações", "Gerir o seu perfil pessoal e configurações"),
    ("Tipoи de notificações", "Tipos de notificações"),
    ("Завершення de tarefas", "Conclusão de tarefas"),
    ("De emergência ситуації", "Situações de emergência"),
    ("Спpessoas отримання", "Formas de receber"),
    ("В системі", "No sistema"),
    ("Gerais configurações do sistema e інтерфейсу", "Configurações gerais do sistema e interface"),
    ("Idioma інтерфейсу", "Idioma da interface"),
    ("інтерфейсу", "da interface"),
    ("інтерфейс", "interface"),

    # === Common remaining Ukrainian words ===
    ("Виконано", "Concluído"),
    ("виконано", "concluído"),
    ("Кваліфікація", "Qualificação"),
    ("кваліфікація", "qualificação"),
    ("Навички", "Competências"),
    ("навички", "competências"),
    ("Завантаження", "Carregamento"),
    ("завантаження", "carregamento"),
    ("Рейтинг", "Avaliação"),
    ("рейтинг", "avaliação"),
    ("Відгук", "Avaliação"),
    ("відгук", "avaliação"),
    ("Коментар", "Comentário"),
    ("коментар", "comentário"),
    ("Коментарі", "Comentários"),
    ("коментарі", "comentários"),
    ("Підрозділ", "Departamento"),
    ("підрозділ", "departamento"),
    ("Власник", "Proprietário"),
    ("власник", "proprietário"),
    ("Орендар", "Arrendatário"),
    ("орендар", "arrendatário"),
    ("Мешканець", "Residente"),
    ("мешканець", "residente"),
    ("Адреса", "Endereço"),
    ("адреса", "endereço"),
    ("Поверх", "Andar"),
    ("поверх", "andar"),
    ("Квартира", "Apartamento"),
    ("квартира", "apartamento"),
    ("Будинок", "Edifício"),
    ("будинок", "edifício"),
    ("Район", "Zona"),
    ("район", "zona"),
    ("Вулиця", "Rua"),
    ("вулиця", "rua"),
    ("Номер", "Número"),
    ("номер", "número"),
    ("Серійний", "Série"),
    ("серійний", "série"),
    ("Виробник", "Fabricante"),
    ("виробник", "fabricante"),
    ("Модель", "Modelo"),
    ("модель", "modelo"),
    ("Вантажопідйомність", "Capacidade de carga"),
    ("вантажопідйомність", "capacidade de carga"),
    ("Швидкість", "Velocidade"),
    ("швидкість", "velocidade"),
    ("Зупинок", "Paragens"),
    ("зупинок", "paragens"),
    ("Зупинка", "Paragem"),
    ("зупинка", "paragem"),
    ("Ліцензія", "Licença"),
    ("ліцензія", "licença"),
    ("Сертифікат", "Certificado"),
    ("сертифікат", "certificado"),
    ("Страховка", "Seguro"),
    ("страховка", "seguro"),
    ("Договір", "Contrato"),
    ("договір", "contrato"),
    ("Гарантія", "Garantia"),
    ("гарантія", "garantia"),
    ("Термін дії", "Prazo de validade"),
    ("Дата встановлення", "Data de instalação"),
    ("Дата виготовлення", "Data de fabrico"),
    ("Несправності", "Avarias"),
    ("несправності", "avarias"),
    ("Несправність", "Avaria"),
    ("несправність", "avaria"),
    ("Планові", "Planeados"),
    ("планові", "planeados"),
    ("Позапланові", "Não planeados"),
    ("позапланові", "não planeados"),
    ("Потребують поповнення", "Necessitam reposição"),
    ("потребують поповнення", "necessitam reposição"),
    ("Поповнення", "Reposição"),
    ("поповнення", "reposição"),
    ("Розміщення", "Localização"),
    ("розміщення", "localização"),
    ("Підтверджено", "Confirmado"),
    ("підтверджено", "confirmado"),
    ("Відхилено", "Rejeitado"),
    ("відхилено", "rejeitado"),
    ("Призначено", "Atribuído"),
    ("призначено", "atribuído"),
    ("Очікується", "Pendente"),
    ("очікується", "pendente"),
    ("Дефект", "Defeito"),
    ("дефект", "defeito"),
    ("Несправний", "Avariado"),
    ("несправний", "avariado"),
    ("Справний", "A funcionar"),
    ("справний", "a funcionar"),
    ("Аварійний виклик", "Chamada de emergência"),
    ("аварійний виклик", "chamada de emergência"),
    ("Параметри", "Parâmetros"),
    ("параметри", "parâmetros"),
    ("Налаштування", "Configurações"),
    ("налаштування", "configurações"),
    ("Профіль", "Perfil"),
    ("профіль", "perfil"),
    ("Вихід", "Sair"),
    ("вихід", "saída"),
    ("Довідка", "Ajuda"),
    ("довідка", "ajuda"),
    ("Підтримка", "Suporte"),
    ("підтримка", "suporte"),
    ("Повідомлення", "Mensagem"),
    ("повідомлення", "mensagem"),
    ("Нотатки", "Notas"),
    ("нотатки", "notas"),
    ("Результати", "Resultados"),
    ("результати", "resultados"),
    ("Висновок", "Conclusão"),
    ("висновок", "conclusão"),
    ("Рекомендації", "Recomendações"),
    ("рекомендації", "recomendações"),
    ("Прикріпити", "Anexar"),
    ("прикріпити", "anexar"),
    ("Прикріплення", "Anexo"),
    ("прикріплення", "anexo"),
    ("Надіслати", "Enviar"),
    ("надіслати", "enviar"),
    ("Отримано", "Recebido"),
    ("отримано", "recebido"),
    ("Відправлено", "Enviado"),
    ("відправлено", "enviado"),
]

total = 0
changed = 0
for fpath in files:
    with open(fpath, encoding='utf-8') as f:
        content = f.read()
    new = content
    for uk, pt in FIXES:
        new = new.replace(uk, pt)
    if new != content:
        with open(fpath, 'w', encoding='utf-8') as f:
            f.write(new)
        n = sum(content.count(uk) for uk, pt in FIXES if content.count(uk) > 0)
        total += n
        changed += 1
        print(f"  {fpath}: {n}")

print(f"\nTotal: {total} replacements in {changed} files")
