#!/bin/bash
# Ukrainian → Portuguese (pt-PT) translation for FestLift client pages
# Generated: 2026-05-01

FILES="/workspaces/deapseak/pages/client/dashboard.html \
       /workspaces/deapseak/pages/client/requests.html \
       /workspaces/deapseak/pages/client/my-lifts.html \
       /workspaces/deapseak/pages/client/notifications.html \
       /workspaces/deapseak/pages/client/orcamentos.html \
       /workspaces/deapseak/pages/client/profile.html \
       /workspaces/deapseak/pages/client/history.html \
       /workspaces/deapseak/pages/client/invoices.html \
       /workspaces/deapseak/pages/client/settings.html \
       /workspaces/deapseak/pages/client/support.html \
       /workspaces/deapseak/pages/client/tickets.html \
       /workspaces/deapseak/pages/client/documentation.html \
       /workspaces/deapseak/pages/client/ai-predictions.html"

sed -i \
  -e 's|Клієнт - Головна|Cliente - Início|g' \
  -e 's|Клієнт - Мої заявки|Cliente - Os meus pedidos|g' \
  -e 's|Клієнт - Рахунки|Cliente - Faturas|g' \
  -e 's|Клієнт - Історія обслуговування|Cliente - Histórico de manutenção|g' \
  -e 's|Сповіщення - Клієнт|Notificações - Cliente|g' \
  -e 's|Perfil - Клієнт|Perfil - Cliente|g' \
  -e 's|Suporte - Клієнт|Suporte - Cliente|g' \
  -e 's|Мої звернення - Cliente|Os meus tickets - Cliente|g' \
  -e 's|AI Прогнозування - Мої ліфти|Previsões AI - Os meus elevadores|g' \
  -e 's|title="Сповіщення"|title="Notificações"|g' \
  -e 's|title="Sповіщення"|title="Notificações"|g' \
  -e 's|title="Вийти"|title="Sair"|g' \
  -e 's|title="Переглянути"|title="Ver"|g' \
  -e 's|title="Закрити"|title="Fechar"|g' \
  -e 's|title="Скасувати заявку"|title="Cancelar pedido"|g' \
  -e 's|title="Оцінити"|title="Avaliar"|g' \
  -e 's|title="Деталі"|title="Detalhes"|g' \
  -e 's|title="Замовити ТО"|title="Encomendar manutenção"|g' \
  -e 's|placeholder="Pesquisar заявок..."|placeholder="Pesquisar pedidos..."|g' \
  -e 's|placeholder="Pesquisar сповіщень..."|placeholder="Pesquisar notificações..."|g' \
  -e 's|placeholder="Введіть поточний пароль"|placeholder="Introduza a palavra-passe atual"|g' \
  -e 's|placeholder="Мінімум 8 символів"|placeholder="Mínimo 8 caracteres"|g' \
  -e 's|placeholder="Повторіть новий пароль"|placeholder="Repita a nova palavra-passe"|g' \
  -e 's|placeholder="Короткий опис проблеми"|placeholder="Descrição breve do problema"|g' \
  -e 's|placeholder="Коротко опишіть проблему"|placeholder="Descreva brevemente o problema"|g' \
  -e 's|placeholder="Детально опишіть проблему або запит..."|placeholder="Descreva detalhadamente o problema ou pedido..."|g' \
  -e 's|placeholder="Детально опишіть вашу проблему або запитання..."|placeholder="Descreva detalhadamente o seu problema ou questão..."|g' \
  -e 's|placeholder="Детально опишіть ваше звернення..."|placeholder="Descreva detalhadamente o seu ticket..."|g' \
  -e 's|placeholder="Напишіть ваше повідомлення..."|placeholder="Escreva a sua mensagem..."|g' \
  -e 's|placeholder="Короткий опис проблеми" required|placeholder="Descrição breve do problema" required|g' \
  -e 's|Система управління ліфтами v2.1.0\.|Sistema de gestão de elevadores v2.1.0.|g' \
  -e 's|Ви впевнені, що хочете вийти з системи?|Tem a certeza que quer sair do sistema?|g' \
  -e 's|Ви впевнені, що хочете вийти?|Tem a certeza que quer sair?|g' \
  -e 's|Ви впевнені, що хочете вийти з системи|Tem a certeza que quer sair do sistema|g' \
  -e 's|Штучний інтелект аналізує стан ваших ліфтів та прогнозує майбутні поломки|A inteligência artificial analisa o estado dos seus elevadores e prevê avarias futuras|g' \
  -e 's|Темна тема увімкнена|Tema escuro ativado|g' \
  -e 's|Темна тема вимкнена|Tema escuro desativado|g' \
  -e 's|Мої активні звернення|Os meus tickets ativos|g' \
  -e 's|Всі мої звернення|Todos os meus tickets|g' \
  -e 's|Мої звернення|Os meus tickets|g' \
  -e 's|Нове звернення|Novo ticket|g' \
  -e 's|Деталі звернення|Detalhes do ticket|g' \
  -e 's|Список звернень|Lista de tickets|g' \
  -e 's|Всього звернень|Total de tickets|g' \
  -e 's|Звернень не знайдено|Nenhum ticket encontrado|g' \
  -e 's|Не вдалося завантажити звернення|Não foi possível carregar os tickets|g' \
  -e 's|Закрити це звернення?|Fechar este ticket?|g' \
  -e 's|Не вдалося закрити звернення|Não foi possível fechar o ticket|g' \
  -e 's|Помилка при створенні звернення|Erro ao criar o ticket|g' \
  -e 's|Відповідь підтримки:|Resposta do suporte:|g' \
  -e 's|Мої заявки|Os meus pedidos|g' \
  -e 's|Нова заявка|Novo pedido|g' \
  -e 's|Деталі заявки|Detalhes do pedido|g' \
  -e 's|Список заявок|Lista de pedidos|g' \
  -e 's|Всього заявок|Total de pedidos|g' \
  -e 's|Фільтри заявок|Filtros de pedidos|g' \
  -e 's|Заявки будуть завантажені тут|Os pedidos serão carregados aqui|g' \
  -e 's|Створити нову заявку|Criar novo pedido|g' \
  -e 's|Тип заявки \*|Tipo de pedido *|g' \
  -e 's|Ліфт \*|Elevador *|g' \
  -e 's|Заголовок \*|Assunto *|g' \
  -e 's|Детальний опис проблеми \*|Descrição detalhada do problema *|g' \
  -e 's|Детальний опис \*|Descrição detalhada *|g' \
  -e 's|Фотографії (необов'\''язково)|Fotografias (opcional)|g' \
  -e 's|Термінова заявка (потребує негайної уваги)|Pedido urgente (requer atenção imediata)|g' \
  -e 's|Відправити заявку|Enviar pedido|g' \
  -e 's|Завантажити звіт|Descarregar relatório|g' \
  -e 's|Чат з техніком|Chat com técnico|g' \
  -e 's|Максимум 5 фотографій|Máximo 5 fotografias|g' \
  -e 's|Максимум 5 фото, до 5MB кожне|Máximo 5 fotos, até 5MB cada|g' \
  -e 's|перевищує 5MB і не буде доданий|excede 5MB e não será adicionado|g' \
  -e 's|Заявку успішно створено!|Pedido criado com sucesso!|g' \
  -e 's|Помилка створення заявки|Erro ao criar o pedido|g' \
  -e 's|Скасувати заявку?|Cancelar pedido?|g' \
  -e 's|Заявку буде скасовано. Ця дія незворотна.|O pedido será cancelado. Esta ação é irreversível.|g' \
  -e 's|Скасування можливе лише до початку виконання.|O cancelamento só é possível antes do início da execução.|g' \
  -e 's|Заявку можна скасувати лише до початку виконання|O pedido só pode ser cancelado antes do início da execução|g' \
  -e 's|Неможливо скасувати|Impossível cancelar|g' \
  -e 's|Не призначено|Não atribuído|g' \
  -e 's|Основна інформація|Informação principal|g' \
  -e 's|Функція оцінки техніка буде додана пізніше|Função de avaliação do técnico disponível em breve|g' \
  -e 's|Функція експорту буде додана пізніше|Função de exportação disponível em breve|g' \
  -e 's|Функція пагінації буде додана пізніше|Função de paginação disponível em breve|g' \
  -e 's|Функція завантаження звіту буде додана пізніше|Função de descargar relatório disponível em breve|g' \
  -e 's|Функція чату з техніком буде додана пізніше|Função de chat com técnico disponível em breve|g' \
  -e 's|Оцінити техніка|Avaliar técnico|g' \
  -e 's|Мої рахунки|As minhas faturas|g' \
  -e 's|Деталі рахунку|Detalhes da fatura|g' \
  -e 's|Список рахунків|Lista de faturas|g' \
  -e 's|Filtroи рахунків|Filtros das faturas|g' \
  -e 's|Номер рахунку|Número de fatura|g' \
  -e 's|Термін оплати|Data de vencimento|g' \
  -e 's|Способи оплати|Métodos de pagamento|g' \
  -e 's|Оплата рахунку|Pagamento da fatura|g' \
  -e 's|Загальна сума|Total geral|g' \
  -e 's|Поточний місяць|Mês atual|g' \
  -e 's|Минулий місяць|Mês anterior|g' \
  -e 's|Цей квартал|Este trimestre|g' \
  -e 's|Цей рік|Este ano|g' \
  -e 's|Весь період|Todo o período|g' \
  -e 's|Дата (новіші)|Data (mais recentes)|g' \
  -e 's|Дата (старіші)|Data (mais antigas)|g' \
  -e 's|Сума (більші)|Valor (maior)|g' \
  -e 's|Сума (менші)|Valor (menor)|g' \
  -e 's|Завантажити PDF|Descarregar PDF|g' \
  -e 's|Оплатити|Pagar|g' \
  -e 's|Прострочено|Em atraso|g' \
  -e 's|Історія обслуговування|Histórico de manutenção|g' \
  -e 's|Filtroи історії|Filtros do histórico|g' \
  -e 's|Останні 30 днів|Últimos 30 dias|g' \
  -e 's|Останні 3 місяці|Últimos 3 meses|g' \
  -e 's|Останній рік|Último ano|g' \
  -e 's|Вся історія|Todo o histórico|g' \
  -e 's|Тип події:|Tipo de evento:|g' \
  -e 's|Всі події|Todos os eventos|g' \
  -e 's|Аварійне обслуговування|Manutenção de emergência|g' \
  -e 's|Всього подій|Total de eventos|g' \
  -e 's|Технічних обслуговувань|Manutenções técnicas|g' \
  -e 's|Середній час реакції|Tempo médio de resposta|g' \
  -e 's|Середня оцінка|Avaliação média|g' \
  -e 's|Хронологія подій|Cronologia de eventos|g' \
  -e 's|Детальна статистика|Estatísticas detalhadas|g' \
  -e 's|Розподіл по типах подій|Distribuição por tipos de evento|g' \
  -e 's|Частота обслуговування|Frequência de manutenção|g' \
  -e 's|Оцінки якості|Avaliações de qualidade|g' \
  -e 's|Витрати на обслуговування|Custos de manutenção|g' \
  -e 's|Guardar у форматі PDF|Guardar em formato PDF|g' \
  -e 's|Guardar у форматі Excel|Guardar em formato Excel|g' \
  -e 's|Роздрукувати історію|Imprimir histórico|g' \
  -e 's|Служба підтримки|Serviço de suporte|g' \
  -e 's|Оберіть категорію запитання|Escolha a categoria da questão|g' \
  -e 's|Технічні питання|Questões técnicas|g' \
  -e 's|Проблеми з ліфтами, ремонт, обслуговування|Problemas com elevadores, reparação, manutenção|g' \
  -e 's|Питання щодо рахунків, оплати, тарифів|Questões sobre faturas, pagamentos, tarifas|g' \
  -e 's|Термінова допомога, аварійні виклики|Ajuda urgente, chamadas de emergência|g' \
  -e 's|Загальні питання|Questões gerais|g' \
  -e 's|Інша інформація, документація, довідка|Outras informações, documentação, ajuda|g' \
  -e 's|Контактні методи|Métodos de contacto|g' \
  -e 's|Пн-Пт: 9:00-18:00|Seg-Sex: 9:00-18:00|g' \
  -e 's|Зателефонувати|Ligar|g' \
  -e 's|Відповідь протягом 24 год|Resposta em 24 horas|g' \
  -e 's|Написати|Escrever|g' \
  -e 's|Онлайн-чат з підтримкою|Chat online com suporte|g' \
  -e 's|Онлайн-чат|Chat online|g' \
  -e 's|Ми онлайн зараз|Estamos online agora|g' \
  -e 's|Швидка допомога|Ajuda rápida|g' \
  -e 's|Почати чат|Iniciar chat|g' \
  -e 's|Форма звернення|Formulário de ticket|g' \
  -e 's|Створення тикету|Criar ticket|g' \
  -e 's|Системне відстеження|Rastreamento do sistema|g' \
  -e 's|Створити тикет|Criar ticket|g' \
  -e 's|База знань|Base de conhecimento|g' \
  -e 's|Часті запитання|Perguntas frequentes|g' \
  -e 's|Пов'\''язаний ліфт (якщо є)|Elevador associado (se aplicável)|g' \
  -e 's|Оберіть ліфт\.\.\.|Escolha o elevador...|g' \
  -e 's|Ліфт №1 - Rua Центральна, 12|Elevador №1 - Rua Central, 12|g' \
  -e 's|Ліфт №2 - Rua Центральна, 12|Elevador №2 - Rua Central, 12|g' \
  -e 's|Ліфт №3 - Rua Головна, 25|Elevador №3 - Rua Principal, 25|g' \
  -e 's|Adicionar файл|Adicionar ficheiro|g' \
  -e 's|Обрати файл|Escolher ficheiro|g' \
  -e 's|Максимальний розмір: 5MB (jpg, png, pdf)|Tamanho máximo: 5MB (jpg, png, pdf)|g' \
  -e 's|Термінове звернення (відповідь протягом 2 годин)|Ticket urgente (resposta em 2 horas)|g' \
  -e 's|Надіслати звернення|Enviar ticket|g' \
  -e 's|Завершити чат|Terminar chat|g' \
  -e 's|Дзвінок в підтримку: +351 800 502 020|Ligar para suporte: +351 800 502 020|g' \
  -e 's|Функція чату буде доступна незабаром|Função de chat disponível em breve|g' \
  -e 's|Тикет успішно відправлений!|Ticket enviado com sucesso!|g' \
  -e 's|пустий запит|pesquisa vazia|g' \
  -e 's|Повідомлення відправлено|Mensagem enviada|g' \
  -e 's|Чат завершено|Chat terminado|g' \
  -e 's|Коментар додано|Comentário adicionado|g' \
  -e 's|Adicionar коментар|Adicionar comentário|g' \
  -e 's|Мій профіль|O meu perfil|g' \
  -e 's|Редагування профілю|Editar perfil|g' \
  -e 's|Контактна інформація|Informações de contacto|g' \
  -e 's|Повне ім'\''я|Nome completo|g' \
  -e 's|Клієнт Клієнтович|Cliente Exemplo|g' \
  -e 's|ТОВ "Приклад"|Empresa Exemplo|g' \
  -e 's|м\. Lisboa, Rua Прикладна, 123|Lisboa, Rua Exemplo, 123|g' \
  -e 's|Lisboaська область|Distrito de Lisboa|g' \
  -e 's|Поштовий індекс|Código postal|g' \
  -e 's|Активних заявок|Pedidos ativos|g' \
  -e 's|Років з нами|Anos connosco|g' \
  -e 's|Зміна пароля|Alterar palavra-passe|g' \
  -e 's|Поточний пароль|Palavra-passe atual|g' \
  -e 's|Підтвердження нового пароля|Confirmar nova palavra-passe|g' \
  -e 's|Підтвердження пароля|Confirmar palavra-passe|g' \
  -e 's|Мінімум 8 символів, включаючи цифри та літери|Mínimo 8 caracteres, incluindo números e letras|g' \
  -e 's|Новий пароль|Nova palavra-passe|g' \
  -e 's|Змінити пароль|Alterar palavra-passe|g' \
  -e 's|Зміна паролю|Alterar palavra-passe|g' \
  -e 's|Завершити всі сесії?|Terminar todas as sessões?|g' \
  -e 's|Всі сесії завершено|Todas as sessões terminadas|g' \
  -e 's|Аккаунт буде видалено|Conta será eliminada|g' \
  -e 's|Файл занадто великий (максимум 2 МБ)|Ficheiro demasiado grande (máximo 2 MB)|g' \
  -e 's|Не вдалося завантажити аватар|Não foi possível carregar o avatar|g' \
  -e 's|Аватар збережено локально|Avatar guardado localmente|g' \
  -e 's|Аватар оновлено|Avatar atualizado|g' \
  -e 's|Пароль має бути не менше 8 символів|A palavra-passe deve ter no mínimo 8 caracteres|g' \
  -e 's|Новий пароль має бути не менше 8 символів|A nova palavra-passe deve ter no mínimo 8 caracteres|g' \
  -e 's|Паролі не співпадають|As palavras-passe não coincidem|g' \
  -e 's|Збереження\.\.\.|A guardar...|g' \
  -e 's|Пароль успішно змінено|Palavra-passe alterada com sucesso|g' \
  -e 's|Помилка зміни пароля|Erro ao alterar a palavra-passe|g' \
  -e 's|Помилка з'\''єднання з сервером|Erro de ligação ao servidor|g' \
  -e "s|Помилка з'єднання з сервером|Erro de ligação ao servidor|g" \
  -e "s|Помилка з'єднання|Erro de ligação|g" \
  -e 's|Налаштування сповіщень збережено|Definições de notificações guardadas|g' \
  -e 's|Фото профілю|Foto de perfil|g' \
  -e 's|JPG або PNG, не більше 2 МБ|JPG ou PNG, máximo 2 MB|g' \
  -e 's|Завантажити фото|Carregar foto|g' \
  -e 's|Канали сповіщень|Canais de notificações|g' \
  -e 's|Типи подій|Tipos de eventos|g' \
  -e 's|Аварійні ситуації|Situações de emergência|g' \
  -e 's|Нові рахунки|Novas faturas|g' \
  -e 's|Зміна статусів заявок|Alteração do estado dos pedidos|g' \
  -e 's|Зберегти налаштування сповіщень|Guardar definições de notificações|g' \
  -e 's|НАЛАШТУВАННЯ|DEFINIÇÕES|g' \
  -e 's|Панель клієнта|Painel do cliente|g' \
  -e 's|Дашборд|Início|g' \
  -e 's|>Панель<|>Painel<|g' \
  -e 's|Вітаємо, |Bem-vindo, |g' \
  -e 's|Статус ваших ліфтів:|Estado dos seus elevadores:|g' \
  -e 's|Всі працюють|Todos a funcionar|g' \
  -e 's|Хмарно|Nublado|g' \
  -e 's|Моїх ліфтів|Os meus elevadores|g' \
  -e 's|Детальніше|Ver mais|g' \
  -e 's|Активні заявки|Pedidos ativos|g' \
  -e 's|Останні події|Últimos eventos|g' \
  -e 's|Вся історія|Todo o histórico|g' \
  -e 's|Графік техобслуговування|Calendário de manutenção|g' \
  -e 's|Повний графік|Calendário completo|g' \
  -e 's|Статистика ліфтів|Estatísticas dos elevadores|g' \
  -e 's|Останні заявки|Últimos pedidos|g' \
  -e 's|Всі заявки|Todos os pedidos|g' \
  -e 's|Останні сповіщення|Últimas notificações|g' \
  -e 's|Всі сповіщення|Todas as notificações|g' \
  -e 's|Зв'\''язатися з підтримкою|Contactar suporte|g' \
  -e 's|Зв'\''язатися|Contactar|g' \
  -e 's|Перегляд усіх ліфтів|Ver todos os elevadores|g' \
  -e 's|Перегляд рахунків|Ver faturas|g' \
  -e 's|Детальна інформація про ліфти|Informação detalhada dos elevadores|g' \
  -e 's|Всього ліфтів|Total de elevadores|g' \
  -e 's|Працюють нормально|A funcionar normalmente|g' \
  -e 's|На обслуговуванні|Em manutenção|g' \
  -e 's|Потребують уваги|Requerem atenção|g' \
  -e 's|Пасажирські|Passageiros|g' \
  -e 's|Вантажні|Carga|g' \
  -e 's|Лікарняні|Hospitalares|g' \
  -e 's|Grafік ТО|Calendário de manutenção|g' \
  -e 's|Typи сповіщень:|Tipos de notificações:|g' \
  -e 's|Типи сповіщень:|Tipos de notificações:|g' \
  -e 's|Всього сповіщень|Total de notificações|g' \
  -e 's|Список сповіщень|Lista de notificações|g' \
  -e 's|Configurações сповіщень|Configurações de notificações|g' \
  -e 's|Деталі сповіщення|Detalhes da notificação|g' \
  -e 's|Аварійні сповіщення|Alertas de emergência|g' \
  -e 's|Рахунки та оплата|Faturas e pagamentos|g' \
  -e 's|Спосіб отримання:|Método de receção:|g' \
  -e 's|Email сповіщення|Notificações por Email|g' \
  -e 's|Push-сповіщення|Notificações push|g' \
  -e 's|SMS сповіщення|Notificações SMS|g' \
  -e 's|Guardar налаштування|Guardar definições|g' \
  -e 's|Непрочитані|Não lidas|g' \
  -e 's|Непрочитаних|Não lidas|g' \
  -e 's|Важливі|Importantes|g' \
  -e 's|Важливих|Importantes|g' \
  -e 's|Техобслуговування|Manutenção|g' \
  -e 's|Позначити всі як прочитані|Marcar todas como lidas|g' \
  -e 's|Очистити всі|Limpar todas|g' \
  -e 's|Переглянути деталі|Ver detalhes|g' \
  -e 's|За датою|Por data|g' \
  -e 's|За пріоритетом|Por prioridade|g' \
  -e 's|Загальні рекомендації AI|Recomendações gerais AI|g' \
  -e 's|Завантаження рекомендацій\.\.\.|A carregar recomendações...|g' \
  -e 's|Немає даних для відображення\.|Sem dados para apresentar.|g' \
  -e 's|Спробуйте змінити фільтри або оновити прогнози\.|Tente alterar os filtros ou atualizar as previsões.|g' \
  -e 's|Здорових ліфтів|Elevadores saudáveis|g' \
  -e 's|Критичний стан|Estado crítico|g' \
  -e 's|За ризиком (спочатку високий)|Por risco (maior primeiro)|g' \
  -e 's|За віком ліфта|Por idade do elevador|g' \
  -e 's|За датою останнього ТО|Por data da última manutenção|g' \
  -e 's|Показати:|Mostrar:|g' \
  -e 's|Тільки критичні|Apenas críticos|g' \
  -e 's|Високий ризик|Risco alto|g' \
  -e 's|Середній ризик|Risco médio|g' \
  -e 's|Низький ризик|Risco baixo|g' \
  -e 's|Оновити прогнози|Atualizar previsões|g' \
  -e 's|Критична увага!|Atenção crítica!|g' \
  -e 's|Прострочені інспекції (Порушення закону!)|Inspeções em atraso (Violação da lei!)|g' \
  -e 's|обов'\''язкова щомісячна інспекція для всіх типів ліфтів!|inspeção mensal obrigatória para todos os tipos de elevadores!|g' \
  -e 's|Прострочення може призвести до штрафів від 500€ до 5000€\.|O atraso pode resultar em multas de 500€ a 5000€.|g' \
  -e 's|УВАГА:|ATENÇÃO:|g' \
  -e 's|Старе обладнання|Equipamento antigo|g' \
  -e 's|Все чудово!|Tudo ótimo!|g' \
  -e 's|Стан компонентів|Estado dos componentes|g' \
  -e 's|Рекомендації AI|Recomendações AI|g' \
  -e 's|Перейти до ліфта|Ver elevador|g' \
  -e 's|Двигун|Motor|g' \
  -e 's|Троси|Cabos|g' \
  -e 's|Гальма|Travões|g' \
  -e 's|Двері|Portas|g' \
  -e 's|Система керування|Sistema de controlo|g' \
  -e 's|Системи безпеки|Sistemas de segurança|g' \
  -e 's|ТЕРМІНОВО|URGENTE|g' \
  -e 's|ВАЖЛИВО|IMPORTANTE|g' \
  -e 's|ПЛАНОВЕ|PLANEADO|g' \
  -e 's|Все в порядку|Tudo em ordem|g' \
  -e 's|Ліфт №|Elevador №|g' \
  -e 's|Мої ліфти|Os meus elevadores|g' \
  -e 's|Прогнозування AI|Previsões AI|g' \
  -e 's|Асистент AI|Assistente AI|g' \
  -e 's|Головна|Início|g' \
  -e 's|Заявки|Pedidos|g' \
  -e 's|Рахунки|Faturas|g' \
  -e 's|Історія|Histórico|g' \
  -e 's|Документація|Documentação|g' \
  -e 's|Сповіщення|Notificações|g' \
  -e 's|Підтримка|Suporte|g' \
  -e 's|Профіль|Perfil|g' \
  -e 's|Налаштування|Definições|g' \
  -e 's|Вийти|Sair|g' \
  -e 's|Звернення|Tickets|g' \
  -e 's|>Всі<|>Todos<|g' \
  -e 's|Всі статуси|Todos os estados|g' \
  -e 's|Всі типи|Todos os tipos|g' \
  -e 's|Всі пріоритети|Todas as prioridades|g' \
  -e 's|Всі ліфти|Todos os elevadores|g' \
  -e 's|Всі<|Todos<|g' \
  -e 's|Сортування:|Ordenação:|g' \
  -e 's|За назвою|Por nome|g' \
  -e 's|За статусом|Por estado|g' \
  -e 's|За локацією|Por localização|g' \
  -e 's|Застосувати|Aplicar|g' \
  -e 's|Скинути|Repor|g' \
  -e 's|Статус:|Estado:|g' \
  -e 's|Тип:|Tipo:|g' \
  -e 's|Ліфт:|Elevador:|g' \
  -e 's|Пріоритет:|Prioridade:|g' \
  -e 's|Адреса:|Morada:|g' \
  -e 's|Номер:|Número:|g' \
  -e 's|Категорія:|Categoria:|g' \
  -e 's|Відповідальний:|Responsável:|g' \
  -e 's|Оновлення:|Atualizações:|g' \
  -e 's|Тема:|Assunto:|g' \
  -e 's|Дата:|Data:|g' \
  -e 's|Створено:|Criado em:|g' \
  -e 's|Технік:|Técnico:|g' \
  -e 's|Термін:|Prazo:|g' \
  -e 's|Завершено:|Concluído em:|g' \
  -e 's|Опис:|Descrição:|g' \
  -e 's|Інформація:|Informação:|g' \
  -e 's|Nова|Novo|g' \
  -e 's|Призначено|Atribuído|g' \
  -e 's|В роботі|Em curso|g' \
  -e 's|Відкрите|Aberto|g' \
  -e 's|Відкриті|Abertos|g' \
  -e 's|Вирішено|Resolvido|g' \
  -e 's|Вирішені|Resolvidos|g' \
  -e 's|Закрито|Fechado|g' \
  -e 's|Закриті|Fechados|g' \
  -e 's|Скасовано|Cancelado|g' \
  -e 's|В очікуванні|Pendente|g' \
  -e 's|Оплачено|Pago|g' \
  -e 's|Завершено|Concluído|g' \
  -e 's|Технічне обслуговування|Manutenção técnica|g' \
  -e 's|Планове ТО|Manutenção planeada|g' \
  -e 's|Аварійна ситуація|Situação de emergência|g' \
  -e 's|Аварійне|Emergência|g' \
  -e 's|Технічне питання|Questão técnica|g' \
  -e 's|Загальне питання|Questão geral|g' \
  -e 's|Технічний огляд|Inspeção técnica|g' \
  -e 's|Консультація з техніком|Consulta com técnico|g' \
  -e 's|Консультація|Consulta|g' \
  -e 's|Орсаменто (Кошторис)|Orçamento|g' \
  -e 's|Запит кошторису на роботи|Pedido de orçamento para obras|g' \
  -e 's|Аварійний ремонт|Reparação de emergência|g' \
  -e 's|Терміновий ремонт ліфта|Reparação urgente do elevador|g' \
  -e 's|Заявка на ТО|Pedido de manutenção|g' \
  -e 's|Планове технічне обслуговування|Manutenção técnica planeada|g' \
  -e 's|Технічний|Técnico|g' \
  -e 's|Загальне|Geral|g' \
  -e 's|Оберіть категорію\.\.\.|Escolha a categoria...|g' \
  -e 's|Оберіть тип\.\.\.|Escolha o tipo...|g' \
  -e 's|Критичний 🔴|Crítico 🔴|g' \
  -e 's|Критичний|Crítico|g' \
  -e 's|Високий|Alto|g' \
  -e 's|Середній|Médio|g' \
  -e 's|Baixo|Baixo|g' \
  -e 's|Низький|Baixo|g' \
  -e 's|Категорія \*|Categoria *|g' \
  -e 's|Пріоритет \*|Prioridade *|g' \
  -e 's|Тема \*|Assunto *|g' \
  -e 's|Коротко опишіть проблему|Descreva brevemente o problema|g' \
  -e 's|Детально опишіть ваше звернення\.\.\.|Descreva detalhadamente o seu ticket...|g' \
  -e 's|Відправити|Enviar|g' \
  -e 's|Замовити|Encomendar|g' \
  -e 's|Запланувати|Agendar|g' \
  -e 's|Запитати|Solicitar|g' \
  -e 's|Створити|Criar|g' \
  -e 's|Переглянути|Ver|g' \
  -e 's|Будь ласка, заповніть всі обов'\''язкові поля|Por favor, preencha todos os campos obrigatórios|g' \
  -e 's|Опис відсутній|Sem descrição|g' \
  -e 's|Тема|Assunto|g' \
  -e 's|Категорія|Categoria|g' \
  -e 's|Пріоритет|Prioridade|g' \
  -e 's|Статус|Estado|g' \
  -e 's|Дата|Data|g' \
  -e 's|Дії|Ações|g' \
  -e 's|Опис|Descrição|g' \
  -e 's|Технік|Técnico|g' \
  -e 's|Ремонт|Reparação|g' \
  -e 's|Інспекція|Inspeção|g' \
  -e 's|Ліфт|Elevador|g' \
  -e 's|Місто|Cidade|g' \
  -e 's|Область|Distrito|g' \
  -e 's|Адреса|Morada|g' \
  -e 's|Компанія|Empresa|g' \
  -e 's|Телефон|Telefone|g' \
  -e 's|Ім'\''я \*|Nome *|g' \
  -e 's|Прізвище \*|Apelido *|g' \
  -e 's|Безпека|Segurança|g' \
  -e 's|Ліфтів|Elevadores|g' \
  -e 's|Завантаження ліфтів\.\.\.|A carregar elevadores...|g' \
  -e 's|Ліфтів немає|Sem elevadores|g' \
  -e 's|Завантаження\.\.\.|A carregar...|g' \
  -e 's|Немає даних|Sem dados|g' \
  -e 's|Помилка завантаження|Erro ao carregar|g' \
  -e 's|Помилка з'\''єднання|Erro de ligação|g' \
  -e 's|Période:|Período:|g' \
  -e 's|Período:|Período:|g' \
  -e 's|Sторінка|Página|g' \
  -e 's|Попередня|Anterior|g' \
  -e 's|Наступна|Seguinte|g' \
  -e 's|Друк|Imprimir|g' \
  -e 's|Так, скасувати|Sim, cancelar|g' \
  -e 's|Ні, залишити|Não, manter|g' \
  -e 's|Закрити|Fechar|g' \
  -e 's|Оновити|Atualizar|g' \
  -e 's|Підтримка|Suporte|g' \
  -e 's|Сума|Valor|g' \
  -e 's|Онлайн|Online|g' \
  -e 's|ID заявки|ID do pedido|g' \
  -e 's|Дата створення|Data de criação|g' \
  -e 's|Рек\.|Rec.|g' \
  $FILES

echo "✅ Tradução concluída!"
