from pathlib import Path

TRANSLATIONS = [
    ('Адмін-панель - FestLift', 'Painel Admin - FestLift'),
    ('Адмін дашборд', 'Painel de Administração'),
    ('Диспетчер - Управління призначеннями', 'Operador - Gestão de Atribuições'),
    ('Диспетчер - Моніторинг', 'Operador - Monitorização'),
    ('FestLift - Управління ліфтами', 'FestLift - Gestão de Elevadores'),
    ('QR Система', 'Sistema QR'),
    ('Управління QR', 'Gestão QR'),
    ('Аналітика QR', 'Análise QR'),
    ('Історія сканувань', 'Histórico de Leituras'),
    ('Управління ліфтами', 'Gestão de Elevadores'),
    ('Управління призначеннями', 'Gestão de Atribuições'),
    ('Масове призначення', 'Atribuição em Massa'),
    ('Нове призначення', 'Nova Atribuição'),
    ('Відновити із архіву', 'Restaurar do Arquivo'),
    ('Зведена аналітика', 'Análise Consolidada'),
    ('AI Прогнозування', 'Previsão IA'),
    ('AI Асистент', 'Assistente IA'),
    ('Технічна підтримка', 'Suporte Técnico'),
    ('Email шаблони', 'Modelos de Email'),
    ('Шаблони звітів', 'Modelos de Relatórios'),
    ('Кошторис (Створити)', 'Orçamento (Criar)'),
    ('Кошторис (Список)', 'Orçamento (Lista)'),
    ('Список призначень', 'Lista de Atribuições'),
    ('Звіт продуктивності', 'Relatório de Desempenho'),
    ('Темна тема', 'Tema Escuro'),
    ('Головна', 'Início'),
    ('Налаштування', 'Definições'),
    ('Сповіщення', 'Notificações'),
    ('Підтримка', 'Suporte'),
    ('Аналітика', 'Análise'),
    ('Інспекції', 'Inspecções'),
    ('Документи', 'Documentos'),
    ('Дашборд', 'Painel'),
    ('Моніторинг', 'Monitorização'),
    ('Призначення', 'Atribuições'),
    ('Календар', 'Calendário'),
    ('Адміністратор', 'Administrador'),
    ('Диспетчер', 'Operador'),
    ('Всі статуси', 'Todos os estados'),
    ('В очікуванні', 'Pendente'),
    ('На розгляді', 'Em análise'),
    ('Призначені', 'Atribuídos'),
    ('Завершені', 'Concluídos'),
    ('Скасовані', 'Cancelados'),
    ('Архівовані', 'Arquivados'),
    ('Протерміновані', 'Em Atraso'),
    ('Всі пріоритети', 'Todas as prioridades'),
    ('Всі техніки', 'Todos os técnicos'),
    ('Всі ліфти', 'Todos os elevadores'),
    ('Всі клієнти', 'Todos os clientes'),
    ('Позагарантійний', 'Fora de garantia'),
    ('Гарантійний', 'Em garantia'),
    ('Аварійний', 'Emergência'),
    ('Позаплановий', 'Não planeado'),
    ('Критичний', 'Crítico'),
    ('Високий', 'Alta'),
    ('Середній', 'Média'),
    ('Низький', 'Baixa'),
    ('Активні', 'Activos'),
    ('Активна', 'Activa'),
    ('Активний', 'Activo'),
    ('Відмовив', 'Com falha'),
    ('Несправний', 'Avariado'),
    ('Справний', 'Em bom estado'),
    ('Виконується', 'Em execução'),
    ('Виконано', 'Concluído'),
    ('Закрито', 'Fechado'),
    ('Відхилено', 'Rejeitado'),
    ('Не призначено', 'Não atribuído'),
    ('Призначено', 'Atribuído'),
    ('Очікує', 'Aguarda'),
    ('Весь період', 'Todo o período'),
    ('Цей місяць', 'Este mês'),
    ('Цей тиждень', 'Esta semana'),
    ('Сьогодні', 'Hoje'),
    ('Вчора', 'Ontem'),
    ('Перепризначити протерміновані', 'Reatribuir em atraso'),
    ('Призначити / Змінити', 'Atribuir / Alterar'),
    ('Розпочати роботу', 'Iniciar trabalho'),
    ('Фальшивий виклик', 'Falso alarme'),
    ('Додати користувача', 'Adicionar utilizador'),
    ('Додати ліфт', 'Adicionar elevador'),
    ('Додати запис', 'Adicionar registo'),
    ('Додати клієнта', 'Adicionar cliente'),
    ('Нова заявка', 'Novo pedido'),
    ('Нова інспекція', 'Nova inspecção'),
    ('Новий ліфт', 'Novo elevador'),
    ('Новий звіт', 'Novo relatório'),
    ('Зберегти зміни', 'Guardar alterações'),
    ('Скинути фільтри', 'Repor filtros'),
    ('Повернутись до активних', 'Regressar aos activos'),
    ('Скинути', 'Repor'),
    ('Зберегти', 'Guardar'),
    ('Редагувати', 'Editar'),
    ('Видалити', 'Eliminar'),
    ('Завершити', 'Concluir'),
    ('Підтвердити', 'Confirmar'),
    ('Закрити', 'Fechar'),
    ('Архівувати', 'Arquivar'),
    ('Застосувати', 'Aplicar'),
    ('Повернутись', 'Regressar'),
    ('Відправити', 'Enviar'),
    ('Завантаження...', 'A carregar...'),
    ('Завантажити', 'Descarregar'),
    ('Завантаження', 'A carregar'),
    ('Збереження...', 'A guardar...'),
    ('Зберігаємо', 'A guardar'),
    ('Перегляд', 'Visualizar'),
    ('Оновити', 'Atualizar'),
    ('Відмінити', 'Cancelar'),
    ('Скасувати', 'Cancelar'),
    ('Друкувати', 'Imprimir'),
    ('Надіслати', 'Enviar'),
    ('Призначити', 'Atribuir'),
    ('Довантажити', 'Carregar mais'),
    ('Копіювати', 'Copiar'),
    ('Вставити', 'Colar'),
    ('Всього призначень', 'Total de atribuições'),
    ('Всього заявок', 'Total de pedidos'),
    ('Всього ліфтів', 'Total de elevadores'),
    ('Всього клієнтів', 'Total de clientes'),
    ('Всього користувачів', 'Total de utilizadores'),
    ('Активних заявок', 'Pedidos activos'),
    ('Доходів (грн)', 'Receitas (€)'),
    ('Стан сервера', 'Estado do servidor'),
    ('База даних', 'Base de dados'),
    ('Останні дії', 'Ações recentes'),
    ('Швидкі дії', 'Ações rápidas'),
    ('Швидкий доступ', 'Acesso rápido'),
    ('Управління', 'Gestão'),
    ('Технічне обслуговування', 'Manutenção técnica'),
    ('технічне обслуговування', 'manutenção técnica'),
    ('Обслуговування', 'Manutenção'),
    ('Профілактика', 'Manutenção preventiva'),
    ('Плановий ТО', 'Manutenção planeada'),
    ('Плановий', 'Planeado'),
    ('Ліфти', 'Elevadores'),
    ('Ліфт', 'Elevador'),
    ('ліфти', 'elevadores'),
    ('ліфт', 'elevador'),
    ('Заявки', 'Pedidos'),
    ('Заявка', 'Pedido'),
    ('заявки', 'pedidos'),
    ('заявка', 'pedido'),
    ('Запит', 'Pedido'),
    ('Клієнти', 'Clientes'),
    ('Клієнт', 'Cliente'),
    ('клієнти', 'clientes'),
    ('клієнт', 'cliente'),
    ('Користувачі', 'Utilizadores'),
    ('Користувач', 'Utilizador'),
    ('користувачі', 'utilizadores'),
    ('користувач', 'utilizador'),
    ('Техніки', 'Técnicos'),
    ('Технік', 'Técnico'),
    ('техніки', 'técnicos'),
    ('технік', 'técnico'),
    ('Звіти', 'Relatórios'),
    ('Звіт', 'Relatório'),
    ('звіти', 'relatórios'),
    ('звіт', 'relatório'),
    ('Коментарів поки немає', 'Ainda não há comentários'),
    ('Напишіть коментар', 'Escreva um comentário'),
    ('Написати коментар', 'Escrever um comentário'),
    ('Коментарі', 'Comentários'),
    ('Коментар', 'Comentário'),
    ('коментарі', 'comentários'),
    ('коментар', 'comentário'),
    ('Записи', 'Registos'),
    ('Запис', 'Registo'),
    ('записи', 'registos'),
    ('запис', 'registo'),
    ('Статус', 'Estado'),
    ('статус', 'estado'),
    ('Пріоритет', 'Prioridade'),
    ('пріоритет', 'prioridade'),
    ('Адреса', 'Endereço'),
    ('адреса', 'endereço'),
    ('Місто', 'Cidade'),
    ('Район', 'Bairro'),
    ('Будівля', 'Edifício'),
    ('Поверхів', 'Andares'),
    ('Поверх', 'Andar'),
    ('Локація', 'Localização'),
    ('локація', 'localização'),
    ('Опис проблеми', 'Descrição do problema'),
    ('Опис роботи', 'Descrição do trabalho'),
    ('Опис', 'Descrição'),
    ('опис', 'descrição'),
    ('Назва', 'Nome'),
    ('назва', 'nome'),
    ('Серійний номер', 'Número de série'),
    ('серійний номер', 'número de série'),
    ('Модель', 'Modelo'),
    ('модель', 'modelo'),
    ('Виробник', 'Fabricante'),
    ('Рік встановлення', 'Ano de instalação'),
    ('Дата встановлення', 'Data de instalação'),
    ('Дата реєстрації', 'Data de registo'),
    ('Вартість', 'Valor'),
    ('вартість', 'valor'),
    ('Сума', 'Montante'),
    ('сума', 'montante'),
    ('Ціна', 'Preço'),
    ('ціна', 'preço'),
    ('Роль', 'Função'),
    ('роль', 'função'),
    ('Прізвище', 'Apelido'),
    ('Телефон', 'Telefone'),
    ('Пароль', 'Palavra-passe'),
    ('пароль', 'palavra-passe'),
    ('Логін', 'Login'),
    ('логін', 'login'),
    ('Сесія', 'Sessão'),
    ('Доступ', 'Acesso'),
    ('Права', 'Permissões'),
    ('Сторінок', 'Páginas'),
    ('Сторінка', 'Página'),
    ('сторінка', 'página'),
    ('Ліфтів', 'Elevadores'),
    ('Доходів', 'Receitas'),
    ('Новий користувач зареєстрований', 'Novo utilizador registado'),
    ('Заявка на ТО завершена', 'Pedido de manutenção concluído'),
    ('Ліфт додано до системи', 'Elevador adicionado ao sistema'),
    ('хвилин тому', 'minutos atrás'),
    ('хвилина тому', 'minuto atrás'),
    ('годин тому', 'horas atrás'),
    ('година тому', 'hora atrás'),
    ('днів тому', 'dias atrás'),
    ('день тому', 'dia atrás'),
    ('Оберіть статус', 'Selecione o estado'),
    ('Оберіть', 'Selecione'),
    ('оберіть', 'selecione'),
    ('Виберіть', 'Selecione'),
    ('виберіть', 'selecione'),
    ('Введіть', 'Introduza'),
    ('введіть', 'introduza'),
    ('Заповніть', 'Preencha'),
    ('Не знайдено', 'Não encontrado'),
    ('не знайдено', 'não encontrado'),
    ('Немає даних', 'Sem dados'),
    ('Успішно збережено', 'Guardado com sucesso'),
    ('Успішно!', 'Sucesso!'),
    ('Попередження', 'Aviso'),
    ('Підтвердження', 'Confirmação'),
    ('Помилка', 'Erro'),
    ('помилка', 'erro'),
    ('Увага', 'Atenção'),
    ('Деталі запиту', 'Detalhes do pedido'),
    ('Деталі', 'Detalhes'),
    ('деталі', 'detalhes'),
    ('Інформація', 'Informação'),
    ('інформація', 'informação'),
    ('Примітка', 'Nota'),
    ('примітка', 'nota'),
    ('Всього', 'Total'),
    ('всього', 'total'),
    ('Показано', 'A mostrar'),
    ('Наступна', 'Próximo'),
    ('Попередня', 'Anterior'),
    ('Перша', 'Primeira'),
    ('Остання', 'Última'),
    ('Рядків на сторінці', 'Linhas por página'),
    ('Шукати', 'Pesquisar'),
    ('Пошук', 'Pesquisar'),
    ('Gestão призначенням', 'Gestão de Atribuições'),
    ('Доступні заявки', 'Pedidos disponíveis'),
    ('Вибрані для призначення', 'Selecionados para atribuição'),
    ('ID ліфта', 'ID do elevador'),
    ('Хронологія', 'Cronologia'),
    ('Заплановано', 'Planeado'),
    ('Режим перегляду архіву.', 'Modo de arquivo.'),
    ('фальшиві виклики', 'falsos alarmes'),
    ('Надіслано сповіщення', 'Notificação enviada'),
    ('Нові повідомлення', 'Novas mensagens'),
    ('нових повідомлень', 'novas mensagens'),
    ('Немає сповіщень', 'Sem notificações'),
    ('Переглянути всі', 'Ver tudo'),
    ('Позначити як прочитане', 'Marcar como lido'),
    ('Прочитано', 'Lido'),
    ('Вийти', 'Sair'),
    ('вийти', 'sair'),
    ('Профіль', 'Perfil'),
    ('Тема оформлення', 'Tema'),
    ('Зовнішній вигляд', 'Aparência'),
    ('Створити новий обліковий запис', 'Criar nova conta'),
    ('Додати або редагувати ліфти', 'Adicionar ou editar elevadores'),
    ('призначень', 'atribuições'),
    ('призначення', 'atribuição'),
    ('Архів', 'Arquivo'),
    ('Карта', 'Mapa'),
]

seen_keys = set()
DEDUP = []
for old, new in TRANSLATIONS:
    if old not in seen_keys:
        seen_keys.add(old)
        DEDUP.append((old, new))

def translate_file(path):
    txt = path.read_text(encoding='utf-8')
    original = txt
    for old, new in DEDUP:
        if old in txt:
            txt = txt.replace(old, new)
    if txt != original:
        path.write_text(txt, encoding='utf-8')
        return True
    return False

base = Path('/workspaces/deapseak/pages')
for panel in ['admin', 'dispatcher', 'tech']:
    changed = skipped = 0
    for f in sorted((base / panel).glob('*.html')):
        if translate_file(f):
            changed += 1
        else:
            skipped += 1
    print(f'{panel}: {changed} files translated, {skipped} unchanged')
print('Done.')
